#ifndef CYDER_SRC_VERSION_H_
#define CYDER_SRC_VERSION_H_

#define CYDER_VERSION_MAJOR 0
#define CYDER_VERSION_MINOR 0
#define CYDER_VERSION_MICRO 1
#define CYDER_VERSION ""

#endif  // CYDER_SRC_VERSION_H_
