#ifndef RECYCLE_SRC_VERSION_H_
#define RECYCLE_SRC_VERSION_H_

#define RECYCLE_VERSION_MAJOR 0
#define RECYCLE_VERSION_MINOR 0
#define RECYCLE_VERSION_MICRO 1
#define RECYCLE_VERSION "0.0.0-5-g64dcbb2"

#endif  // RECYCLE_SRC_VERSION_H_
