cyder: STCThermal Class Reference
STCThermal Class Reference
STCThermal is a skeleton component model that does nothing.
#include <STCThermal.h>
Public Member Functions
const double alpha_th () const
returns alpha_th_, the thermal diffusivity []
virtual void copy (const ThermalModel &src)
copies a component and its parameters from another
std::pair< int, Temp > getMaxTempChange (mat_rsrc_ptr mat)
Returns the maximum temperature change due to a material.
std::map< int, Temp > getTempChange (mat_rsrc_ptr mat)
Returns the whole temperature change projection due to a material over time.
Temp getTempChange (Iso tope, int the_time)
Returns the temperature change due to a material.
Temp getTempChange (mat_rsrc_ptr mat, int the_time)
Returns the temperature change due to a material.
virtual void initModuleMembers (QueryEngine *qe)
initializes the model parameters from an QueryEngine object
const double k_th () const
returns k_th_, the thermal conductivity []
const std::string mat () const
returns mat_, the mat_t material through which to transport heat
virtual bool mat_acceptable (mat_rsrc_ptr mat, Radius r_lim, Temp t_lim)
This function says whether or not the material is acceptable to this repository at r_lim for the limit t_lim.
virtual std::string name ()
return the thermal model implementation type
virtual Temp peak_temp ()
gets the peak temperature that this component will experience on the boundary
virtual void print ()
standard verbose printer includes current temp and concentrations
const double r_calc () const
returns spacing_, the spacing between waste packages (uniform grid) [m]
void set_alpha_th (double alpha_th)
sets alpha_th_, the thermal diffusivity []
void set_k_th (double k_th)
sets k_th_, the thermal conductivity[]
void set_mat (std::string mat)
sets mat_, an optional name for the material through which to transport heat
void set_r_calc (double r_calc)
sets r_calc_, the radius at which the temperature is to be calculated [m]
void set_spacing (double spacing)
sets spacing_, the spacing between waste packages (uniform grid) [m]
const double spacing () const
returns spacing_, the spacing between waste packages (uniform grid) [m]
virtual Temp temp ()
gets the temperature average in the component
virtual void transportHeat (int time)
transports the heat
virtual const ThermalModelType type ()
return the thermal model implementation type
~STCThermal ()
Default destructor does nothing.
Public Member Functions inherited from ThermalModel
GeometryPtr geom ()
void set_geom (GeometryPtr geom)
set the geometry shared pointer
void set_mat_table (MatDataTablePtr mat_table)
set the MatDataTablePtr shared pointer
virtual ~ThermalModel ()
A virtual destructor.
Static Public Member Functions
static STCThermalPtr create ()
A constructor for the STC Nuclide Model that returns a shared pointer.
static STCThermalPtr create (QueryEngine *qe)
A constructor for the STC Nuclide Model that returns a shared pointer.
Protected Member Functions
void initializeSTCTable ()
initializes the STC map from the STCDB.
Protected Attributes
double alpha_th_
the thermal diffusivity []
double k_th_
the thermal conductivity []
std::string mat_
This parameter is optional and sets default alpha, k, s, r for the mat_t.
double r_calc_
the r_calc radius at which the temperature is calculated [m]
double spacing_
the spacing between waste packages (uniform grid) [m]
STCDataTablePtr table_
an STCDataTable containing a fully interpereted array of STC values indexed by isotope and time for specifically this mat_t.
Protected Attributes inherited from ThermalModel
GeometryPtr geom_
A shared pointer to the geometry of this component.
MatDataTablePtr mat_table_
A shared pointer to the MatDataTablePtr representing the material of this component.
TempHist temp_hist_
The temperature history of this component.
Temp temperature_
The temperature of this component, on average.
Private Member Functions
STCThermal ()
Default constructor for the component class.
STCThermal (QueryEngine *qe)
primary constructor reads input from XML node
Detailed Description
STCThermal is a skeleton component model that does nothing.
This disposal system component will do nothing. This Component is intended as a skeleton to guide the implementation of new Components.
The STCThermal model can be used to represent components of the disposal system such as the Waste Form, Waste Package, Buffer, Near Field, Far Field, and Envrionment.
Definition at line 30 of file STCThermal.h.
Constructor & Destructor Documentation
STCThermal::STCThermal () private
Default constructor for the component class.
Creates an empty component.
Definition at line 21 of file STCThermal.cpp.
References ThermalModel::set_geom().
Referenced by create().
STCThermal::STCThermal (QueryEngine * qe) private
primary constructor reads input from XML node
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 32 of file STCThermal.cpp.
References initModuleMembers(), and ThermalModel::set_geom().
STCThermal::~STCThermal () inline
Default destructor does nothing.
Definition at line 61 of file STCThermal.h.
Member Function Documentation
const double STCThermal::alpha_th () const inline
returns alpha_th_, the thermal diffusivity []
Definition at line 173 of file STCThermal.h.
References alpha_th_.
Referenced by copy(), and set_alpha_th().
void STCThermal::copy (const ThermalModel & src) virtual
copies a component and its parameters from another
Parameters:
src is the component being copied
Implements ThermalModel.
Definition at line 56 of file STCThermal.cpp.
References alpha_th(), k_th(), mat(), r_calc(), set_alpha_th(), ThermalModel::set_geom(), set_k_th(), set_mat(), set_r_calc(), set_spacing(), and spacing().
static STCThermalPtr STCThermal::create () inline static
A constructor for the STC Nuclide Model that returns a shared pointer.
Definition at line 49 of file STCThermal.h.
References STCThermal().
Referenced by STCThermalTest::initThermalModel(), STCThermalTest::SetUp(), STCThermalModelConstructor(), and TEST_F().
static STCThermalPtr STCThermal::create (QueryEngine * qe) inline static
A constructor for the STC Nuclide Model that returns a shared pointer.
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 56 of file STCThermal.h.
References STCThermal().
std::pair< int, Temp > STCThermal::getMaxTempChange (mat_rsrc_ptr mat)
Returns the maximum temperature change due to a material.
Parameters:
mat the material which is responsible for heating
Returns:
the time and temperature change in this medium due to mat [K]
Definition at line 139 of file STCThermal.cpp.
References getTempChange().
std::map< int, Temp > STCThermal::getTempChange (mat_rsrc_ptr mat)
Returns the whole temperature change projection due to a material over time.
Parameters:
mat the material which is responsible for heating
Returns:
the <time,temperature change> vector in this medium due to mat [K]
Definition at line 94 of file STCThermal.cpp.
References table_.
Referenced by getMaxTempChange(), and getTempChange().
Temp STCThermal::getTempChange (Iso tope, int the_time)
Returns the temperature change due to a material.
Parameters:
tope the isotope for which to collect the STC
the_time the timestep at which to report the temp change
Returns:
the temperature change in this medium due to mat [K]
Definition at line 89 of file STCThermal.cpp.
References table_.
Temp STCThermal::getTempChange (mat_rsrc_ptr mat, int the_time)
Returns the temperature change due to a material.
Parameters:
mat the material which is responsible for heating
the_time the timestep at which to report the temp change
Returns:
the temperature change in this medium due to mat [K]
Definition at line 121 of file STCThermal.cpp.
References getTempChange().
void STCThermal::initializeSTCTable () protected
initializes the STC map from the STCDB.
Parameters:
mat the mat_t struct defining the near field material:w
                             @TODO this is where the interpolation must occur.
you want to make a NEW STCDataTable out of whatever tables, indexes,
Definition at line 79 of file STCThermal.cpp.
References th_params_t::a(), alpha_th_, th_params_t::k(), k_th_, th_params_t::r(), r_calc_, th_params_t::s(), SDB, spacing_, and table_.
Referenced by initModuleMembers().
void STCThermal::initModuleMembers (QueryEngine * qe) virtual
initializes the model parameters from an QueryEngine object
Parameters:
qe is the QueryEngine object containing intialization info
use mat to set alpha, k, s, r
Implements ThermalModel.
Definition at line 44 of file STCThermal.cpp.
References initializeSTCTable(), set_alpha_th(), set_k_th(), set_mat(), set_r_calc(), and set_spacing().
Referenced by STCThermal().
const double STCThermal::k_th () const inline
returns k_th_, the thermal conductivity []
Definition at line 175 of file STCThermal.h.
References k_th_.
Referenced by copy(), and set_k_th().
const std::string STCThermal::mat () const inline
returns mat_, the mat_t material through which to transport heat
Definition at line 181 of file STCThermal.h.
References mat_.
Referenced by copy(), and set_mat().
bool STCThermal::mat_acceptable (mat_rsrc_ptr mat, Radius r_lim, Temp t_lim) virtual
This function says whether or not the material is acceptable to this repository at r_lim for the limit t_lim.
Parameters:
mat the material whose whose contribution to query
r_lim the limiting radius
t_lim the limiting temperature
Returns:
mat_acceptable (true when acceptable, false otherwise)
obviously, put some logic here.
Implements ThermalModel.
Definition at line 163 of file STCThermal.cpp.
virtual std::string STCThermal::name () inline virtual
return the thermal model implementation type
Returns:
impl_name_ the name of the ThermalModel implementation
Implements ThermalModel.
Definition at line 136 of file STCThermal.h.
Temp STCThermal::peak_temp () virtual
gets the peak temperature that this component will experience on the boundary
Implements ThermalModel.
Definition at line 155 of file STCThermal.cpp.
References ThermalModel::temp_hist_.
void STCThermal::print () virtual
standard verbose printer includes current temp and concentrations
Implements ThermalModel.
Definition at line 67 of file STCThermal.cpp.
const double STCThermal::r_calc () const inline
returns spacing_, the spacing between waste packages (uniform grid) [m]
Definition at line 179 of file STCThermal.h.
References spacing_.
Referenced by copy(), and set_r_calc().
void STCThermal::set_alpha_th (double alpha_th)
sets alpha_th_, the thermal diffusivity []
Definition at line 175 of file STCThermal.cpp.
References alpha_th(), alpha_th_, and MatTools::validate_finite_pos().
Referenced by copy(), and initModuleMembers().
void STCThermal::set_k_th (double k_th)
sets k_th_, the thermal conductivity[]
Definition at line 181 of file STCThermal.cpp.
References k_th(), k_th_, and MatTools::validate_finite_pos().
Referenced by copy(), and initModuleMembers().
void STCThermal::set_mat (std::string mat) inline
sets mat_, an optional name for the material through which to transport heat
Definition at line 171 of file STCThermal.h.
References mat(), and mat_.
Referenced by copy(), and initModuleMembers().
void STCThermal::set_r_calc (double r_calc)
sets r_calc_, the radius at which the temperature is to be calculated [m]
Definition at line 192 of file STCThermal.cpp.
References r_calc(), r_calc_, and MatTools::validate_finite_pos().
Referenced by copy(), and initModuleMembers().
void STCThermal::set_spacing (double spacing)
sets spacing_, the spacing between waste packages (uniform grid) [m]
Definition at line 187 of file STCThermal.cpp.
References spacing(), spacing_, and MatTools::validate_finite_pos().
Referenced by copy(), and initModuleMembers().
const double STCThermal::spacing () const inline
returns spacing_, the spacing between waste packages (uniform grid) [m]
Definition at line 177 of file STCThermal.h.
References spacing_.
Referenced by copy(), and set_spacing().
Temp STCThermal::temp () virtual
gets the temperature average in the component
Implements ThermalModel.
Definition at line 169 of file STCThermal.cpp.
References ThermalModel::temperature_.
void STCThermal::transportHeat (int time) virtual
transports the heat
Parameters:
time the timestep at which to transport the heat
Implements ThermalModel.
Definition at line 73 of file STCThermal.cpp.
virtual const ThermalModelType STCThermal::type () inline virtual
return the thermal model implementation type
Returns:
impl_name_ the name of the ThermalModel implementation
Implements ThermalModel.
Definition at line 129 of file STCThermal.h.
References STC_THERMAL.
Member Data Documentation
double STCThermal::alpha_th_ protected
the thermal diffusivity []
Definition at line 198 of file STCThermal.h.
Referenced by alpha_th(), initializeSTCTable(), and set_alpha_th().
double STCThermal::k_th_ protected
the thermal conductivity []
Definition at line 200 of file STCThermal.h.
Referenced by initializeSTCTable(), k_th(), and set_k_th().
std::string STCThermal::mat_ protected
This parameter is optional and sets default alpha, k, s, r for the mat_t.
Definition at line 206 of file STCThermal.h.
Referenced by mat(), and set_mat().
double STCThermal::r_calc_ protected
the r_calc radius at which the temperature is calculated [m]
Definition at line 204 of file STCThermal.h.
Referenced by initializeSTCTable(), and set_r_calc().
double STCThermal::spacing_ protected
the spacing between waste packages (uniform grid) [m]
Definition at line 202 of file STCThermal.h.
Referenced by initializeSTCTable(), r_calc(), set_spacing(), and spacing().
STCDataTablePtr STCThermal::table_ protected
an STCDataTable containing a fully interpereted array of STC values indexed by isotope and time for specifically this mat_t.
Definition at line 195 of file STCThermal.h.
Referenced by getTempChange(), and initializeSTCTable().
The documentation for this class was generated from the following files:
STCThermal.h
STCThermal.cpp