cyder: STCThermalTest Class Reference
STCThermalTest Class Reference
#include <STCThermalTests.h>
Protected Member Functions
STCThermalPtr initThermalModel ()
virtual void SetUp ()
virtual void TearDown ()
Protected Attributes
double alpha_th_
int am241_
CompMapPtr cold_comp_
mat_rsrc_ptr cold_mat_
int Cs135_
CompMapPtr cs135_comp_
mat_rsrc_ptr cs135_mat_
int Cs137_
CompMapPtr cs137_comp_
mat_rsrc_ptr cs137_mat_
CompMapPtr cs_comp_
mat_rsrc_ptr cs_mat_
STCThermalPtr default_stc_ptr_
ThermalModelPtr default_therm_model_ptr_
GeometryPtr geom_
CompMapPtr hot_comp_
mat_rsrc_ptr hot_mat_
double k_th_
Length len_five_
std::string mat_name_
MatDataTablePtr mat_table_
int one_mol_
point_t origin_
double r_calc_
Radius r_five_
Radius r_four_
double spacing_
STCThermalPtr stc_ptr_
CompMapPtr test_comp_
mat_rsrc_ptr test_mat_
double test_size_
ThermalModelPtr therm_model_ptr_
int time_
int u235_
Elem u_
Detailed Description
Definition at line 11 of file STCThermalTests.h.
Member Function Documentation
STCThermalPtr STCThermalTest::initThermalModel () protected
Definition at line 84 of file STCThermalTests.cpp.
References STCThermal::create().
void STCThermalTest::SetUp () protected virtual
Definition at line 13 of file STCThermalTests.cpp.
References STCThermal::create(), MDB, and ThermalModel::set_mat_table().
void STCThermalTest::TearDown () protected virtual
Definition at line 76 of file STCThermalTests.cpp.
Member Data Documentation
double STCThermalTest::alpha_th_ protected
Definition at line 19 of file STCThermalTests.h.
int STCThermalTest::am241_ protected
Definition at line 24 of file STCThermalTests.h.
CompMapPtr STCThermalTest::cold_comp_ protected
Definition at line 39 of file STCThermalTests.h.
mat_rsrc_ptr STCThermalTest::cold_mat_ protected
Definition at line 45 of file STCThermalTests.h.
int STCThermalTest::Cs135_ protected
Definition at line 35 of file STCThermalTests.h.
CompMapPtr STCThermalTest::cs135_comp_ protected
Definition at line 40 of file STCThermalTests.h.
mat_rsrc_ptr STCThermalTest::cs135_mat_ protected
Definition at line 46 of file STCThermalTests.h.
int STCThermalTest::Cs137_ protected
Definition at line 35 of file STCThermalTests.h.
CompMapPtr STCThermalTest::cs137_comp_ protected
Definition at line 41 of file STCThermalTests.h.
mat_rsrc_ptr STCThermalTest::cs137_mat_ protected
Definition at line 47 of file STCThermalTests.h.
CompMapPtr STCThermalTest::cs_comp_ protected
Definition at line 42 of file STCThermalTests.h.
mat_rsrc_ptr STCThermalTest::cs_mat_ protected
Definition at line 48 of file STCThermalTests.h.
STCThermalPtr STCThermalTest::default_stc_ptr_ protected
Definition at line 15 of file STCThermalTests.h.
ThermalModelPtr STCThermalTest::default_therm_model_ptr_ protected
Definition at line 17 of file STCThermalTests.h.
GeometryPtr STCThermalTest::geom_ protected
Definition at line 29 of file STCThermalTests.h.
CompMapPtr STCThermalTest::hot_comp_ protected
Definition at line 38 of file STCThermalTests.h.
mat_rsrc_ptr STCThermalTest::hot_mat_ protected
Definition at line 44 of file STCThermalTests.h.
double STCThermalTest::k_th_ protected
Definition at line 20 of file STCThermalTests.h.
Length STCThermalTest::len_five_ protected
Definition at line 31 of file STCThermalTests.h.
std::string STCThermalTest::mat_name_ protected
Definition at line 27 of file STCThermalTests.h.
MatDataTablePtr STCThermalTest::mat_table_ protected
Definition at line 28 of file STCThermalTests.h.
int STCThermalTest::one_mol_ protected
Definition at line 23 of file STCThermalTests.h.
point_t STCThermalTest::origin_ protected
Definition at line 32 of file STCThermalTests.h.
double STCThermalTest::r_calc_ protected
Definition at line 18 of file STCThermalTests.h.
Radius STCThermalTest::r_five_ protected
Definition at line 30 of file STCThermalTests.h.
Radius STCThermalTest::r_four_ protected
Definition at line 30 of file STCThermalTests.h.
double STCThermalTest::spacing_ protected
Definition at line 21 of file STCThermalTests.h.
STCThermalPtr STCThermalTest::stc_ptr_ protected
Definition at line 14 of file STCThermalTests.h.
CompMapPtr STCThermalTest::test_comp_ protected
Definition at line 37 of file STCThermalTests.h.
mat_rsrc_ptr STCThermalTest::test_mat_ protected
Definition at line 22 of file STCThermalTests.h.
double STCThermalTest::test_size_ protected
Definition at line 26 of file STCThermalTests.h.
ThermalModelPtr STCThermalTest::therm_model_ptr_ protected
Definition at line 16 of file STCThermalTests.h.
int STCThermalTest::time_ protected
Definition at line 33 of file STCThermalTests.h.
int STCThermalTest::u235_ protected
Definition at line 24 of file STCThermalTests.h.
Elem STCThermalTest::u_ protected
Definition at line 25 of file STCThermalTests.h.
The documentation for this class was generated from the following files:
STCThermalTests.h
STCThermalTests.cpp