cyder: LumpedNuclideTest Class Reference
LumpedNuclideTest Class Reference
#include <LumpedNuclideTests.h>
Protected Member Functions
LumpedNuclidePtr initNuclideModel ()
virtual void SetUp ()
virtual void TearDown ()
Protected Attributes
double adv_vel_
int am241_
LumpedNuclidePtr default_lumped_ptr_
NuclideModelPtr default_nuc_model_ptr_
GeometryPtr geom_
Length len_five_
LumpedNuclidePtr lumped_ptr_
MatDataTablePtr mat_table_
NuclideModelPtr nuc_model_ptr_
int one_kg_
point_t origin_
Radius r_five_
Radius r_four_
int some_param_
double t_t_
IsoConcMap test_C_0_
CompMapPtr test_comp_
mat_rsrc_ptr test_mat_
double test_size_
double theta_
int time_
int u235_
Elem u_
Detailed Description
Definition at line 10 of file LumpedNuclideTests.h.
Member Function Documentation
LumpedNuclidePtr LumpedNuclideTest::initNuclideModel () protected
test other formulation stringstreams...
Definition at line 68 of file LumpedNuclideTests.cpp.
References LumpedNuclide::create().
void LumpedNuclideTest::SetUp () protected virtual
?
Definition at line 17 of file LumpedNuclideTests.cpp.
References MatTools::comp_to_conc_map(), LumpedNuclide::create(), MDB, and NuclideModel::set_mat_table().
void LumpedNuclideTest::TearDown () protected virtual
Definition at line 60 of file LumpedNuclideTests.cpp.
Member Data Documentation
double LumpedNuclideTest::adv_vel_ protected
Definition at line 26 of file LumpedNuclideTests.h.
int LumpedNuclideTest::am241_ protected
Definition at line 22 of file LumpedNuclideTests.h.
LumpedNuclidePtr LumpedNuclideTest::default_lumped_ptr_ protected
Definition at line 14 of file LumpedNuclideTests.h.
NuclideModelPtr LumpedNuclideTest::default_nuc_model_ptr_ protected
Definition at line 16 of file LumpedNuclideTests.h.
GeometryPtr LumpedNuclideTest::geom_ protected
Definition at line 27 of file LumpedNuclideTests.h.
Length LumpedNuclideTest::len_five_ protected
Definition at line 29 of file LumpedNuclideTests.h.
LumpedNuclidePtr LumpedNuclideTest::lumped_ptr_ protected
Definition at line 13 of file LumpedNuclideTests.h.
MatDataTablePtr LumpedNuclideTest::mat_table_ protected
Definition at line 17 of file LumpedNuclideTests.h.
NuclideModelPtr LumpedNuclideTest::nuc_model_ptr_ protected
Definition at line 15 of file LumpedNuclideTests.h.
int LumpedNuclideTest::one_kg_ protected
Definition at line 20 of file LumpedNuclideTests.h.
point_t LumpedNuclideTest::origin_ protected
Definition at line 30 of file LumpedNuclideTests.h.
Radius LumpedNuclideTest::r_five_ protected
Definition at line 28 of file LumpedNuclideTests.h.
Radius LumpedNuclideTest::r_four_ protected
Definition at line 28 of file LumpedNuclideTests.h.
int LumpedNuclideTest::some_param_ protected
Definition at line 32 of file LumpedNuclideTests.h.
double LumpedNuclideTest::t_t_ protected
Definition at line 21 of file LumpedNuclideTests.h.
IsoConcMap LumpedNuclideTest::test_C_0_ protected
Definition at line 33 of file LumpedNuclideTests.h.
CompMapPtr LumpedNuclideTest::test_comp_ protected
Definition at line 18 of file LumpedNuclideTests.h.
mat_rsrc_ptr LumpedNuclideTest::test_mat_ protected
Definition at line 19 of file LumpedNuclideTests.h.
double LumpedNuclideTest::test_size_ protected
Definition at line 24 of file LumpedNuclideTests.h.
double LumpedNuclideTest::theta_ protected
Definition at line 25 of file LumpedNuclideTests.h.
int LumpedNuclideTest::time_ protected
Definition at line 31 of file LumpedNuclideTests.h.
int LumpedNuclideTest::u235_ protected
Definition at line 22 of file LumpedNuclideTests.h.
Elem LumpedNuclideTest::u_ protected
Definition at line 23 of file LumpedNuclideTests.h.
The documentation for this class was generated from the following files:
LumpedNuclideTests.h
LumpedNuclideTests.cpp