cyder: MixedCellNuclide Class Reference
MixedCellNuclide Class Reference
MixedCellNuclide is a nuclide model that releases material congruently with degradation of the engineered barrier material.
#include <MixedCellNuclide.h>
Public Member Functions
virtual void absorb (mat_rsrc_ptr matToAdd)
Absorbs the contents of the given Material into this MixedCellNuclide.
const BCType bc_type () const
Sets the boundary condition type used on the inner boundary.
virtual IsoFluxMap cauchy_bc (IsoConcMap c_ext, Radius r_ext)
returns the flux at the boundary, the Neumann bc
double contained_mass ()
returns the current contained contaminant mass, in kg should put this in the NuclideModel class or something.
virtual NuclideModelPtr copy (const NuclideModel &src)
copies a nuclide model and its parameters from another
const double deg_rate () const
returns the degradation rate that characterizes this model
virtual IsoConcMap dirichlet_bc ()
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
virtual mat_rsrc_ptr extract (CompMapPtr comp_to_rem, double kg_to_rem)
Extracts the contents of the given Material from this MixedCellNuclide.
virtual void initModuleMembers (QueryEngine *qe)
initializes the model parameters from a QueryEngine object
std::pair< CompMapPtr, double > inner_cauchy (NuclideModelPtr daughter)
Determines what IsoVector to remove from the daughter nuclide model based on the cauchy condition.
std::pair< CompMapPtr, double > inner_dirichlet (NuclideModelPtr daughter)
Determines what IsoVector to remove from the daughter nuclide model based on the dirichlet condition.
std::pair< CompMapPtr, double > inner_neumann (NuclideModelPtr daughter)
Determines what IsoVector to remove from the daughter nuclide model based on the neumann condition.
const bool kd_limited () const
Gets boolean indicating whether to incorporate sorption.
const int last_degraded () const
Returns the last timestamp at which this component was last degraded [integer timestamp].
virtual std::string name ()
Returns the nuclide model type name.
virtual ConcGradMap neumann_bc (IsoConcMap c_ext, Radius r_ext)
returns the concentration gradient at the boundary, the Neumann bc
const double porosity () const
The porosity (a fraction) of the material of this component.
double precipitate (int time, int iso, double mass)
Update the isotopic vector history to incorporate solubility limitation.
virtual void print ()
standard verbose printer includes current temp and concentrations
void set_bc_type (BCType bc_type)
Sets the boundary condition type used on the inner boundary.
void set_deg_rate (double cur_rate)
returns the degradation rate that characterizes this model
void set_kd_limited (bool kd_limited)
Sets boolean indicating whether to incorporate sorption.
void set_last_degraded (int last_degraded)
Set the last_degraded_ time [integer timestamp].
void set_porosity (double porosity)
Set the porosity (a fraction) of the material of this component.
void set_sol_limited (bool sol_limited)
Sets boolean indicating whether to incorporate solubility limits.
void set_tot_deg (double tot_deg)
sets the total degradation of the component
void set_v (double v)
Set the advective velocity v_ through this component.
const bool sol_limited () const
Gets boolean indicating whether to incorporate solubility limits.
double sorb (int time, int iso, double mass)
Update the isotopic vector history to incorporate sorption.
virtual std::pair< IsoVector,
double > source_term_bc ()
returns the available material source term at the outer boundary of the component
const double tot_deg () const
returns the total degradation of the component
virtual void transportNuclides (int time)
Transports nuclides from the inner to the outer boundary.
virtual NuclideModelType type ()
Returns the nuclide model type.
virtual void update (int the_time)
Updates all the hists.
IsoConcMap update_conc_hist (int time)
updates the contained concentration according to contained wastes_
IsoConcMap update_conc_hist (int time, std::deque< mat_rsrc_ptr > mats)
updates the contained concentration with mats provided
double update_degradation (int time, double cur_rate)
updates the total degradation and makes time the last degraded time.
void update_inner_bc (int the_time, std::vector< NuclideModelPtr > daughters)
Determines what IsoVector to remove from the daughter nuclide models.
void update_vec_hist (int time)
Updates the isotopic vector history at the time.
void update_vec_hist (int time, std::deque< mat_rsrc_ptr > mats)
Updates the isotopic vector history at the time.
virtual void updateNuclideParamsTable ()
Updates the NuclideParams table by adding appropriate rows to describe the parameters initializing this NuclideModel.
const double v () const
The advective velocity through this component.
double V_f ()
Gets the fluid volume, based on porosity.
virtual double V_ff ()
Gets the free fluid volume, based on porosity and degradation rate.
double V_s ()
Gets the fluid volume, based on porosity.
double V_T ()
Gets the total volume.
virtual ~MixedCellNuclide ()
Virtual destructor deletes datamembers that are object pointers.
Public Member Functions inherited from NuclideModel
virtual void addRowToNuclideParamsTable (std::string param_name, boost::any param_val)
adds a row to the NuclideModelParams table.
ConcGrad calc_conc_grad (Concentration c_ext, Concentration c_int, Radius r_ext, Radius r_int)
Returns the concentration gradient based on a simple finite difference between two datapoints.
Flux cauchy_bc (IsoConcMap c_ext, Radius r_ext, Iso tope)
IsoConcMap conc_hist (int the_time)
Returns the map of isotopes to concentrations at the time profided.
Concentration conc_hist (int the_time, Iso tope)
Returns the concetration of a certain isotope at a certain time.
double contained_mass (int the_time)
returns the current contained contaminant mass, in kg, at time
IsoVector contained_vec (int the_time)
The IsoVector representing the summed, normalized material in the component.
virtual Concentration dirichlet_bc (Iso tope)
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
virtual BCType enumerateBCType (std::string type_name)
spits out a number instead of a BCType
const GeometryPtr geom () const
Returns the geom_ data member.
int last_updated ()
returns the time at which the vec_hist and conc_hist were updated
virtual ConcGrad neumann_bc (IsoConcMap c_ext, Radius r_ext, Iso tope)
returns the concentration gradient at the boundary, the Neumann bc
void set_comp_id (int id)
Allows the component id data member to be set.
void set_geom (GeometryPtr geom)
Allows the geometry object to be set.
void set_last_updated (int new_last_updated)
sets the last time that the vec_hist and conc_hist were updated, first verifying whether last_updated is larger than last_updated_
void set_mat_table (MatDataTablePtr mat_table)
sends a pointer to the material table used by this component
virtual double source_term_bc (Iso tope)
returns the prescribed concentration at the boundary, the source term bc in kg
std::pair< IsoVector, double > vec_hist (int the_time)
Returns the IsoVector mass pair for a certain time.
std::deque< mat_rsrc_ptr > wastes ()
Returns wastes_.
virtual ~NuclideModel ()
A virtual destructor.
Static Public Member Functions
static MixedCellNuclidePtr create ()
A constructor for the Mixed Cell Nuclide Model that returns a shared pointer.
static MixedCellNuclidePtr create (QueryEngine *qe)
A constructor for the Mixed Cell Nuclide Model that returns a shared pointer.
Protected Attributes
BCType bc_type_
The type of boundary condition with which to treat the inner bc.
double deg_rate_
The degradation rate that defines this model, fraction per year.
bool kd_limited_
Boolean indicates whether to incorporate sorption. (True = yes)
int last_degraded_
the last timestamp at which this component was last degraded [integer timestamp]
double porosity_
The porosity of the material in the component, a fraction [%].
bool sol_limited_
Boolean indicates whether to incorporate solubility limits. (True = yes)
double tot_deg_
the total fraction that this component has degraded
double v_
The advective velocity through this component [m/s].
Protected Attributes inherited from NuclideModel
int comp_id_
the id of the component that this nuclidemodel is a part of
ConcHist conc_hist_
The map of times to isotopes to concentrations, in kg/m^3.
GeometryPtr geom_
A shared pointer to the geometry of the component.
int last_updated_
the time at which the histories were last updated
MatDataTablePtr mat_table_
A shared pointer to this Component's material data table.
VecHist vec_hist_
The map of times to IsoVectors.
std::deque< mat_rsrc_ptr > wastes_
A vector of the wastes contained by this component wastes(){return component_->wastes();};.
Private Member Functions
MixedCellNuclide ()
Default constructor for the nuclide model class.
MixedCellNuclide (QueryEngine *qe)
primary constructor reads input from the QueryEngine
Detailed Description
MixedCellNuclide is a nuclide model that releases material congruently with degradation of the engineered barrier material.
This disposal system nuclide model will release any contained contaminants at a rate corresponding solely to its degradation rate. That is, if the component degrades at a rate of 15% per year, then 15% of the contaminant will be made available at the boundaries. This NuclideModel will follow J. Ahn's congruent release model.
The MixedCellNuclide model can be used to represent nuclide models of the disposal system such as the Waste Form, Waste Package, Buffer, and Near Field. However, since the Far Field and the Envrionment do not degrade, these are not well represented by the MixedCellNuclide model.
Definition at line 36 of file MixedCellNuclide.h.
Constructor & Destructor Documentation
MixedCellNuclide::MixedCellNuclide () private
Default constructor for the nuclide model class.
Creates an empty nuclide model.
Definition at line 24 of file MixedCellNuclide.cpp.
References NuclideModel::conc_hist_, NuclideModel::last_updated_, NuclideModel::set_geom(), NuclideModel::vec_hist_, and NuclideModel::wastes_.
Referenced by create().
MixedCellNuclide::MixedCellNuclide (QueryEngine * qe) private
primary constructor reads input from the QueryEngine
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 42 of file MixedCellNuclide.cpp.
References NuclideModel::conc_hist_, initModuleMembers(), NuclideModel::last_updated_, NuclideModel::set_geom(), NuclideModel::vec_hist_, and NuclideModel::wastes_.
MixedCellNuclide::~MixedCellNuclide () virtual
Virtual destructor deletes datamembers that are object pointers.
Definition at line 61 of file MixedCellNuclide.cpp.
Member Function Documentation
void MixedCellNuclide::absorb (mat_rsrc_ptr matToAdd) virtual
Absorbs the contents of the given Material into this MixedCellNuclide.
Parameters:
matToAdd the MixedCellNuclide to be absorbed
Implements NuclideModel.
Definition at line 135 of file MixedCellNuclide.cpp.
References NuclideModel::wastes_.
Referenced by update_inner_bc().
const BCType MixedCellNuclide::bc_type () const inline
Sets the boundary condition type used on the inner boundary.
Definition at line 360 of file MixedCellNuclide.h.
References bc_type_.
Referenced by copy(), and set_bc_type().
IsoFluxMap MixedCellNuclide::cauchy_bc (IsoConcMap c_ext, Radius r_ext) virtual
returns the flux at the boundary, the Neumann bc
Returns:
qC the solute flux at the boundary in kg/m^2/s
Implements NuclideModel.
Definition at line 287 of file MixedCellNuclide.cpp.
References NuclideModel::mat_table_, neumann_bc(), and v().
double MixedCellNuclide::contained_mass ()
returns the current contained contaminant mass, in kg should put this in the NuclideModel class or something.
Returns:
contained_mass_[now] throughout the component volume, in kg
Definition at line 199 of file MixedCellNuclide.cpp.
References last_degraded().
NuclideModelPtr MixedCellNuclide::copy (const NuclideModel & src) virtual
copies a nuclide model and its parameters from another
Parameters:
src is the nuclide model being copied
Implements NuclideModel.
Definition at line 87 of file MixedCellNuclide.cpp.
References bc_type(), NuclideModel::conc_hist_, deg_rate(), NuclideModel::geom(), NuclideModel::geom_, kd_limited(), porosity(), set_bc_type(), set_deg_rate(), NuclideModel::set_geom(), set_kd_limited(), set_last_degraded(), set_porosity(), set_sol_limited(), set_tot_deg(), set_v(), sol_limited(), v(), NuclideModel::vec_hist_, and NuclideModel::wastes_.
static MixedCellNuclidePtr MixedCellNuclide::create () inline static
A constructor for the Mixed Cell Nuclide Model that returns a shared pointer.
Definition at line 60 of file MixedCellNuclide.h.
References MixedCellNuclide().
Referenced by MixedCellNuclideTest::initNuclideModel(), MixedCellNuclideModelConstructor(), NuclideModelFactory::nuclideModel(), MixedCellNuclideTest::SetUp(), and TEST_F().
static MixedCellNuclidePtr MixedCellNuclide::create (QueryEngine * qe) inline static
A constructor for the Mixed Cell Nuclide Model that returns a shared pointer.
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 67 of file MixedCellNuclide.h.
References MixedCellNuclide().
const double MixedCellNuclide::deg_rate () const inline
returns the degradation rate that characterizes this model
Returns:
deg_rate_ fraction per year
Definition at line 183 of file MixedCellNuclide.h.
References deg_rate_.
Referenced by copy(), transportNuclides(), update_degradation(), and updateNuclideParamsTable().
IsoConcMap MixedCellNuclide::dirichlet_bc () virtual
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
Returns:
C the concentration at the boundary in kg/m^3 for each isotope
Implements NuclideModel.
Definition at line 243 of file MixedCellNuclide.cpp.
References MatTools::comp_to_conc_map(), source_term_bc(), and V_ff().
Referenced by inner_neumann().
mat_rsrc_ptr MixedCellNuclide::extract (CompMapPtr comp_to_rem, double kg_to_rem) virtual
Extracts the contents of the given Material from this MixedCellNuclide.
Use this function for decrementing a MixedCellNuclide's mass balance after transferring through a link.
Parameters:
comp_to_rem the composition to decrement against this MixedCellNuclide
kg_to_rem the amount in kg to decrement against this MixedCellNuclide
Returns:
the material extracted
Implements NuclideModel.
Definition at line 146 of file MixedCellNuclide.cpp.
References MatTools::extract(), NuclideModel::last_updated(), update(), and NuclideModel::wastes_.
void MixedCellNuclide::initModuleMembers (QueryEngine * qe) virtual
initializes the model parameters from a QueryEngine object
Parameters:
qe is the QueryEngine object containing intialization info
Implements NuclideModel.
Definition at line 65 of file MixedCellNuclide.cpp.
References NuclideModel::enumerateBCType(), set_bc_type(), set_deg_rate(), set_kd_limited(), set_porosity(), set_sol_limited(), and set_v().
Referenced by MixedCellNuclide().
pair< CompMapPtr, double > MixedCellNuclide::inner_cauchy (NuclideModelPtr daughter)
Determines what IsoVector to remove from the daughter nuclide model based on the cauchy condition.
Parameters:
daughter nuclide_model of an internal component. there may be many.
Definition at line 438 of file MixedCellNuclide.cpp.
References inner_dirichlet(), and inner_neumann().
Referenced by update_inner_bc().
pair< CompMapPtr, double > MixedCellNuclide::inner_dirichlet (NuclideModelPtr daughter)
Determines what IsoVector to remove from the daughter nuclide model based on the dirichlet condition.
Parameters:
daughter nuclide_model of an internal component. there may be many.
Definition at line 421 of file MixedCellNuclide.cpp.
References MatTools::conc_to_comp_map(), porosity(), MatTools::scaleConcMap(), tot_deg(), and v().
Referenced by inner_cauchy(), and update_inner_bc().
pair< CompMapPtr, double > MixedCellNuclide::inner_neumann (NuclideModelPtr daughter)
Determines what IsoVector to remove from the daughter nuclide model based on the neumann condition.
Parameters:
daughter nuclide_model of an internal component. there may be many.
Definition at line 399 of file MixedCellNuclide.cpp.
References MatTools::conc_to_comp_map(), dirichlet_bc(), NuclideModel::geom(), NuclideModel::mat_table_, porosity(), MatTools::scaleConcMap(), and tot_deg().
Referenced by inner_cauchy(), and update_inner_bc().
const bool MixedCellNuclide::kd_limited () const inline
Gets boolean indicating whether to incorporate sorption.
Definition at line 345 of file MixedCellNuclide.h.
References kd_limited_.
Referenced by copy(), set_kd_limited(), sorb(), and updateNuclideParamsTable().
const int MixedCellNuclide::last_degraded () const inline
Returns the last timestamp at which this component was last degraded [integer timestamp].
Definition at line 333 of file MixedCellNuclide.h.
References last_degraded_.
Referenced by contained_mass(), set_last_degraded(), source_term_bc(), and update_degradation().
virtual std::string MixedCellNuclide::name () inline virtual
Returns the nuclide model type name.
Implements NuclideModel.
Definition at line 127 of file MixedCellNuclide.h.
ConcGradMap MixedCellNuclide::neumann_bc (IsoConcMap c_ext, Radius r_ext) virtual
returns the concentration gradient at the boundary, the Neumann bc
Returns:
dCdx the concentration gradient at the boundary in kg/m^3
Implements NuclideModel.
Definition at line 252 of file MixedCellNuclide.cpp.
References NuclideModel::calc_conc_grad(), MatTools::comp_to_conc_map(), NuclideModel::geom(), and V_ff().
Referenced by cauchy_bc().
const double MixedCellNuclide::porosity () const inline
The porosity (a fraction) of the material of this component.
[%]
Definition at line 313 of file MixedCellNuclide.h.
References porosity_.
Referenced by copy(), inner_dirichlet(), inner_neumann(), set_porosity(), updateNuclideParamsTable(), V_f(), V_ff(), and V_s().
double MixedCellNuclide::precipitate (int time, int iso, double mass)
Update the isotopic vector history to incorporate solubility limitation.
Parameters:
time the time at which to update the vector history
iso the isotope to update
mass the total mass of that isotope in the component
Returns:
the solubility limited mass
Definition at line 459 of file MixedCellNuclide.cpp.
References MatTools::isoToElem(), SolLim::m_aff(), NuclideModel::mat_table_, sol_limited(), and V_ff().
Referenced by source_term_bc().
void MixedCellNuclide::print () virtual
standard verbose printer includes current temp and concentrations
Implements NuclideModel.
Definition at line 130 of file MixedCellNuclide.cpp.
void MixedCellNuclide::set_bc_type (BCType bc_type) inline
Sets the boundary condition type used on the inner boundary.
Definition at line 363 of file MixedCellNuclide.h.
References bc_type(), and bc_type_.
Referenced by copy(), and initModuleMembers().
void MixedCellNuclide::set_deg_rate (double cur_rate)
returns the degradation rate that characterizes this model
Parameters:
cur_rate the current degradation rate, a fraction per timestep, between 0 and 1
Exceptions:
CycRangeException if deg_rate not between 0 and 1 inclusive
Definition at line 167 of file MixedCellNuclide.cpp.
References deg_rate_.
Referenced by copy(), initModuleMembers(), and update_degradation().
void MixedCellNuclide::set_kd_limited (bool kd_limited) inline
Sets boolean indicating whether to incorporate sorption.
Definition at line 342 of file MixedCellNuclide.h.
References kd_limited(), and kd_limited_.
Referenced by copy(), and initModuleMembers().
void MixedCellNuclide::set_last_degraded (int last_degraded) inline
Set the last_degraded_ time [integer timestamp].
Definition at line 328 of file MixedCellNuclide.h.
References last_degraded(), and last_degraded_.
Referenced by copy(), and update_degradation().
void MixedCellNuclide::set_porosity (double porosity)
Set the porosity (a fraction) of the material of this component.
[%]
Definition at line 183 of file MixedCellNuclide.cpp.
References porosity(), and porosity_.
Referenced by copy(), and initModuleMembers().
void MixedCellNuclide::set_sol_limited (bool sol_limited) inline
Sets boolean indicating whether to incorporate solubility limits.
Definition at line 336 of file MixedCellNuclide.h.
References sol_limited(), and sol_limited_.
Referenced by copy(), and initModuleMembers().
void MixedCellNuclide::set_tot_deg (double tot_deg) inline
sets the total degradation of the component
Definition at line 303 of file MixedCellNuclide.h.
References tot_deg(), and tot_deg_.
Referenced by copy(), and update_degradation().
void MixedCellNuclide::set_v (double v) inline
Set the advective velocity v_ through this component.
[m/s]
Definition at line 318 of file MixedCellNuclide.h.
References v(), and v_.
Referenced by copy(), and initModuleMembers().
const bool MixedCellNuclide::sol_limited () const inline
Gets boolean indicating whether to incorporate solubility limits.
Definition at line 339 of file MixedCellNuclide.h.
References sol_limited_.
Referenced by copy(), precipitate(), set_sol_limited(), and updateNuclideParamsTable().
double MixedCellNuclide::sorb (int time, int iso, double mass)
Update the isotopic vector history to incorporate sorption.
Parameters:
time the time at which to update the vector history
iso the isotope to update
mass the total mass of that isotope in the component
Returns:
the sorption limited mass
Definition at line 450 of file MixedCellNuclide.cpp.
References MatTools::isoToElem(), kd_limited(), SolLim::m_ff(), NuclideModel::mat_table_, tot_deg(), V_f(), and V_s().
Referenced by source_term_bc().
pair< IsoVector, double > MixedCellNuclide::source_term_bc () virtual
returns the available material source term at the outer boundary of the component
Returns:
m_ij the available source term outer boundary condition
Implements NuclideModel.
Definition at line 204 of file MixedCellNuclide.cpp.
References NuclideModel::geom_, last_degraded(), precipitate(), sorb(), MatTools::sum_mats(), V_ff(), and NuclideModel::wastes_.
Referenced by dirichlet_bc().
const double MixedCellNuclide::tot_deg () const inline
returns the total degradation of the component
Definition at line 300 of file MixedCellNuclide.h.
References tot_deg_.
Referenced by inner_dirichlet(), inner_neumann(), set_tot_deg(), sorb(), update_degradation(), and V_ff().
void MixedCellNuclide::transportNuclides (int time) virtual
Transports nuclides from the inner to the outer boundary.
Parameters:
time the timestep at which to transport the nuclides
Implements NuclideModel.
Definition at line 159 of file MixedCellNuclide.cpp.
References deg_rate(), update(), and update_degradation().
virtual NuclideModelType MixedCellNuclide::type () inline virtual
Returns the nuclide model type.
Implements NuclideModel.
Definition at line 122 of file MixedCellNuclide.h.
References MIXEDCELL_NUCLIDE.
void MixedCellNuclide::update (int the_time) virtual
Updates all the hists.
Parameters:
the_time the time at which to update the history
Implements NuclideModel.
Definition at line 123 of file MixedCellNuclide.cpp.
References NuclideModel::set_last_updated(), update_conc_hist(), and update_vec_hist().
Referenced by extract(), and transportNuclides().
IsoConcMap MixedCellNuclide::update_conc_hist (int time)
updates the contained concentration according to contained wastes_
Parameters:
time the time at which to update the degradation
Returns:
the current isotopic concentration map at the outer border
Definition at line 303 of file MixedCellNuclide.cpp.
References NuclideModel::wastes_.
Referenced by update().
IsoConcMap MixedCellNuclide::update_conc_hist (int time, std::deque< mat_rsrc_ptr > mats)
updates the contained concentration with mats provided
Parameters:
time the time at which to update the degradation
mats the vector of materials contained in the component
Returns:
the current isotopic concentration map at the outer border
double MixedCellNuclide::update_degradation (int time, double cur_rate)
updates the total degradation and makes time the last degraded time.
Parameters:
time the time at which to update the degradation
cur_rate is the degradation rate since the last degradation, fraction.
Definition at line 329 of file MixedCellNuclide.cpp.
References deg_rate(), last_degraded(), set_deg_rate(), set_last_degraded(), set_tot_deg(), tot_deg(), and tot_deg_.
Referenced by transportNuclides().
void MixedCellNuclide::update_inner_bc (int the_time, std::vector< NuclideModelPtr > daughters) virtual
Determines what IsoVector to remove from the daughter nuclide models.
Parameters:
time the timestep at which the nuclides should be transported
daughter nuclide_model of an internal component. there may be many.
Implements NuclideModel.
Definition at line 352 of file MixedCellNuclide.cpp.
References absorb(), bc_type_, CAUCHY, DIRICHLET, inner_cauchy(), inner_dirichlet(), inner_neumann(), NEUMANN, and SOURCE_TERM.
void MixedCellNuclide::update_vec_hist (int time)
Updates the isotopic vector history at the time.
Parameters:
time the time at which to update the vector history, according to wastes_ last_degraded_ time.
Definition at line 347 of file MixedCellNuclide.cpp.
References MatTools::sum_mats(), NuclideModel::vec_hist_, and NuclideModel::wastes_.
Referenced by update().
void MixedCellNuclide::update_vec_hist (int time, std::deque< mat_rsrc_ptr > mats)
Updates the isotopic vector history at the time.
Parameters:
time the time at which to update the vector history
mats the deque of materials to include in the history, usually wastes_
Exceptions:
an exception if the time provided is less than the last_degraded_ time.
void MixedCellNuclide::updateNuclideParamsTable () virtual
Updates the NuclideParams table by adding appropriate rows to describe the parameters initializing this NuclideModel.
Implements NuclideModel.
Definition at line 111 of file MixedCellNuclide.cpp.
References deg_rate(), kd_limited(), NuclideModel::mat_table_, porosity(), sol_limited(), and v().
const double MixedCellNuclide::v () const inline
The advective velocity through this component.
[m/s]
Definition at line 323 of file MixedCellNuclide.h.
References v_.
Referenced by cauchy_bc(), copy(), inner_dirichlet(), set_v(), and updateNuclideParamsTable().
double MixedCellNuclide::V_f ()
Gets the fluid volume, based on porosity.
Definition at line 470 of file MixedCellNuclide.cpp.
References porosity(), and V_T().
Referenced by sorb().
double MixedCellNuclide::V_ff () virtual
Gets the free fluid volume, based on porosity and degradation rate.
Implements NuclideModel.
Definition at line 479 of file MixedCellNuclide.cpp.
References porosity(), tot_deg(), and V_T().
Referenced by dirichlet_bc(), neumann_bc(), precipitate(), and source_term_bc().
double MixedCellNuclide::V_s ()
Gets the fluid volume, based on porosity.
Definition at line 474 of file MixedCellNuclide.cpp.
References porosity(), and V_T().
Referenced by sorb().
double MixedCellNuclide::V_T () virtual
Gets the total volume.
Implements NuclideModel.
Definition at line 483 of file MixedCellNuclide.cpp.
References NuclideModel::geom_.
Referenced by V_f(), V_ff(), and V_s().
Member Data Documentation
BCType MixedCellNuclide::bc_type_ protected
The type of boundary condition with which to treat the inner bc.
Definition at line 392 of file MixedCellNuclide.h.
Referenced by bc_type(), set_bc_type(), and update_inner_bc().
double MixedCellNuclide::deg_rate_ protected
The degradation rate that defines this model, fraction per year.
Definition at line 374 of file MixedCellNuclide.h.
Referenced by deg_rate(), and set_deg_rate().
bool MixedCellNuclide::kd_limited_ protected
Boolean indicates whether to incorporate sorption. (True = yes)
Definition at line 389 of file MixedCellNuclide.h.
Referenced by kd_limited(), and set_kd_limited().
int MixedCellNuclide::last_degraded_ protected
the last timestamp at which this component was last degraded [integer timestamp]
Definition at line 380 of file MixedCellNuclide.h.
Referenced by last_degraded(), and set_last_degraded().
double MixedCellNuclide::porosity_ protected
The porosity of the material in the component, a fraction [%].
Definition at line 383 of file MixedCellNuclide.h.
Referenced by porosity(), and set_porosity().
bool MixedCellNuclide::sol_limited_ protected
Boolean indicates whether to incorporate solubility limits. (True = yes)
Definition at line 386 of file MixedCellNuclide.h.
Referenced by set_sol_limited(), and sol_limited().
double MixedCellNuclide::tot_deg_ protected
the total fraction that this component has degraded
Definition at line 377 of file MixedCellNuclide.h.
Referenced by set_tot_deg(), tot_deg(), and update_degradation().
double MixedCellNuclide::v_ protected
The advective velocity through this component [m/s].
Definition at line 369 of file MixedCellNuclide.h.
Referenced by set_v(), and v().
The documentation for this class was generated from the following files:
MixedCellNuclide.h
MixedCellNuclide.cpp