cyder: STCDataTable Class Reference
STCDataTable Class Reference
The STCDataTable class provides an interface to the stc_data.sqlite database, providing a robust and correct mass lookup by isotope.
#include <STCDataTable.h>
Public Member Functions
int indToIso (int ind)
calls checkValidity on the iso and then returns its row value.
int indToTime (int ind)
calls checkValidity on the time and then returns its row value.
int indToVal (int ind, std::map< int, int > index)
calls check_validity on the isotope and then returns its row value.
std::map< Iso, int > isoIndex ()
int isoToInd (Iso tope)
calls check_validity on the isotope and then returns its row index.
std::string name ()
returns the string name of the material that this table represents
double stc (Iso tope, int the_time)
get the specific temperature change [K] for an isotope in this material.
STCDataTable (std::string name, boost::multi_array< double, 2 > stc_array, std::map< Iso, int > iso_index, std::map< int, int > time_index)
Detailed constructor for the STCDataTable class Fully initializes the object.
std::map< int, int > timeIndex ()
int timeToInd (int the_time)
calls checkValidity on the time and then returns its row index.
~STCDataTable ()
Destructor for the NullFacility class.
Protected Member Functions
void checkValidity (int val, std::map< int, int > index)
checks whether this element has a row entry in the table.
Protected Attributes
std::map< Iso, int > iso_index_
a map for isotope index lookup in the stc array.
std::string name_
The name of the material that this table represents, specifically, the name of the table in the DB.
boost::multi_array< double, 2 > stc_array_
The array of stc data.
th_params_t th_params_
The struct representing this material.
std::map< int, int > time_index_
a map for time index lookup in the stc array.
Private Member Functions
STCDataTable ()
Default constructor for the STCDataTable class.
Detailed Description
The STCDataTable class provides an interface to the stc_data.sqlite database, providing a robust and correct mass lookup by isotope.
Definition at line 43 of file STCDataTable.h.
Constructor & Destructor Documentation
STCDataTable::STCDataTable () private
Default constructor for the STCDataTable class.
Default values are zeros and null strings
Definition at line 18 of file STCDataTable.cpp.
STCDataTable::STCDataTable (std::string name, boost::multi_array< double, 2 > stc_array, std::map< Iso, int > iso_index, std::map< int, int > time_index)
Detailed constructor for the STCDataTable class Fully initializes the object.
Parameters:
name the name_ data member, a string naming this material
stc_array the stc_array_ data member, a 2d array of stc values (n_isos x n_timesteps)
iso_index the iso_index_ data member, mapping the isotope IDs to indices
time_index the time_index_ data member, mapping the timestep values to indices
STCDataTable::~STCDataTable ()
Destructor for the NullFacility class.
Makes certain to delete all appropriate data on the stack.
Definition at line 34 of file STCDataTable.cpp.
Member Function Documentation
void STCDataTable::checkValidity (int val, std::map< int, int > index) protected
checks whether this element has a row entry in the table.
ideally all of them will...
Parameters:
val the value to find in the index
index the map between values and indices
Exceptions:
CycException when theres some drama
Definition at line 98 of file STCDataTable.cpp.
Referenced by isoToInd(), and timeToInd().
int STCDataTable::indToIso (int ind)
calls checkValidity on the iso and then returns its row value.
Parameters:
ind the index of the value of interest
Returns:
the value of that index in the stc_array
Definition at line 73 of file STCDataTable.cpp.
References indToVal(), and iso_index_.
int STCDataTable::indToTime (int ind)
calls checkValidity on the time and then returns its row value.
Parameters:
ind the index of the value of interest
Returns:
the value of that index in the stc_array
Definition at line 78 of file STCDataTable.cpp.
References indToVal(), and time_index_.
int STCDataTable::indToVal (int ind, std::map< int, int > index)
calls check_validity on the isotope and then returns its row value.
Parameters:
index the map of indices for this table in which the val exists
ind the index of the row of that isotope
Returns:
tope the isotope identifier (e.g., 92235)
Definition at line 56 of file STCDataTable.cpp.
Referenced by indToIso(), and indToTime().
std::map<Iso, int> STCDataTable::isoIndex () inline
Definition at line 131 of file STCDataTable.h.
References iso_index_.
int STCDataTable::isoToInd (Iso tope)
calls check_validity on the isotope and then returns its row index.
Parameters:
tope the isotope identifier (e.g., 92235)
Returns:
the index of the row of that isotope
Definition at line 91 of file STCDataTable.cpp.
References checkValidity(), and iso_index_.
Referenced by stc().
std::string STCDataTable::name () inline
returns the string name of the material that this table represents
Returns:
name_
Definition at line 86 of file STCDataTable.h.
References name_.
double STCDataTable::stc (Iso tope, int the_time)
get the specific temperature change [K] for an isotope in this material.
Parameters:
tope an identifier of type Iso, which is an int
the_time,an integer indicating the timestep at which to determine the stc
Returns:
stc a double, the specific temperature change at time the_time [K]
interpolate between closest times
Definition at line 38 of file STCDataTable.cpp.
References isoToInd(), stc_array_, and timeToInd().
std::map<int, int> STCDataTable::timeIndex () inline
Definition at line 130 of file STCDataTable.h.
References time_index_.
int STCDataTable::timeToInd (int the_time)
calls checkValidity on the time and then returns its row index.
Parameters:
the_time the timestep value (e.g., 200)
Returns:
the index of that time in the stc_array
Definition at line 84 of file STCDataTable.cpp.
References checkValidity(), and time_index_.
Referenced by stc().
Member Data Documentation
std::map<Iso, int> STCDataTable::iso_index_ protected
a map for isotope index lookup in the stc array.
Definition at line 165 of file STCDataTable.h.
Referenced by indToIso(), isoIndex(), and isoToInd().
std::string STCDataTable::name_ protected
The name of the material that this table represents, specifically, the name of the table in the DB.
Definition at line 149 of file STCDataTable.h.
Referenced by name().
boost::multi_array<double, 2> STCDataTable::stc_array_ protected
The array of stc data.
It's a 2d array with dimensions iso x time. Think of it as stc[n_isos][n_timesteps].
Definition at line 160 of file STCDataTable.h.
Referenced by stc().
th_params_t STCDataTable::th_params_ protected
The struct representing this material.
Definition at line 154 of file STCDataTable.h.
std::map<int, int> STCDataTable::time_index_ protected
a map for time index lookup in the stc array.
Definition at line 170 of file STCDataTable.h.
Referenced by indToTime(), timeIndex(), and timeToInd().
The documentation for this class was generated from the following files:
STCDataTable.h
STCDataTable.cpp