cyder: ThermalModelFactory Class Reference
ThermalModelFactory Class Reference
A class which selects and produces concrete instances of ThermalModels.
#include <ThermalModelFactory.h>
Static Public Member Functions
static ThermalModelPtr thermalModel (QueryEngine *qe)
Creates a concrete ThermalModel from a QueryEngine pointer.
static ThermalModelPtr thermalModel (QueryEngine *qe, MatDataTablePtr mat_table, GeometryPtr geom)
Creates a concrete ThermalModel from a QueryEngine pointer as well as geometry and material data.
static ThermalModelPtr thermalModel (ThermalModelPtr src, MatDataTablePtr mat_table, GeometryPtr geom)
Creates a copy of a ThermalModel from another ThermalModel as well as geometry and material data.
Static Protected Member Functions
static ThermalModelType thermalEnum (std::string type_name)
Enumerates a string if it is one of the named ThermalModelTypes.
Static Protected Attributes
static std::string thermal_type_names_ [LAST_THERMAL]
ThermalModelType names list.
Detailed Description
A class which selects and produces concrete instances of ThermalModels.
Definition at line 19 of file ThermalModelFactory.h.
Member Function Documentation
ThermalModelType ThermalModelFactory::thermalEnum (std::string type_name) static protected
Enumerates a string if it is one of the named ThermalModelTypes.
Parameters:
type the name of the ThermalModelType (e.g., StubThermal)
Definition at line 83 of file ThermalModelFactory.cpp.
References LAST_THERMAL, and thermal_type_names_.
Referenced by thermalModel().
ThermalModelPtr ThermalModelFactory::thermalModel (QueryEngine * qe) static
Creates a concrete ThermalModel from a QueryEngine pointer.
This will have and uninitialized geometry and material table?
Parameters:
qe query engine pointer describing the thermal model
Definition at line 26 of file ThermalModelFactory.cpp.
References LumpedThermal::create(), StubThermal::create(), LUMPED_THERMAL, STC_THERMAL, STUB_THERMAL, and thermalEnum().
Referenced by Component::copyThermalModel(), Cyder::initModuleMembers(), Component::thermal_model(), and thermalModel().
ThermalModelPtr ThermalModelFactory::thermalModel (QueryEngine * qe, MatDataTablePtr mat_table, GeometryPtr geom) static
Creates a concrete ThermalModel from a QueryEngine pointer as well as geometry and material data.
Parameters:
qe query engine pointer describing the thermal model
mat_table a pointer to the material table
geom a pointer to the Geometry object
Definition at line 49 of file ThermalModelFactory.cpp.
References thermalModel().
ThermalModelPtr ThermalModelFactory::thermalModel (ThermalModelPtr src, MatDataTablePtr mat_table, GeometryPtr geom) static
Creates a copy of a ThermalModel from another ThermalModel as well as geometry and material data.
Parameters:
src the original ThermalModel
mat_table a pointer to the material table
geom a pointer to the Geometry object
Definition at line 58 of file ThermalModelFactory.cpp.
References LumpedThermal::create(), StubThermal::create(), LUMPED_THERMAL, STC_THERMAL, and STUB_THERMAL.
Member Data Documentation
std::string ThermalModelFactory::thermal_type_names_ static protected
Initial value:
 {
  "LumpedThermal",
  "STCThermal",
  "StubThermal"
}
ThermalModelType names list.
Definition at line 61 of file ThermalModelFactory.h.
Referenced by thermalEnum().
The documentation for this class was generated from the following files:
ThermalModelFactory.h
ThermalModelFactory.cpp