cyder: NuclideModel Class Reference
NuclideModel Class Reference
Abstract interface for Cyder nuclide transport.
#include <NuclideModel.h>
Public Member Functions
virtual void absorb (mat_rsrc_ptr matToAdd)=0
Absorbs the contents of the given Material into this NuclideModel.
virtual void addRowToNuclideParamsTable (std::string param_name, boost::any param_val)
adds a row to the NuclideModelParams table.
ConcGrad calc_conc_grad (Concentration c_ext, Concentration c_int, Radius r_ext, Radius r_int)
Returns the concentration gradient based on a simple finite difference between two datapoints.
virtual IsoFluxMap cauchy_bc (IsoConcMap c_ext, Radius r_ext)=0
returns the flux at the boundary, the Neumann bc
Flux cauchy_bc (IsoConcMap c_ext, Radius r_ext, Iso tope)
IsoConcMap conc_hist (int the_time)
Returns the map of isotopes to concentrations at the time profided.
Concentration conc_hist (int the_time, Iso tope)
Returns the concetration of a certain isotope at a certain time.
double contained_mass (int the_time)
returns the current contained contaminant mass, in kg, at time
IsoVector contained_vec (int the_time)
The IsoVector representing the summed, normalized material in the component.
virtual NuclideModelPtr copy (const NuclideModel &src)=0
copies a component and its parameters from another
virtual IsoConcMap dirichlet_bc ()=0
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
virtual Concentration dirichlet_bc (Iso tope)
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
virtual BCType enumerateBCType (std::string type_name)
spits out a number instead of a BCType
virtual mat_rsrc_ptr extract (CompMapPtr comp_to_rem, double kg_to_rem)=0
Extracts the contents of the given composition from this NuclideModel.
const GeometryPtr geom () const
Returns the geom_ data member.
virtual void initModuleMembers (QueryEngine *qe)=0
initializes the model parameters from a Query Engine
int last_updated ()
returns the time at which the vec_hist and conc_hist were updated
virtual std::string name ()=0
returns the name of the NuclideModelType of the model
virtual ConcGradMap neumann_bc (IsoConcMap c_ext, Radius r_ext)=0
returns the concentration gradient at the boundary, the Neumann bc
virtual ConcGrad neumann_bc (IsoConcMap c_ext, Radius r_ext, Iso tope)
returns the concentration gradient at the boundary, the Neumann bc
virtual void print ()=0
standard verbose printer explains the model
void set_comp_id (int id)
Allows the component id data member to be set.
void set_geom (GeometryPtr geom)
Allows the geometry object to be set.
void set_last_updated (int new_last_updated)
sets the last time that the vec_hist and conc_hist were updated, first verifying whether last_updated is larger than last_updated_
void set_mat_table (MatDataTablePtr mat_table)
sends a pointer to the material table used by this component
virtual std::pair< IsoVector,
double > source_term_bc ()=0
returns the available material source term at the outer boundary of the component in kg
virtual double source_term_bc (Iso tope)
returns the prescribed concentration at the boundary, the source term bc in kg
virtual void transportNuclides (int time)=0
Transports nuclides from the inner boundary to the outer boundary in this component.
virtual NuclideModelType type ()=0
returns the NuclideModelType of the model
virtual void update (int the_time)=0
Update the hists at a certain time.
virtual void update_inner_bc (int the_time, std::vector< NuclideModelPtr > daughters)=0
Determines what IsoVector to remove from the daughter nuclide models.
virtual void updateNuclideParamsTable ()=0
All NuclideModels should implement a function that updates the Params table just once, to be called from the NuclideModelFactor right after initialization.
virtual double V_ff ()=0
virtual double V_T ()=0
std::pair< IsoVector, double > vec_hist (int the_time)
Returns the IsoVector mass pair for a certain time.
std::deque< mat_rsrc_ptr > wastes ()
Returns wastes_.
virtual ~NuclideModel ()
A virtual destructor.
Protected Attributes
int comp_id_
the id of the component that this nuclidemodel is a part of
ConcHist conc_hist_
The map of times to isotopes to concentrations, in kg/m^3.
GeometryPtr geom_
A shared pointer to the geometry of the component.
int last_updated_
the time at which the histories were last updated
MatDataTablePtr mat_table_
A shared pointer to this Component's material data table.
VecHist vec_hist_
The map of times to IsoVectors.
std::deque< mat_rsrc_ptr > wastes_
A vector of the wastes contained by this component wastes(){return component_->wastes();};.
Detailed Description
Abstract interface for Cyder nuclide transport.
NuclideModels such as MixedCell, OneDimPPM, etc., will share a virtual interface defined here so that information passing concerning hydrogeologic nuclide transport fluxes and other boundary conditions can be conducted between components within the repository.
Definition at line 65 of file NuclideModel.h.
Constructor & Destructor Documentation
virtual NuclideModel::~NuclideModel () inline virtual
A virtual destructor.
Definition at line 71 of file NuclideModel.h.
Member Function Documentation
virtual void NuclideModel::absorb (mat_rsrc_ptr matToAdd) pure virtual
Absorbs the contents of the given Material into this NuclideModel.
Parameters:
matToAdd the NuclideModel to be absorbed
Implemented in OneDimPPMNuclide, LumpedNuclide, MixedCellNuclide, DegRateNuclide, and StubNuclide.
virtual void NuclideModel::addRowToNuclideParamsTable (std::string param_name, boost::any param_val) inline virtual
adds a row to the NuclideModelParams table.
Parameters:
the name of the variable to record
the variable value, to be cast with boost::any_cast
Definition at line 211 of file NuclideModel.h.
References comp_id_.
ConcGrad NuclideModel::calc_conc_grad (Concentration c_ext, Concentration c_int, Radius r_ext, Radius r_int) inline
Returns the concentration gradient based on a simple finite difference between two datapoints.
Parameters:
c_ext external concentration, at r_ext
c_int internal concentration, at r_int
r_ext external radial midpoint
r_int interal radil midpoint
Definition at line 358 of file NuclideModel.h.
Referenced by DegRateNuclide::neumann_bc(), MixedCellNuclide::neumann_bc(), LumpedNuclide::neumann_bc(), and OneDimPPMNuclide::neumann_bc().
virtual IsoFluxMap NuclideModel::cauchy_bc (IsoConcMap c_ext, Radius r_ext) pure virtual
returns the flux at the boundary, the Neumann bc
Returns:
qC the solute flux at the boundary in kg/m^2/s
Implemented in OneDimPPMNuclide, LumpedNuclide, MixedCellNuclide, StubNuclide, and DegRateNuclide.
Flux NuclideModel::cauchy_bc (IsoConcMap c_ext, Radius r_ext, Iso tope) inline
Definition at line 244 of file NuclideModel.h.
IsoConcMap NuclideModel::conc_hist (int the_time) inline
Returns the map of isotopes to concentrations at the time profided.
Parameters:
time the time at which to query the concentration history
Returns:
conc_hist_.at(time). If not found an empty IsoConcMap is return
Definition at line 314 of file NuclideModel.h.
References conc_hist_, last_updated(), and update().
Referenced by conc_hist(), LumpedNuclide::dirichlet_bc(), LumpedNuclide::neumann_bc(), and LumpedNuclide::source_term_bc().
Concentration NuclideModel::conc_hist (int the_time, Iso tope) inline
Returns the concetration of a certain isotope at a certain time.
Parameters:
time the time to query the concentration history
tope the isotope to query
Returns:
conc_hist(time)[iso].second, or zero if not found
Definition at line 336 of file NuclideModel.h.
References conc_hist().
double NuclideModel::contained_mass (int the_time) inline
returns the current contained contaminant mass, in kg, at time
Parameters:
time the time to query the contained contaminant mass
Returns:
contained_mass_ throughout the component volume, in kg, at time
Definition at line 266 of file NuclideModel.h.
IsoVector NuclideModel::contained_vec (int the_time) inline
The IsoVector representing the summed, normalized material in the component.
should put this in a toolkit or something. Doesn't belong here.
Parameters:
time the time at which to retrieve the IsoVector
Returns:
vec_hist(time).first
Definition at line 303 of file NuclideModel.h.
References vec_hist().
virtual NuclideModelPtr NuclideModel::copy (const NuclideModel & src) pure virtual
copies a component and its parameters from another
Parameters:
src is the component being copied
Implemented in OneDimPPMNuclide, LumpedNuclide, MixedCellNuclide, DegRateNuclide, and StubNuclide.
virtual IsoConcMap NuclideModel::dirichlet_bc () pure virtual
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
Parameters:
tope the isotope to query
Returns:
C the concentration at the boundary in kg/m^3
Implemented in OneDimPPMNuclide, LumpedNuclide, MixedCellNuclide, StubNuclide, and DegRateNuclide.
virtual Concentration NuclideModel::dirichlet_bc (Iso tope) inline virtual
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
Parameters:
tope the isotope to query
Returns:
C the concentration at the boundary in kg/m^3
Definition at line 182 of file NuclideModel.h.
virtual BCType NuclideModel::enumerateBCType (std::string type_name) inline virtual
spits out a number instead of a BCType
Definition at line 411 of file NuclideModel.h.
References LAST_BC_TYPE, name(), and type().
Referenced by DegRateNuclide::initModuleMembers(), and MixedCellNuclide::initModuleMembers().
virtual mat_rsrc_ptr NuclideModel::extract (CompMapPtr comp_to_rem, double kg_to_rem) pure virtual
Extracts the contents of the given composition from this NuclideModel.
Use this function for decrementing a NuclideModel's mass balance after transferring through a link.
Parameters:
comp_to_rem the composition to decrement against this NuclideModel
comp_to_rem the mass in kg to decrement against this NuclideModel
Returns:
the material extracted
Implemented in OneDimPPMNuclide, LumpedNuclide, MixedCellNuclide, DegRateNuclide, and StubNuclide.
const GeometryPtr NuclideModel::geom () const inline
Returns the geom_ data member.
Definition at line 258 of file NuclideModel.h.
References geom_.
Referenced by OneDimPPMNuclide::Co(), DegRateNuclide::copy(), MixedCellNuclide::copy(), LumpedNuclide::copy(), OneDimPPMNuclide::copy(), LumpedNuclide::extractIntegratedMass(), DegRateNuclide::inner_neumann(), MixedCellNuclide::inner_neumann(), MixedCellNuclide::neumann_bc(), LumpedNuclide::neumann_bc(), OneDimPPMNuclide::neumann_bc(), set_geom(), and OneDimPPMNuclide::update_inner_bc().
virtual void NuclideModel::initModuleMembers (QueryEngine * qe) pure virtual
initializes the model parameters from a Query Engine
Parameters:
qe is the QueryEngine object containing intialization info
Implemented in OneDimPPMNuclide, LumpedNuclide, MixedCellNuclide, DegRateNuclide, and StubNuclide.
int NuclideModel::last_updated () inline
returns the time at which the vec_hist and conc_hist were updated
Definition at line 389 of file NuclideModel.h.
References last_updated_.
Referenced by conc_hist(), LumpedNuclide::dirichlet_bc(), DegRateNuclide::extract(), MixedCellNuclide::extract(), LumpedNuclide::extract(), OneDimPPMNuclide::extract(), LumpedNuclide::neumann_bc(), LumpedNuclide::source_term_bc(), LumpedNuclide::update(), and vec_hist().
virtual std::string NuclideModel::name () pure virtual
returns the name of the NuclideModelType of the model
Implemented in OneDimPPMNuclide, LumpedNuclide, MixedCellNuclide, StubNuclide, and DegRateNuclide.
Referenced by enumerateBCType().
virtual ConcGradMap NuclideModel::neumann_bc (IsoConcMap c_ext, Radius r_ext) pure virtual
returns the concentration gradient at the boundary, the Neumann bc
Parameters:
c_ext the external concentration in the parent component
r_ext the radius in the parent component corresponding to c_ext
tope the isotope to query
Returns:
dCdx the concentration gradient at the boundary in kg/m^3
Implemented in OneDimPPMNuclide, LumpedNuclide, MixedCellNuclide, StubNuclide, and DegRateNuclide.
virtual ConcGrad NuclideModel::neumann_bc (IsoConcMap c_ext, Radius r_ext, Iso tope) inline virtual
returns the concentration gradient at the boundary, the Neumann bc
Parameters:
c_ext the external concentration in the parent component
r_ext the radius in the parent component corresponding to c_ext
tope the isotope to query
Returns:
dCdx the concentration gradient at the boundary in kg/m^3
Definition at line 232 of file NuclideModel.h.
virtual void NuclideModel::print () pure virtual
standard verbose printer explains the model
Implemented in OneDimPPMNuclide, LumpedNuclide, MixedCellNuclide, DegRateNuclide, and StubNuclide.
void NuclideModel::set_comp_id (int id) inline
Allows the component id data member to be set.
Definition at line 252 of file NuclideModel.h.
References comp_id_.
void NuclideModel::set_geom (GeometryPtr geom) inline
Allows the geometry object to be set.
Definition at line 255 of file NuclideModel.h.
References geom(), and geom_.
Referenced by DegRateNuclide::copy(), MixedCellNuclide::copy(), LumpedNuclide::copy(), OneDimPPMNuclide::copy(), DegRateNuclide::DegRateNuclide(), LumpedNuclide::LumpedNuclide(), MixedCellNuclide::MixedCellNuclide(), and OneDimPPMNuclide::OneDimPPMNuclide().
void NuclideModel::set_last_updated (int new_last_updated) inline
sets the last time that the vec_hist and conc_hist were updated, first verifying whether last_updated is larger than last_updated_
Parameters:
last_updated the time to set last_updated_ to.
Definition at line 396 of file NuclideModel.h.
References last_updated_.
Referenced by LumpedNuclide::copy(), OneDimPPMNuclide::copy(), MixedCellNuclide::update(), LumpedNuclide::update(), DegRateNuclide::update(), and OneDimPPMNuclide::update().
void NuclideModel::set_mat_table (MatDataTablePtr mat_table) inline
sends a pointer to the material table used by this component
Parameters:
mat_table the mat table data pointer for this component.
Definition at line 383 of file NuclideModel.h.
References mat_table_.
Referenced by OneDimPPMNuclideTest::SetUp(), DegRateNuclideTest::SetUp(), LumpedNuclideTest::SetUp(), and MixedCellNuclideTest::SetUp().
virtual std::pair<IsoVector, double> NuclideModel::source_term_bc () pure virtual
returns the available material source term at the outer boundary of the component in kg
Returns:
a pair, the available isovector and mass at the outer boundary
Implemented in OneDimPPMNuclide, LumpedNuclide, MixedCellNuclide, StubNuclide, and DegRateNuclide.
Referenced by source_term_bc().
virtual double NuclideModel::source_term_bc (Iso tope) inline virtual
returns the prescribed concentration at the boundary, the source term bc in kg
Parameters:
tope the isotope to query
Returns:
C the concentration at the boundary in kg/m^3
Definition at line 160 of file NuclideModel.h.
References source_term_bc().
virtual void NuclideModel::transportNuclides (int time) pure virtual
Transports nuclides from the inner boundary to the outer boundary in this component.
Parameters:
time the timestep at which the nuclides should be transported
Implemented in OneDimPPMNuclide, LumpedNuclide, MixedCellNuclide, DegRateNuclide, and StubNuclide.
virtual NuclideModelType NuclideModel::type () pure virtual
returns the NuclideModelType of the model
Implemented in OneDimPPMNuclide, LumpedNuclide, MixedCellNuclide, StubNuclide, and DegRateNuclide.
Referenced by enumerateBCType().
virtual void NuclideModel::update (int the_time) pure virtual
Update the hists at a certain time.
Parameters:
the_time the time at which to update the hists
Implemented in OneDimPPMNuclide, DegRateNuclide, LumpedNuclide, MixedCellNuclide, and StubNuclide.
Referenced by conc_hist(), and vec_hist().
virtual void NuclideModel::update_inner_bc (int the_time, std::vector< NuclideModelPtr > daughters) pure virtual
Determines what IsoVector to remove from the daughter nuclide models.
Parameters:
time the timestep at which the nuclides should be transported
daughter nuclide_model of an internal component. there may be many.
Implemented in LumpedNuclide, MixedCellNuclide, DegRateNuclide, OneDimPPMNuclide, and StubNuclide.
virtual void NuclideModel::updateNuclideParamsTable () pure virtual
All NuclideModels should implement a function that updates the Params table just once, to be called from the NuclideModelFactor right after initialization.
Implemented in OneDimPPMNuclide, LumpedNuclide, StubNuclide, MixedCellNuclide, and DegRateNuclide.
virtual double NuclideModel::V_ff () pure virtual
Implemented in MixedCellNuclide, OneDimPPMNuclide, DegRateNuclide, LumpedNuclide, and StubNuclide.
virtual double NuclideModel::V_T () pure virtual
Implemented in MixedCellNuclide, OneDimPPMNuclide, DegRateNuclide, LumpedNuclide, and StubNuclide.
std::pair<IsoVector, double> NuclideModel::vec_hist (int the_time) inline
Returns the IsoVector mass pair for a certain time.
Parameters:
time the time to query the isotopic history
Returns:
vec_hist_.at(time). If not found an empty pair is returned.
Definition at line 274 of file NuclideModel.h.
References last_updated(), update(), and vec_hist_.
Referenced by contained_vec().
std::deque<mat_rsrc_ptr> NuclideModel::wastes () inline
Returns wastes_.
Definition at line 386 of file NuclideModel.h.
References wastes_.
Member Data Documentation
int NuclideModel::comp_id_ protected
the id of the component that this nuclidemodel is a part of
Definition at line 455 of file NuclideModel.h.
Referenced by addRowToNuclideParamsTable(), and set_comp_id().
ConcHist NuclideModel::conc_hist_ protected
The map of times to isotopes to concentrations, in kg/m^3.
Definition at line 440 of file NuclideModel.h.
Referenced by conc_hist(), DegRateNuclide::copy(), MixedCellNuclide::copy(), LumpedNuclide::copy(), OneDimPPMNuclide::copy(), DegRateNuclide::DegRateNuclide(), LumpedNuclide::LumpedNuclide(), MixedCellNuclide::MixedCellNuclide(), and OneDimPPMNuclide::OneDimPPMNuclide().
GeometryPtr NuclideModel::geom_ protected
A shared pointer to the geometry of the component.
Definition at line 446 of file NuclideModel.h.
Referenced by DegRateNuclide::copy(), MixedCellNuclide::copy(), LumpedNuclide::copy(), OneDimPPMNuclide::copy(), geom(), DegRateNuclide::neumann_bc(), set_geom(), MixedCellNuclide::source_term_bc(), StubNuclide::V_ff(), DegRateNuclide::V_ff(), StubNuclide::V_T(), LumpedNuclide::V_T(), DegRateNuclide::V_T(), OneDimPPMNuclide::V_T(), and MixedCellNuclide::V_T().
int NuclideModel::last_updated_ protected
the time at which the histories were last updated
Definition at line 452 of file NuclideModel.h.
Referenced by DegRateNuclide::DegRateNuclide(), last_updated(), LumpedNuclide::LumpedNuclide(), MixedCellNuclide::MixedCellNuclide(), OneDimPPMNuclide::OneDimPPMNuclide(), and set_last_updated().
MatDataTablePtr NuclideModel::mat_table_ protected
A shared pointer to this Component's material data table.
Definition at line 449 of file NuclideModel.h.
Referenced by OneDimPPMNuclide::calculate_conc_diff(), DegRateNuclide::cauchy_bc(), MixedCellNuclide::cauchy_bc(), LumpedNuclide::cauchy_bc(), OneDimPPMNuclide::cauchy_bc(), DegRateNuclide::inner_neumann(), MixedCellNuclide::inner_neumann(), MixedCellNuclide::precipitate(), set_mat_table(), MixedCellNuclide::sorb(), DegRateNuclide::updateNuclideParamsTable(), MixedCellNuclide::updateNuclideParamsTable(), LumpedNuclide::updateNuclideParamsTable(), and OneDimPPMNuclide::updateNuclideParamsTable().
VecHist NuclideModel::vec_hist_ protected
The map of times to IsoVectors.
Definition at line 443 of file NuclideModel.h.
Referenced by DegRateNuclide::copy(), MixedCellNuclide::copy(), LumpedNuclide::copy(), OneDimPPMNuclide::copy(), DegRateNuclide::DegRateNuclide(), LumpedNuclide::LumpedNuclide(), MixedCellNuclide::MixedCellNuclide(), OneDimPPMNuclide::OneDimPPMNuclide(), OneDimPPMNuclide::update_vec_hist(), DegRateNuclide::update_vec_hist(), MixedCellNuclide::update_vec_hist(), LumpedNuclide::update_vec_hist(), and vec_hist().
std::deque<mat_rsrc_ptr> NuclideModel::wastes_ protected
A vector of the wastes contained by this component wastes(){return component_->wastes();};.
Definition at line 437 of file NuclideModel.h.
Referenced by DegRateNuclide::absorb(), MixedCellNuclide::absorb(), LumpedNuclide::absorb(), OneDimPPMNuclide::absorb(), OneDimPPMNuclide::Ci(), DegRateNuclide::copy(), MixedCellNuclide::copy(), LumpedNuclide::copy(), OneDimPPMNuclide::copy(), DegRateNuclide::DegRateNuclide(), DegRateNuclide::extract(), MixedCellNuclide::extract(), LumpedNuclide::extract(), OneDimPPMNuclide::extract(), MixedCellNuclide::MixedCellNuclide(), OneDimPPMNuclide::OneDimPPMNuclide(), DegRateNuclide::source_term_bc(), MixedCellNuclide::source_term_bc(), OneDimPPMNuclide::source_term_bc(), OneDimPPMNuclide::update(), DegRateNuclide::update_conc_hist(), MixedCellNuclide::update_conc_hist(), OneDimPPMNuclide::update_conc_hist(), LumpedNuclide::update_conc_hist(), OneDimPPMNuclide::update_inner_bc(), OneDimPPMNuclide::update_vec_hist(), DegRateNuclide::update_vec_hist(), MixedCellNuclide::update_vec_hist(), LumpedNuclide::update_vec_hist(), and wastes().
The documentation for this class was generated from the following file:
NuclideModel.h