cyder: DegRateNuclide Class Reference
DegRateNuclide Class Reference
DegRateNuclide is a nuclide model that releases material congruently with degradation of the engineered barrier material.
#include <DegRateNuclide.h>
Public Member Functions
virtual void absorb (mat_rsrc_ptr matToAdd)
Absorbs the contents of the given Material into this DegRateNuclide.
const BCType bc_type () const
Sets the boundary condition type used on the inner boundary.
virtual IsoFluxMap cauchy_bc (IsoConcMap c_ext, Radius r_ext)
returns the flux at the boundary, the Neumann bc
double contained_mass ()
returns the current contained contaminant mass, in kg should put this in the NuclideModel class or something.
virtual NuclideModelPtr copy (const NuclideModel &src)
copies a nuclide model and its parameters from another
const double deg_rate () const
returns the degradation rate that characterizes this model
virtual IsoConcMap dirichlet_bc ()
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
virtual mat_rsrc_ptr extract (CompMapPtr comp_to_rem, double kg_to_rem)
Extracts the contents of the given Material from this DegRateNuclide.
virtual void initModuleMembers (QueryEngine *qe)
initializes the model parameters from a QueryEngine object
std::pair< CompMapPtr, double > inner_cauchy (NuclideModelPtr daughter)
Determines what to remove from a daughter nuclide, relying on cauchy bc.
std::pair< CompMapPtr, double > inner_dirichlet (NuclideModelPtr daughter)
Determines what to remove from a daughter nuclide, relying on dirichlet bc.
std::pair< CompMapPtr, double > inner_neumann (NuclideModelPtr daughter)
Determines what to remove from a daughter nuclide, relying on neumann bc.
const int last_degraded () const
Returns the last timestamp at which this component was last degraded [integer timestamp].
virtual std::string name ()
Returns the nuclide model type name.
virtual ConcGradMap neumann_bc (IsoConcMap c_ext, Radius r_ext)
returns the concentration gradient at the boundary, the Neumann bc
virtual void print ()
standard verbose printer includes current temp and concentrations
void set_bc_type (BCType bc_type)
Sets the boundary condition type used on the inner boundary.
void set_deg_rate (double cur_rate)
returns the degradation rate that characterizes this model
void set_last_degraded (const int last_degraded)
Set the last_degraded_ time [integer timestamp].
void set_tot_deg (const double tot_deg)
sets the total degradation of the component
void set_v (const double v)
Set the advective velocity v_ through this component.
virtual std::pair< IsoVector,
double > source_term_bc ()
returns the available material source term at the outer boundary of the component
const double tot_deg () const
returns the total degradation of the component
virtual void transportNuclides (int time)
Transports nuclides from the inner to the outer boundary.
virtual NuclideModelType type ()
Returns the nuclide model type.
virtual void update (int the_time)
updates all the hists at the time
IsoConcMap update_conc_hist (int time)
updates the contained concentration according to contained wastes_
IsoConcMap update_conc_hist (int time, std::deque< mat_rsrc_ptr > mats)
updates the contained concentration with mats provided
double update_degradation (int time, double cur_rate)
updates the total degradation and makes time the last degraded time.
void update_inner_bc (int the_time, std::vector< NuclideModelPtr > daughters)
Determines what IsoVector to remove from the daughter nuclide models.
void update_vec_hist (int time)
Updates the isotopic vector history at the time.
void update_vec_hist (int time, std::deque< mat_rsrc_ptr > mats)
Updates the isotopic vector history at the time.
virtual void updateNuclideParamsTable ()
Updates the NuclideParams table by adding appropriate rows to describe the parameters initializing this NuclideModel.
const double v () const
The advective velocity through this component.
virtual double V_ff ()
Returns the last timestamp at which this component was last degraded [integer timestamp].
virtual double V_T ()
virtual ~DegRateNuclide ()
Virtual destructor deletes datamembers that are object pointers.
Public Member Functions inherited from NuclideModel
virtual void addRowToNuclideParamsTable (std::string param_name, boost::any param_val)
adds a row to the NuclideModelParams table.
ConcGrad calc_conc_grad (Concentration c_ext, Concentration c_int, Radius r_ext, Radius r_int)
Returns the concentration gradient based on a simple finite difference between two datapoints.
Flux cauchy_bc (IsoConcMap c_ext, Radius r_ext, Iso tope)
IsoConcMap conc_hist (int the_time)
Returns the map of isotopes to concentrations at the time profided.
Concentration conc_hist (int the_time, Iso tope)
Returns the concetration of a certain isotope at a certain time.
double contained_mass (int the_time)
returns the current contained contaminant mass, in kg, at time
IsoVector contained_vec (int the_time)
The IsoVector representing the summed, normalized material in the component.
virtual Concentration dirichlet_bc (Iso tope)
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
virtual BCType enumerateBCType (std::string type_name)
spits out a number instead of a BCType
const GeometryPtr geom () const
Returns the geom_ data member.
int last_updated ()
returns the time at which the vec_hist and conc_hist were updated
virtual ConcGrad neumann_bc (IsoConcMap c_ext, Radius r_ext, Iso tope)
returns the concentration gradient at the boundary, the Neumann bc
void set_comp_id (int id)
Allows the component id data member to be set.
void set_geom (GeometryPtr geom)
Allows the geometry object to be set.
void set_last_updated (int new_last_updated)
sets the last time that the vec_hist and conc_hist were updated, first verifying whether last_updated is larger than last_updated_
void set_mat_table (MatDataTablePtr mat_table)
sends a pointer to the material table used by this component
virtual double source_term_bc (Iso tope)
returns the prescribed concentration at the boundary, the source term bc in kg
std::pair< IsoVector, double > vec_hist (int the_time)
Returns the IsoVector mass pair for a certain time.
std::deque< mat_rsrc_ptr > wastes ()
Returns wastes_.
virtual ~NuclideModel ()
A virtual destructor.
Static Public Member Functions
static DegRateNuclidePtr create ()
A constructor for the DegRate Nuclide Model that returns a shared pointer.
static DegRateNuclidePtr create (QueryEngine *qe)
A constructor for the DegRate Nuclide Model that returns a shared pointer.
Protected Attributes
BCType bc_type_
The type of boundary condition with which to treat the inner boundary.
double deg_rate_
The degradation rate that defines this model, fraction per year.
int last_degraded_
the last timestamp at which this component was last degraded [integer timestamp]
double tot_deg_
the total fraction that this component has degraded
double v_
The advective velocity through this component [m/s].
Protected Attributes inherited from NuclideModel
int comp_id_
the id of the component that this nuclidemodel is a part of
ConcHist conc_hist_
The map of times to isotopes to concentrations, in kg/m^3.
GeometryPtr geom_
A shared pointer to the geometry of the component.
int last_updated_
the time at which the histories were last updated
MatDataTablePtr mat_table_
A shared pointer to this Component's material data table.
VecHist vec_hist_
The map of times to IsoVectors.
std::deque< mat_rsrc_ptr > wastes_
A vector of the wastes contained by this component wastes(){return component_->wastes();};.
Private Member Functions
DegRateNuclide ()
Default constructor for the nuclide model class.
DegRateNuclide (QueryEngine *qe)
primary constructor reads input from the QueryEngine
Detailed Description
DegRateNuclide is a nuclide model that releases material congruently with degradation of the engineered barrier material.
This disposal system nuclide model will release any contained contaminants at a rate corresponding solely to its degradation rate. That is, if the component degrades at a rate of 15% per year, then 15% of the contaminant will be made available at the boundaries. This NuclideModel will follow J. Ahn's congruent release model.
The DegRateNuclide model can be used to represent nuclide models of the disposal system such as the Waste Form, Waste Package, Buffer, and Near Field. However, since the Far Field and the Envrionment do not degrade, these are not well represented by the DegRateNuclide model.
Definition at line 36 of file DegRateNuclide.h.
Constructor & Destructor Documentation
DegRateNuclide::DegRateNuclide () private
Default constructor for the nuclide model class.
Creates an empty nuclide model.
Definition at line 22 of file DegRateNuclide.cpp.
References NuclideModel::conc_hist_, NuclideModel::last_updated_, NuclideModel::set_geom(), NuclideModel::vec_hist_, and NuclideModel::wastes_.
Referenced by create().
DegRateNuclide::DegRateNuclide (QueryEngine * qe) private
primary constructor reads input from the QueryEngine
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 39 of file DegRateNuclide.cpp.
References NuclideModel::conc_hist_, initModuleMembers(), NuclideModel::last_updated_, NuclideModel::set_geom(), NuclideModel::vec_hist_, and NuclideModel::wastes_.
DegRateNuclide::~DegRateNuclide () virtual
Virtual destructor deletes datamembers that are object pointers.
Definition at line 57 of file DegRateNuclide.cpp.
Member Function Documentation
void DegRateNuclide::absorb (mat_rsrc_ptr matToAdd) virtual
Absorbs the contents of the given Material into this DegRateNuclide.
Parameters:
matToAdd the DegRateNuclide to be absorbed
Implements NuclideModel.
Definition at line 123 of file DegRateNuclide.cpp.
References NuclideModel::wastes_.
Referenced by update_inner_bc().
const BCType DegRateNuclide::bc_type () const inline
Sets the boundary condition type used on the inner boundary.
Definition at line 304 of file DegRateNuclide.h.
References bc_type_.
Referenced by copy(), and set_bc_type().
IsoFluxMap DegRateNuclide::cauchy_bc (IsoConcMap c_ext, Radius r_ext) virtual
returns the flux at the boundary, the Neumann bc
Returns:
qC the solute flux at the boundary in kg/m^2/s
Implements NuclideModel.
Definition at line 223 of file DegRateNuclide.cpp.
References NuclideModel::mat_table_, neumann_bc(), and v().
double DegRateNuclide::contained_mass ()
returns the current contained contaminant mass, in kg should put this in the NuclideModel class or something.
Returns:
contained_mass_[now] throughout the component volume, in kg
Definition at line 171 of file DegRateNuclide.cpp.
References last_degraded().
NuclideModelPtr DegRateNuclide::copy (const NuclideModel & src) virtual
copies a nuclide model and its parameters from another
Parameters:
src is the nuclide model being copied
Implements NuclideModel.
Definition at line 81 of file DegRateNuclide.cpp.
References bc_type(), NuclideModel::conc_hist_, deg_rate(), NuclideModel::geom(), NuclideModel::geom_, set_bc_type(), set_deg_rate(), NuclideModel::set_geom(), set_last_degraded(), set_tot_deg(), set_v(), v(), NuclideModel::vec_hist_, and NuclideModel::wastes_.
static DegRateNuclidePtr DegRateNuclide::create () inline static
A constructor for the DegRate Nuclide Model that returns a shared pointer.
Definition at line 59 of file DegRateNuclide.h.
References DegRateNuclide().
Referenced by DegRateNuclideModelConstructor(), DegRateNuclideTest::initNuclideModel(), NuclideModelFactory::nuclideModel(), ComponentTest::SetUp(), DegRateNuclideTest::SetUp(), and TEST_F().
static DegRateNuclidePtr DegRateNuclide::create (QueryEngine * qe) inline static
A constructor for the DegRate Nuclide Model that returns a shared pointer.
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 66 of file DegRateNuclide.h.
References DegRateNuclide().
const double DegRateNuclide::deg_rate () const inline
returns the degradation rate that characterizes this model
Returns:
deg_rate_ fraction per year
Definition at line 181 of file DegRateNuclide.h.
References deg_rate_.
Referenced by copy(), transportNuclides(), update_degradation(), and updateNuclideParamsTable().
IsoConcMap DegRateNuclide::dirichlet_bc () virtual
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
Returns:
C the concentration at the boundary in kg/m^3 for each isotope
Implements NuclideModel.
Definition at line 183 of file DegRateNuclide.cpp.
References MatTools::comp_to_conc_map(), and V_ff().
Referenced by inner_neumann(), and neumann_bc().
mat_rsrc_ptr DegRateNuclide::extract (CompMapPtr comp_to_rem, double kg_to_rem) virtual
Extracts the contents of the given Material from this DegRateNuclide.
Use this function for decrementing a DegRateNuclide's mass balance after transferring through a link.
Parameters:
comp_to_rem the composition to decrement against this DegRateNuclide
kg_to_rem the amount in kg to decrement against this DegRateNuclide
Returns:
the material extracted
Implements NuclideModel.
Definition at line 134 of file DegRateNuclide.cpp.
References MatTools::extract(), NuclideModel::last_updated(), update(), and NuclideModel::wastes_.
void DegRateNuclide::initModuleMembers (QueryEngine * qe) virtual
initializes the model parameters from a QueryEngine object
Parameters:
qe is the QueryEngine object containing intialization info
Implements NuclideModel.
Definition at line 61 of file DegRateNuclide.cpp.
References NuclideModel::enumerateBCType(), set_bc_type(), set_deg_rate(), and set_v().
Referenced by DegRateNuclide().
pair< CompMapPtr, double > DegRateNuclide::inner_cauchy (NuclideModelPtr daughter)
Determines what to remove from a daughter nuclide, relying on cauchy bc.
Parameters:
daughter nuclide_model of an internal component.
Definition at line 374 of file DegRateNuclide.cpp.
References inner_dirichlet(), and inner_neumann().
Referenced by update_inner_bc().
pair< CompMapPtr, double > DegRateNuclide::inner_dirichlet (NuclideModelPtr daughter)
Determines what to remove from a daughter nuclide, relying on dirichlet bc.
Parameters:
daughter nuclide_model of an internal component.
Definition at line 356 of file DegRateNuclide.cpp.
References MatTools::conc_to_comp_map(), MatTools::scaleConcMap(), SECSPERMONTH, and v().
Referenced by inner_cauchy(), and update_inner_bc().
pair< CompMapPtr, double > DegRateNuclide::inner_neumann (NuclideModelPtr daughter)
Determines what to remove from a daughter nuclide, relying on neumann bc.
Parameters:
daughter nuclide_model of an internal component.
Definition at line 334 of file DegRateNuclide.cpp.
References MatTools::conc_to_comp_map(), dirichlet_bc(), NuclideModel::geom(), NuclideModel::mat_table_, MatTools::scaleConcMap(), SECSPERMONTH, and tot_deg().
Referenced by inner_cauchy(), and update_inner_bc().
const int DegRateNuclide::last_degraded () const inline
Returns the last timestamp at which this component was last degraded [integer timestamp].
Definition at line 295 of file DegRateNuclide.h.
References last_degraded_.
Referenced by contained_mass(), set_last_degraded(), and update_degradation().
virtual std::string DegRateNuclide::name () inline virtual
Returns the nuclide model type name.
Implements NuclideModel.
Definition at line 126 of file DegRateNuclide.h.
ConcGradMap DegRateNuclide::neumann_bc (IsoConcMap c_ext, Radius r_ext) virtual
returns the concentration gradient at the boundary, the Neumann bc
Returns:
dCdx the concentration gradient at the boundary in kg/m^3
Implements NuclideModel.
Definition at line 191 of file DegRateNuclide.cpp.
References NuclideModel::calc_conc_grad(), dirichlet_bc(), and NuclideModel::geom_.
Referenced by cauchy_bc().
void DegRateNuclide::print () virtual
standard verbose printer includes current temp and concentrations
Implements NuclideModel.
Definition at line 118 of file DegRateNuclide.cpp.
void DegRateNuclide::set_bc_type (BCType bc_type) inline
Sets the boundary condition type used on the inner boundary.
Definition at line 307 of file DegRateNuclide.h.
References bc_type(), and bc_type_.
Referenced by copy(), and initModuleMembers().
void DegRateNuclide::set_deg_rate (double cur_rate)
returns the degradation rate that characterizes this model
Parameters:
cur_rate the current degradation rate, a fraction per timestep, between 0 and 1
Exceptions:
CycRangeException if deg_rate not between 0 and 1 inclusive
Definition at line 155 of file DegRateNuclide.cpp.
References deg_rate_.
Referenced by copy(), initModuleMembers(), and update_degradation().
void DegRateNuclide::set_last_degraded (const int last_degraded) inline
Set the last_degraded_ time [integer timestamp].
Definition at line 290 of file DegRateNuclide.h.
References last_degraded(), and last_degraded_.
Referenced by copy(), and update_degradation().
void DegRateNuclide::set_tot_deg (const double tot_deg) inline
sets the total degradation of the component
Definition at line 275 of file DegRateNuclide.h.
References tot_deg(), and tot_deg_.
Referenced by copy(), and update_degradation().
void DegRateNuclide::set_v (const double v) inline
Set the advective velocity v_ through this component.
[m/s]
Definition at line 280 of file DegRateNuclide.h.
References v(), and v_.
Referenced by copy(), and initModuleMembers().
pair< IsoVector, double > DegRateNuclide::source_term_bc () virtual
returns the available material source term at the outer boundary of the component
Returns:
m_ij the available source term outer boundary condition
Implements NuclideModel.
Definition at line 176 of file DegRateNuclide.cpp.
References MatTools::sum_mats(), tot_deg(), and NuclideModel::wastes_.
const double DegRateNuclide::tot_deg () const inline
returns the total degradation of the component
Definition at line 272 of file DegRateNuclide.h.
References tot_deg_.
Referenced by inner_neumann(), set_tot_deg(), source_term_bc(), update_degradation(), and V_ff().
void DegRateNuclide::transportNuclides (int time) virtual
Transports nuclides from the inner to the outer boundary.
Parameters:
time the timestep at which to transport the nuclides
Implements NuclideModel.
Definition at line 147 of file DegRateNuclide.cpp.
References deg_rate(), update(), and update_degradation().
virtual NuclideModelType DegRateNuclide::type () inline virtual
Returns the nuclide model type.
Implements NuclideModel.
Definition at line 121 of file DegRateNuclide.h.
References DEGRATE_NUCLIDE.
void DegRateNuclide::update (int the_time) virtual
updates all the hists at the time
Parameters:
the_time at which to update everything
Implements NuclideModel.
Definition at line 111 of file DegRateNuclide.cpp.
References NuclideModel::set_last_updated(), update_conc_hist(), and update_vec_hist().
Referenced by extract(), and transportNuclides().
IsoConcMap DegRateNuclide::update_conc_hist (int time)
updates the contained concentration according to contained wastes_
Parameters:
time the time at which to update the degradation
Returns:
the current isotopic concentration map at the outer border
Definition at line 239 of file DegRateNuclide.cpp.
References NuclideModel::wastes_.
Referenced by update().
IsoConcMap DegRateNuclide::update_conc_hist (int time, std::deque< mat_rsrc_ptr > mats)
updates the contained concentration with mats provided
Parameters:
time the time at which to update the degradation
mats the vector of materials contained in the component
Returns:
the current isotopic concentration map at the outer border
double DegRateNuclide::update_degradation (int time, double cur_rate)
updates the total degradation and makes time the last degraded time.
Parameters:
time the time at which to update the degradation
cur_rate is the degradation rate since the last degradation, fraction.
Definition at line 272 of file DegRateNuclide.cpp.
References deg_rate(), last_degraded(), set_deg_rate(), set_last_degraded(), set_tot_deg(), tot_deg(), and tot_deg_.
Referenced by transportNuclides().
void DegRateNuclide::update_inner_bc (int the_time, std::vector< NuclideModelPtr > daughters) virtual
Determines what IsoVector to remove from the daughter nuclide models.
Parameters:
time the timestep at which the nuclides should be transported
daughter nuclide_model of an internal component. there may be many.
Implements NuclideModel.
Definition at line 293 of file DegRateNuclide.cpp.
References absorb(), bc_type_, CAUCHY, DIRICHLET, inner_cauchy(), inner_dirichlet(), inner_neumann(), NEUMANN, and SOURCE_TERM.
void DegRateNuclide::update_vec_hist (int time)
Updates the isotopic vector history at the time.
Parameters:
time the time at which to update the vector history, according to wastes_ last_degraded_ time.
Definition at line 288 of file DegRateNuclide.cpp.
References MatTools::sum_mats(), NuclideModel::vec_hist_, and NuclideModel::wastes_.
Referenced by update().
void DegRateNuclide::update_vec_hist (int time, std::deque< mat_rsrc_ptr > mats)
Updates the isotopic vector history at the time.
Parameters:
time the time at which to update the vector history
mats the deque of materials to include in the history, usually wastes_
Exceptions:
an exception if the time provided is less than the last_degraded_ time.
void DegRateNuclide::updateNuclideParamsTable () virtual
Updates the NuclideParams table by adding appropriate rows to describe the parameters initializing this NuclideModel.
Implements NuclideModel.
Definition at line 102 of file DegRateNuclide.cpp.
References deg_rate(), NuclideModel::mat_table_, and v().
const double DegRateNuclide::v () const inline
The advective velocity through this component.
[m/s]
Definition at line 285 of file DegRateNuclide.h.
References v_.
Referenced by cauchy_bc(), copy(), inner_dirichlet(), set_v(), and updateNuclideParamsTable().
virtual double DegRateNuclide::V_ff () inline virtual
Returns the last timestamp at which this component was last degraded [integer timestamp].
Implements NuclideModel.
Definition at line 300 of file DegRateNuclide.h.
References NuclideModel::geom_, and tot_deg().
Referenced by dirichlet_bc().
virtual double DegRateNuclide::V_T () inline virtual
Implements NuclideModel.
Definition at line 301 of file DegRateNuclide.h.
References NuclideModel::geom_.
Member Data Documentation
BCType DegRateNuclide::bc_type_ protected
The type of boundary condition with which to treat the inner boundary.
Definition at line 328 of file DegRateNuclide.h.
Referenced by bc_type(), set_bc_type(), and update_inner_bc().
double DegRateNuclide::deg_rate_ protected
The degradation rate that defines this model, fraction per year.
Definition at line 319 of file DegRateNuclide.h.
Referenced by deg_rate(), and set_deg_rate().
int DegRateNuclide::last_degraded_ protected
the last timestamp at which this component was last degraded [integer timestamp]
Definition at line 325 of file DegRateNuclide.h.
Referenced by last_degraded(), and set_last_degraded().
double DegRateNuclide::tot_deg_ protected
the total fraction that this component has degraded
Definition at line 322 of file DegRateNuclide.h.
Referenced by set_tot_deg(), tot_deg(), and update_degradation().
double DegRateNuclide::v_ protected
The advective velocity through this component [m/s].
Definition at line 314 of file DegRateNuclide.h.
Referenced by set_v(), and v().
The documentation for this class was generated from the following files:
DegRateNuclide.h
DegRateNuclide.cpp