cyder: MaterialDB Class Reference
MaterialDB Class Reference
The MaterialDB class provides an interface to the mat_data.sqlite database, providing a robust and correct mass lookup by isotope.
#include <MaterialDB.h>
Public Member Functions
void clearTables ()
int curr_table_id ()
double D (std::string mat, Elem ent)
get the dispersion coefficient [kg/m^2/s] for some element in some material of interest
double data (std::string mat, Elem ent, std::string data)
get a piece of data for some element in some material of interest
std::map< Elem, double > data (std::string mat, std::string data)
get a piece of data for some element in some material of interest
bool initialized (std::string mat)
checks whether a table associated with a particular mat has been created
MatDataTablePtr initializeFromSQL (std::string mat, double ref_disp=NULL, double ref_kd=NULL, double ref_sol=NULL)
a function to initialize a large array of element_t structs via the SQLite/C++ API
double K_d (std::string mat, Elem ent)
get the distribution coefficient [kg/kg] for some element in some material of interest
MaterialDB ()
Default constructor for the MaterialDB class.
int ref_ind (double ref, ChemDataType data)
double S (std::string mat, Elem ent)
get the solubility limit for some element in some material of interest
MatDataTablePtr table (std::string mat, double ref_disp=NULL, double ref_kd=NULL, double ref_sol=NULL)
returns the table matching the mat string.
std::string tableID (std::string mat, double ref_disp=NULL, double ref_kd=NULL, double ref_sol=NULL)
~MaterialDB ()
Destructor for the NullFacility class.
Static Public Member Functions
static MaterialDB * Instance ()
Provides a singleton instance for the MaterialDB.
Public Attributes
std::map< std::string,
MatDataTablePtr > tables_
a map from the names of materials to table pointers
Protected Attributes
std::map< double, int > disp_ind_map_
std::map< double, int > kd_ind_map_
std::map< double, int > sol_ind_map_
std::map< int, std::map< int,
std::map< int, int > > > table_id_array_
Private Attributes
std::string file_path_
this database's file path
Static Private Attributes
static MaterialDB * instance_ = 0
A pointer to this MaterialDB once it has been initialized.
static int table_id_ = 0
the current table id
Detailed Description
The MaterialDB class provides an interface to the mat_data.sqlite database, providing a robust and correct mass lookup by isotope.
Definition at line 22 of file MaterialDB.h.
Constructor & Destructor Documentation
MaterialDB::MaterialDB ()
Default constructor for the MaterialDB class.
Initializes the data from the provided mat_data.sqlite file.
Definition at line 29 of file MaterialDB.cpp.
References disp_ind_map_, kd_ind_map_, sol_ind_map_, and table_id_array_.
MaterialDB::~MaterialDB ()
Destructor for the NullFacility class.
Makes certain to delete all appropriate data on the stack.
Definition at line 38 of file MaterialDB.cpp.
References instance_.
Member Function Documentation
void MaterialDB::clearTables ()
Definition at line 169 of file MaterialDB.cpp.
References disp_ind_map_, kd_ind_map_, sol_ind_map_, table_id_array_, and tables_.
int MaterialDB::curr_table_id () inline
Definition at line 149 of file MaterialDB.h.
References table_id_.
double MaterialDB::D (std::string mat, Elem ent)
get the dispersion coefficient [kg/m^2/s] for some element in some material of interest
Parameters:
mat the name of the material table in the database
ent an identifier of type Elem, which is an int
Returns:
D a double, the dispersion coefficient [kg/m^2/s] for the element ent in the material mat.
Definition at line 53 of file MaterialDB.cpp.
References table().
double MaterialDB::data (std::string mat, Elem ent, std::string data)
get a piece of data for some element in some material of interest
Parameters:
mat the name of the material table in the database
ent an identifier of type Elem, which is an int
data the name of the column in the materialDB table
Returns:
a double, the data sought for the element ent in the material mat.
Referenced by ref_ind().
std::map<Elem, double> MaterialDB::data (std::string mat, std::string data)
get a piece of data for some element in some material of interest
Parameters:
mat the name of the material table in the database
data the name of the column in the materialDB table
Returns:
a double, the data sought for the element ent in the material mat.
bool MaterialDB::initialized (std::string mat)
checks whether a table associated with a particular mat has been created
Parameters:
mat the string name of the table to check the existence of
Definition at line 127 of file MaterialDB.cpp.
References tables_.
Referenced by table().
MatDataTablePtr MaterialDB::initializeFromSQL (std::string mat, double ref_disp = NULL, double ref_kd = NULL, double ref_sol = NULL)
a function to initialize a large array of element_t structs via the SQLite/C++ API
Parameters:
mat the string indicatin the material this table should represent
Definition at line 134 of file MaterialDB.cpp.
References file_path_.
Referenced by table().
MaterialDB * MaterialDB::Instance () static
Provides a singleton instance for the MaterialDB.
Like the Highlander, there should be only one.
Returns:
a pointer to the MaterialDB
Definition at line 19 of file MaterialDB.cpp.
double MaterialDB::K_d (std::string mat, Elem ent)
get the distribution coefficient [kg/kg] for some element in some material of interest
Parameters:
mat the name of the material table in the database
ent an identifier of type Elem, which is an int
Returns:
K_d a double, the distribution coefficient [kg/kg] for the element ent in the material mat.
Definition at line 43 of file MaterialDB.cpp.
References table().
int MaterialDB::ref_ind (double ref, ChemDataType data)
Definition at line 96 of file MaterialDB.cpp.
References data(), DISP, disp_ind_map_, KD, kd_ind_map_, SOL, and sol_ind_map_.
Referenced by tableID().
double MaterialDB::S (std::string mat, Elem ent)
get the solubility limit for some element in some material of interest
Parameters:
mat the name of the material table in the database
ent an identifier of type Elem, which is an int
Returns:
S a double, the solubility limit [kg/m^3] for the element ent in the material mat.
Definition at line 48 of file MaterialDB.cpp.
References table().
MatDataTablePtr MaterialDB::table (std::string mat, double ref_disp = NULL, double ref_kd = NULL, double ref_sol = NULL)
returns the table matching the mat string.
Parameters:
mat a string indicating the name of the table (clay, salt, etc.)
Returns:
a MatDataTablePtr holding the data associated with the mat
Definition at line 58 of file MaterialDB.cpp.
References initialized(), initializeFromSQL(), tableID(), and tables_.
Referenced by D(), K_d(), and S().
string MaterialDB::tableID (std::string mat, double ref_disp = NULL, double ref_kd = NULL, double ref_sol = NULL)
Definition at line 73 of file MaterialDB.cpp.
References DISP, KD, ref_ind(), SOL, table_id_, and table_id_array_.
Referenced by table().
Member Data Documentation
std::map<double, int> MaterialDB::disp_ind_map_ protected
Definition at line 156 of file MaterialDB.h.
Referenced by clearTables(), MaterialDB(), and ref_ind().
std::string MaterialDB::file_path_ private
this database's file path
Definition at line 32 of file MaterialDB.h.
Referenced by initializeFromSQL().
MaterialDB * MaterialDB::instance_ = 0 static private
A pointer to this MaterialDB once it has been initialized.
Definition at line 27 of file MaterialDB.h.
Referenced by ~MaterialDB().
std::map<double, int> MaterialDB::kd_ind_map_ protected
Definition at line 157 of file MaterialDB.h.
Referenced by clearTables(), MaterialDB(), and ref_ind().
std::map<double, int> MaterialDB::sol_ind_map_ protected
Definition at line 158 of file MaterialDB.h.
Referenced by clearTables(), MaterialDB(), and ref_ind().
int MaterialDB::table_id_ = 0 static private
the current table id
Definition at line 35 of file MaterialDB.h.
Referenced by curr_table_id(), and tableID().
std::map<int, std::map<int, std::map<int,int> > > MaterialDB::table_id_array_ protected
Definition at line 154 of file MaterialDB.h.
Referenced by clearTables(), MaterialDB(), and tableID().
std::map<std::string, MatDataTablePtr> MaterialDB::tables_
a map from the names of materials to table pointers
Definition at line 95 of file MaterialDB.h.
Referenced by clearTables(), initialized(), and table().
The documentation for this class was generated from the following files:
MaterialDB.h
MaterialDB.cpp