cyder: NuclideModelFactory Class Reference
NuclideModelFactory Class Reference
A class which selects and produces concrete instances of NuclideModels.
#include <NuclideModelFactory.h>
Static Public Member Functions
static NuclideModelPtr nuclideModel (QueryEngine *qe)
Creates a concrete NuclideModel from a QueryEngine pointer.
static NuclideModelPtr nuclideModel (QueryEngine *qe, MatDataTablePtr mat_table, GeometryPtr geom, int comp_id)
Creates a concrete NuclideModel from a QueryEngine pointer as well as geometry and material data.
static NuclideModelPtr nuclideModel (NuclideModelPtr src, MatDataTablePtr mat_table, GeometryPtr geom, int comp_id)
Creates a copy of a NuclideModel from another NuclideModel as well as geometry and material data.
Static Protected Member Functions
static NuclideModelType nuclideEnum (std::string type_name)
Enumerates a string if it is one of the named NuclideModelTypes.
Static Protected Attributes
static std::string nuclide_type_names_ [LAST_NUCLIDE]
NuclideModelType names list.
Detailed Description
A class which selects and produces concrete instances of NuclideModels.
Definition at line 19 of file NuclideModelFactory.h.
Member Function Documentation
NuclideModelType NuclideModelFactory::nuclideEnum (std::string type_name) static protected
Enumerates a string if it is one of the named NuclideModelTypes.
Parameters:
type the name of the NuclideModelType (e.g., StubNuclide)
Definition at line 106 of file NuclideModelFactory.cpp.
References LAST_NUCLIDE, and nuclide_type_names_.
Referenced by nuclideModel().
NuclideModelPtr NuclideModelFactory::nuclideModel (QueryEngine * qe) static
Creates a concrete NuclideModel from a QueryEngine pointer.
This will have and uninitialized geometry and material table?
Parameters:
qe query engine pointer describing the nuclide model
Definition at line 31 of file NuclideModelFactory.cpp.
References StubNuclide::create(), DegRateNuclide::create(), MixedCellNuclide::create(), LumpedNuclide::create(), OneDimPPMNuclide::create(), DEGRATE_NUCLIDE, LUMPED_NUCLIDE, MIXEDCELL_NUCLIDE, nuclideEnum(), ONEDIMPPM_NUCLIDE, and STUB_NUCLIDE.
Referenced by Component::copyNuclideModel(), Component::nuclide_model(), and nuclideModel().
NuclideModelPtr NuclideModelFactory::nuclideModel (QueryEngine * qe, MatDataTablePtr mat_table, GeometryPtr geom, int comp_id) static
Creates a concrete NuclideModel from a QueryEngine pointer as well as geometry and material data.
Parameters:
qe query engine pointer describing the nuclide model
mat_table a pointer to the material table
geom a pointer to the Geometry object
comp_id the id number of the owning component
Definition at line 63 of file NuclideModelFactory.cpp.
References nuclideModel().
NuclideModelPtr NuclideModelFactory::nuclideModel (NuclideModelPtr src, MatDataTablePtr mat_table, GeometryPtr geom, int comp_id) static
Creates a copy of a NuclideModel from another NuclideModel as well as geometry and material data.
Parameters:
src the original NuclideModel
mat_table a pointer to the material table
geom a pointer to the Geometry object
comp_id the id number of the owning component
Definition at line 74 of file NuclideModelFactory.cpp.
References StubNuclide::create(), DegRateNuclide::create(), MixedCellNuclide::create(), LumpedNuclide::create(), OneDimPPMNuclide::create(), DEGRATE_NUCLIDE, LUMPED_NUCLIDE, MIXEDCELL_NUCLIDE, ONEDIMPPM_NUCLIDE, and STUB_NUCLIDE.
Member Data Documentation
std::string NuclideModelFactory::nuclide_type_names_ static protected
Initial value:
 {
  "DegRateNuclide",
  "LumpedNuclide",
  "MixedCellNuclide",
  "OneDimPPMNuclide",
  "StubNuclide",
}
NuclideModelType names list.
Definition at line 63 of file NuclideModelFactory.h.
Referenced by nuclideEnum().
The documentation for this class was generated from the following files:
NuclideModelFactory.h
NuclideModelFactory.cpp