cyder: StubNuclide Class Reference
StubNuclide Class Reference
StubNuclide is a skeleton nuclide model model that does nothing.
#include <StubNuclide.h>
Public Member Functions
virtual void absorb (mat_rsrc_ptr matToAdd)
Absorbs the contents of the given Material into this StubNuclide.
virtual IsoFluxMap cauchy_bc (IsoConcMap c_ext, Radius r_ext)
returns the flux at the boundary, the Neumann bc
virtual NuclideModelPtr copy (const NuclideModel &src)
copies a nuclide model and its parameters from another
virtual IsoConcMap dirichlet_bc ()
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
virtual mat_rsrc_ptr extract (CompMapPtr comp_to_rem, double kg_to_rem)
Extracts the contents of the given Material from this NuclideModel.
virtual void initModuleMembers (QueryEngine *qe)
initializes the model parameters from an xmlNodePtr
virtual std::string name ()
Returns the nuclide model type name.
virtual ConcGradMap neumann_bc (IsoConcMap c_ext, Radius r_ext)
returns the concentration gradient at the boundary, the Neumann bc
virtual void print ()
standard verbose printer includes current temp and concentrations
virtual std::pair< IsoVector,
double > source_term_bc ()
returns the available material source term at the outer boundary of the component
virtual void transportNuclides (int time)
Transports nuclides from the inner to the outer boundary.
virtual NuclideModelType type ()
Returns the nuclide model type.
virtual void update (int the_time)
Updates all the hists.
void update_inner_bc (int the_time, std::vector< NuclideModelPtr > daughters)
Determines what IsoVector to remove from the daughter nuclide models.
virtual void updateNuclideParamsTable ()
Updates the NuclideParams table by adding appropriate rows to describe the parameters initializing this NuclideModel.
virtual double V_ff ()
returns the fluid volume.
virtual double V_T ()
virtual ~StubNuclide ()
Virtual destructor deletes datamembers that are object pointers.
Public Member Functions inherited from NuclideModel
virtual void addRowToNuclideParamsTable (std::string param_name, boost::any param_val)
adds a row to the NuclideModelParams table.
ConcGrad calc_conc_grad (Concentration c_ext, Concentration c_int, Radius r_ext, Radius r_int)
Returns the concentration gradient based on a simple finite difference between two datapoints.
Flux cauchy_bc (IsoConcMap c_ext, Radius r_ext, Iso tope)
IsoConcMap conc_hist (int the_time)
Returns the map of isotopes to concentrations at the time profided.
Concentration conc_hist (int the_time, Iso tope)
Returns the concetration of a certain isotope at a certain time.
double contained_mass (int the_time)
returns the current contained contaminant mass, in kg, at time
IsoVector contained_vec (int the_time)
The IsoVector representing the summed, normalized material in the component.
virtual Concentration dirichlet_bc (Iso tope)
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
virtual BCType enumerateBCType (std::string type_name)
spits out a number instead of a BCType
const GeometryPtr geom () const
Returns the geom_ data member.
int last_updated ()
returns the time at which the vec_hist and conc_hist were updated
virtual ConcGrad neumann_bc (IsoConcMap c_ext, Radius r_ext, Iso tope)
returns the concentration gradient at the boundary, the Neumann bc
void set_comp_id (int id)
Allows the component id data member to be set.
void set_geom (GeometryPtr geom)
Allows the geometry object to be set.
void set_last_updated (int new_last_updated)
sets the last time that the vec_hist and conc_hist were updated, first verifying whether last_updated is larger than last_updated_
void set_mat_table (MatDataTablePtr mat_table)
sends a pointer to the material table used by this component
virtual double source_term_bc (Iso tope)
returns the prescribed concentration at the boundary, the source term bc in kg
std::pair< IsoVector, double > vec_hist (int the_time)
Returns the IsoVector mass pair for a certain time.
std::deque< mat_rsrc_ptr > wastes ()
Returns wastes_.
virtual ~NuclideModel ()
A virtual destructor.
Static Public Member Functions
static StubNuclidePtr create ()
A constructor for the Stub Nuclide Model that returns a shared pointer.
static StubNuclidePtr create (QueryEngine *qe)
A constructor for the Stub Nuclide Model that returns a shared pointer.
Private Member Functions
StubNuclide ()
Default constructor for the nuclide model class.
StubNuclide (QueryEngine *qe)
primary constructor reads input from QueryEngine
Additional Inherited Members
Protected Attributes inherited from NuclideModel
int comp_id_
the id of the component that this nuclidemodel is a part of
ConcHist conc_hist_
The map of times to isotopes to concentrations, in kg/m^3.
GeometryPtr geom_
A shared pointer to the geometry of the component.
int last_updated_
the time at which the histories were last updated
MatDataTablePtr mat_table_
A shared pointer to this Component's material data table.
VecHist vec_hist_
The map of times to IsoVectors.
std::deque< mat_rsrc_ptr > wastes_
A vector of the wastes contained by this component wastes(){return component_->wastes();};.
Detailed Description
StubNuclide is a skeleton nuclide model model that does nothing.
This disposal system nuclide model will do nothing. This NuclideModel is intended as a skeleton to guide the implementation of new NuclideModels.
The StubNuclide model can be used to represent nuclide models of the disposal system such as the Waste Form, Waste Package, Buffer, Near Field, Far Field, and Envrionment.
Definition at line 31 of file StubNuclide.h.
Constructor & Destructor Documentation
StubNuclide::StubNuclide () private
Default constructor for the nuclide model class.
Creates an empty nuclide model.
Definition at line 18 of file StubNuclide.cpp.
Referenced by create().
StubNuclide::StubNuclide (QueryEngine * qe) private
primary constructor reads input from QueryEngine
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 26 of file StubNuclide.cpp.
StubNuclide::~StubNuclide () virtual
Virtual destructor deletes datamembers that are object pointers.
Definition at line 35 of file StubNuclide.cpp.
Member Function Documentation
void StubNuclide::absorb (mat_rsrc_ptr matToAdd) virtual
Absorbs the contents of the given Material into this StubNuclide.
Parameters:
matToAdd the StubNuclide to be absorbed
Implements NuclideModel.
Definition at line 59 of file StubNuclide.cpp.
IsoFluxMap StubNuclide::cauchy_bc (IsoConcMap c_ext, Radius r_ext) virtual
returns the flux at the boundary, the Neumann bc
Returns:
qC the solute flux at the boundary in kg/m^2/s
This is just a placeholder
Implements NuclideModel.
Definition at line 130 of file StubNuclide.cpp.
NuclideModelPtr StubNuclide::copy (const NuclideModel & src) virtual
copies a nuclide model and its parameters from another
Parameters:
src is the nuclide model being copied
Implements NuclideModel.
Definition at line 48 of file StubNuclide.cpp.
static StubNuclidePtr StubNuclide::create () inline static
A constructor for the Stub Nuclide Model that returns a shared pointer.
Definition at line 55 of file StubNuclide.h.
References StubNuclide().
Referenced by StubNuclideTest::initNuclideModel(), NuclideModelFactory::nuclideModel(), StubNuclideTest::SetUp(), StubNuclideModelConstructor(), and TEST_F().
static StubNuclidePtr StubNuclide::create (QueryEngine * qe) inline static
A constructor for the Stub Nuclide Model that returns a shared pointer.
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 62 of file StubNuclide.h.
References StubNuclide().
IsoConcMap StubNuclide::dirichlet_bc () virtual
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
Returns:
C the concentration at the boundary in kg/m^3 for each isotope
This is just a placeholder
Implements NuclideModel.
Definition at line 118 of file StubNuclide.cpp.
mat_rsrc_ptr StubNuclide::extract (CompMapPtr comp_to_rem, double kg_to_rem) virtual
Extracts the contents of the given Material from this NuclideModel.
Use this function for decrementing a NuclideModel's mass balance after transferring through a link.
Parameters:
comp_to_rem the composition to decrement against this StubNuclide
comp_to_rem the mass in kg to decrement against this StubNuclide
Returns:
the material extracted
Implements NuclideModel.
Definition at line 69 of file StubNuclide.cpp.
References MatTools::extract().
void StubNuclide::initModuleMembers (QueryEngine * qe) virtual
initializes the model parameters from an xmlNodePtr
Parameters:
qe is the QueryEngine object containing intialization info
Implements NuclideModel.
Definition at line 38 of file StubNuclide.cpp.
virtual std::string StubNuclide::name () inline virtual
Returns the nuclide model type name.
Implements NuclideModel.
Definition at line 127 of file StubNuclide.h.
ConcGradMap StubNuclide::neumann_bc (IsoConcMap c_ext, Radius r_ext) virtual
returns the concentration gradient at the boundary, the Neumann bc
Returns:
dCdx the concentration gradient at the boundary in kg/m^3
This is just a placeholder
Implements NuclideModel.
Definition at line 124 of file StubNuclide.cpp.
void StubNuclide::print () virtual
standard verbose printer includes current temp and concentrations
Implements NuclideModel.
Definition at line 54 of file StubNuclide.cpp.
pair< IsoVector, double > StubNuclide::source_term_bc () virtual
returns the available material source term at the outer boundary of the component
Returns:
the IsoVector and mass defining the outer boundary condition
This is just a placeholder
Implements NuclideModel.
Definition at line 111 of file StubNuclide.cpp.
void StubNuclide::transportNuclides (int time) virtual
Transports nuclides from the inner to the outer boundary.
Parameters:
time the timestep at which to transport the nuclides
Implements NuclideModel.
Definition at line 82 of file StubNuclide.cpp.
virtual NuclideModelType StubNuclide::type () inline virtual
Returns the nuclide model type.
Implements NuclideModel.
Definition at line 122 of file StubNuclide.h.
References STUB_NUCLIDE.
void StubNuclide::update (int the_time) virtual
Updates all the hists.
Parameters:
the_time the time at which to update the history
Implements NuclideModel.
Definition at line 93 of file StubNuclide.cpp.
void StubNuclide::update_inner_bc (int the_time, std::vector< NuclideModelPtr > daughters) virtual
Determines what IsoVector to remove from the daughter nuclide models.
Parameters:
time the timestep at which the nuclides should be transported
daughter nuclide_model of an internal component. there may be many.
Implements NuclideModel.
Definition at line 97 of file StubNuclide.cpp.
void StubNuclide::updateNuclideParamsTable () virtual
Updates the NuclideParams table by adding appropriate rows to describe the parameters initializing this NuclideModel.
Implements NuclideModel.
Definition at line 44 of file StubNuclide.cpp.
virtual double StubNuclide::V_ff () inline virtual
returns the fluid volume.
Here, naively, it returns the total volume.
Implements NuclideModel.
Definition at line 169 of file StubNuclide.h.
References NuclideModel::geom_.
virtual double StubNuclide::V_T () inline virtual
Implements NuclideModel.
Definition at line 170 of file StubNuclide.h.
References NuclideModel::geom_.
The documentation for this class was generated from the following files:
StubNuclide.h
StubNuclide.cpp