cyder: LumpedThermal Class Reference
LumpedThermal Class Reference
LumpedThermal is a skeleton component model that does nothing.
#include <LumpedThermal.h>
Public Member Functions
virtual void copy (const ThermalModel &src)
copies a component and its parameters from another
virtual void initModuleMembers (QueryEngine *qe)
initializes the model parameters from an QueryEngine object
virtual bool mat_acceptable (mat_rsrc_ptr mat, Radius r_lim, Temp t_lim)
This function says whether or not the material is acceptable to this repository at r_lim for the limit t_lim.
virtual std::string name ()
return the thermal model implementation type
virtual Temp peak_temp ()
gets the peak temperature that this component will experience on the boundary
virtual void print ()
standard verbose printer includes current temp and concentrations
virtual Temp temp ()
gets the temperature average in the component
virtual void transportHeat (int time)
transports the heat
virtual const ThermalModelType type ()
return the thermal model implementation type
~LumpedThermal ()
Default destructor does nothing.
Public Member Functions inherited from ThermalModel
GeometryPtr geom ()
void set_geom (GeometryPtr geom)
set the geometry shared pointer
void set_mat_table (MatDataTablePtr mat_table)
set the MatDataTablePtr shared pointer
virtual ~ThermalModel ()
A virtual destructor.
Static Public Member Functions
static LumpedThermalPtr create ()
A constructor for the Lumped Nuclide Model that returns a shared pointer.
static LumpedThermalPtr create (QueryEngine *qe)
A constructor for the Lumped Nuclide Model that returns a shared pointer.
Private Member Functions
LumpedThermal ()
Default constructor for the component class.
LumpedThermal (QueryEngine *qe)
primary constructor reads input from XML node
Additional Inherited Members
Protected Attributes inherited from ThermalModel
GeometryPtr geom_
A shared pointer to the geometry of this component.
MatDataTablePtr mat_table_
A shared pointer to the MatDataTablePtr representing the material of this component.
TempHist temp_hist_
The temperature history of this component.
Temp temperature_
The temperature of this component, on average.
Detailed Description
LumpedThermal is a skeleton component model that does nothing.
This disposal system component will do nothing. This Component is intended as a skeleton to guide the implementation of new Components.
The LumpedThermal model can be used to represent components of the disposal system such as the Waste Form, Waste Package, Buffer, Near Field, Far Field, and Envrionment.
Definition at line 30 of file LumpedThermal.h.
Constructor & Destructor Documentation
LumpedThermal::LumpedThermal () inline private
Default constructor for the component class.
Creates an empty component.
Definition at line 35 of file LumpedThermal.h.
Referenced by create().
LumpedThermal::LumpedThermal (QueryEngine * qe) inline private
primary constructor reads input from XML node
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 42 of file LumpedThermal.h.
LumpedThermal::~LumpedThermal () inline
Default destructor does nothing.
Definition at line 61 of file LumpedThermal.h.
Member Function Documentation
void LumpedThermal::copy (const ThermalModel & src) virtual
copies a component and its parameters from another
Parameters:
src is the component being copied
Implements ThermalModel.
Definition at line 22 of file LumpedThermal.cpp.
static LumpedThermalPtr LumpedThermal::create () inline static
A constructor for the Lumped Nuclide Model that returns a shared pointer.
Definition at line 49 of file LumpedThermal.h.
References LumpedThermal().
Referenced by ThermalModelFactory::thermalModel().
static LumpedThermalPtr LumpedThermal::create (QueryEngine * qe) inline static
A constructor for the Lumped Nuclide Model that returns a shared pointer.
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 56 of file LumpedThermal.h.
References LumpedThermal().
void LumpedThermal::initModuleMembers (QueryEngine * qe) virtual
initializes the model parameters from an QueryEngine object
Parameters:
qe is the QueryEngine object containing intialization info
Implements ThermalModel.
Definition at line 17 of file LumpedThermal.cpp.
bool LumpedThermal::mat_acceptable (mat_rsrc_ptr mat, Radius r_lim, Temp t_lim) virtual
This function says whether or not the material is acceptable to this repository at r_lim for the limit t_lim.
Parameters:
mat the material whose whose contribution to query
r_lim the limiting radius
t_lim the limiting temperature
Returns:
mat_acceptable (true when acceptable, false otherwise)
obviously, put some logic here.
Implements ThermalModel.
Definition at line 46 of file LumpedThermal.cpp.
virtual std::string LumpedThermal::name () inline virtual
return the thermal model implementation type
Returns:
impl_name_ the name of the ThermalModel implementation
Implements ThermalModel.
Definition at line 101 of file LumpedThermal.h.
Temp LumpedThermal::peak_temp () virtual
gets the peak temperature that this component will experience on the boundary
Implements ThermalModel.
Definition at line 38 of file LumpedThermal.cpp.
void LumpedThermal::print () virtual
standard verbose printer includes current temp and concentrations
Implements ThermalModel.
Definition at line 26 of file LumpedThermal.cpp.
Temp LumpedThermal::temp () virtual
gets the temperature average in the component
Implements ThermalModel.
Definition at line 52 of file LumpedThermal.cpp.
void LumpedThermal::transportHeat (int time) virtual
transports the heat
Parameters:
time the timestep at which to transport the heat
Implements ThermalModel.
Definition at line 32 of file LumpedThermal.cpp.
virtual const ThermalModelType LumpedThermal::type () inline virtual
return the thermal model implementation type
Returns:
impl_name_ the name of the ThermalModel implementation
Implements ThermalModel.
Definition at line 94 of file LumpedThermal.h.
References LUMPED_THERMAL.
The documentation for this class was generated from the following files:
LumpedThermal.h
LumpedThermal.cpp