cyder: DegRateNuclideTest Class Reference
DegRateNuclideTest Class Reference
#include <DegRateNuclideTests.h>
Protected Member Functions
DegRateNuclidePtr initNuclideModel ()
virtual void SetUp ()
virtual void TearDown ()
Protected Attributes
double adv_vel_
int am241_
DegRateNuclidePtr default_deg_rate_ptr_
NuclideModelPtr default_nuc_model_ptr_
double deg_rate_
DegRateNuclidePtr deg_rate_ptr_
GeometryPtr geom_
Length len_five_
MatDataTablePtr mat_table_
NuclideModelPtr nuc_model_ptr_
int one_mol_
point_t origin_
Radius r_five_
Radius r_four_
CompMapPtr test_comp_
mat_rsrc_ptr test_mat_
double test_size_
double theta_
int time_
int u235_
Elem u_
Detailed Description
Definition at line 11 of file DegRateNuclideTests.h.
Member Function Documentation
DegRateNuclidePtr DegRateNuclideTest::initNuclideModel () protected
Definition at line 63 of file DegRateNuclideTests.cpp.
References DegRateNuclide::create().
void DegRateNuclideTest::SetUp () protected virtual
Definition at line 18 of file DegRateNuclideTests.cpp.
References DegRateNuclide::create(), MDB, and NuclideModel::set_mat_table().
void DegRateNuclideTest::TearDown () protected virtual
Definition at line 55 of file DegRateNuclideTests.cpp.
Member Data Documentation
double DegRateNuclideTest::adv_vel_ protected
Definition at line 26 of file DegRateNuclideTests.h.
int DegRateNuclideTest::am241_ protected
Definition at line 22 of file DegRateNuclideTests.h.
DegRateNuclidePtr DegRateNuclideTest::default_deg_rate_ptr_ protected
Definition at line 15 of file DegRateNuclideTests.h.
NuclideModelPtr DegRateNuclideTest::default_nuc_model_ptr_ protected
Definition at line 17 of file DegRateNuclideTests.h.
double DegRateNuclideTest::deg_rate_ protected
Definition at line 18 of file DegRateNuclideTests.h.
DegRateNuclidePtr DegRateNuclideTest::deg_rate_ptr_ protected
Definition at line 14 of file DegRateNuclideTests.h.
GeometryPtr DegRateNuclideTest::geom_ protected
Definition at line 28 of file DegRateNuclideTests.h.
Length DegRateNuclideTest::len_five_ protected
Definition at line 30 of file DegRateNuclideTests.h.
MatDataTablePtr DegRateNuclideTest::mat_table_ protected
Definition at line 27 of file DegRateNuclideTests.h.
NuclideModelPtr DegRateNuclideTest::nuc_model_ptr_ protected
Definition at line 16 of file DegRateNuclideTests.h.
int DegRateNuclideTest::one_mol_ protected
Definition at line 21 of file DegRateNuclideTests.h.
point_t DegRateNuclideTest::origin_ protected
Definition at line 31 of file DegRateNuclideTests.h.
Radius DegRateNuclideTest::r_five_ protected
Definition at line 29 of file DegRateNuclideTests.h.
Radius DegRateNuclideTest::r_four_ protected
Definition at line 29 of file DegRateNuclideTests.h.
CompMapPtr DegRateNuclideTest::test_comp_ protected
Definition at line 19 of file DegRateNuclideTests.h.
mat_rsrc_ptr DegRateNuclideTest::test_mat_ protected
Definition at line 20 of file DegRateNuclideTests.h.
double DegRateNuclideTest::test_size_ protected
Definition at line 24 of file DegRateNuclideTests.h.
double DegRateNuclideTest::theta_ protected
Definition at line 25 of file DegRateNuclideTests.h.
int DegRateNuclideTest::time_ protected
Definition at line 32 of file DegRateNuclideTests.h.
int DegRateNuclideTest::u235_ protected
Definition at line 22 of file DegRateNuclideTests.h.
Elem DegRateNuclideTest::u_ protected
Definition at line 23 of file DegRateNuclideTests.h.
The documentation for this class was generated from the following files:
DegRateNuclideTests.h
DegRateNuclideTests.cpp