cyder: OneDimPPMNuclideTest Class Reference
OneDimPPMNuclideTest Class Reference
#include <OneDimPPMNuclideTests.h>
Protected Member Functions
IsoConcMap calculate_conc (IsoConcMap C_0, Radius r, int dt)
double calculate_conc (IsoConcMap C_0, IsoConcMap C_i, Radius r, Iso iso, int t0, int t)
OneDimPPMNuclidePtr initNuclideModel ()
virtual void SetUp ()
virtual void TearDown ()
Protected Attributes
int am241_
double Ci_
double Co_
double D_
NuclideModelPtr default_nuc_model_ptr_
OneDimPPMNuclidePtr default_one_dim_ppm_ptr_
GeometryPtr geom_
double Kd_
Length len_five_
MatDataTablePtr mat_table_
NuclideModelPtr nuc_model_ptr_
double one_dim_ppm_
OneDimPPMNuclidePtr one_dim_ppm_ptr_
int one_kg_
point_t origin_
double porosity_
Radius r_five_
Radius r_four_
double rho_
CompMapPtr test_comp_
mat_rsrc_ptr test_mat_
double test_size_
double theta_
int time_
int u235_
double v_
Detailed Description
Definition at line 10 of file OneDimPPMNuclideTests.h.
Member Function Documentation
IsoConcMap OneDimPPMNuclideTest::calculate_conc (IsoConcMap C_0, Radius r, int dt) protected
Definition at line 92 of file OneDimPPMNuclideTests.cpp.
double OneDimPPMNuclideTest::calculate_conc (IsoConcMap C_0, IsoConcMap C_i, Radius r, Iso iso, int t0, int t) protected
Definition at line 64 of file OneDimPPMNuclideTests.cpp.
OneDimPPMNuclidePtr OneDimPPMNuclideTest::initNuclideModel () protected
Definition at line 109 of file OneDimPPMNuclideTests.cpp.
References OneDimPPMNuclide::create().
void OneDimPPMNuclideTest::SetUp () protected virtual
Definition at line 17 of file OneDimPPMNuclideTests.cpp.
References OneDimPPMNuclide::create(), MDB, and NuclideModel::set_mat_table().
void OneDimPPMNuclideTest::TearDown () protected virtual
Definition at line 60 of file OneDimPPMNuclideTests.cpp.
Member Data Documentation
int OneDimPPMNuclideTest::am241_ protected
Definition at line 22 of file OneDimPPMNuclideTests.h.
double OneDimPPMNuclideTest::Ci_ protected
Definition at line 31 of file OneDimPPMNuclideTests.h.
double OneDimPPMNuclideTest::Co_ protected
Definition at line 31 of file OneDimPPMNuclideTests.h.
double OneDimPPMNuclideTest::D_ protected
Definition at line 31 of file OneDimPPMNuclideTests.h.
NuclideModelPtr OneDimPPMNuclideTest::default_nuc_model_ptr_ protected
Definition at line 16 of file OneDimPPMNuclideTests.h.
OneDimPPMNuclidePtr OneDimPPMNuclideTest::default_one_dim_ppm_ptr_ protected
Definition at line 14 of file OneDimPPMNuclideTests.h.
GeometryPtr OneDimPPMNuclideTest::geom_ protected
Definition at line 26 of file OneDimPPMNuclideTests.h.
double OneDimPPMNuclideTest::Kd_ protected
Definition at line 31 of file OneDimPPMNuclideTests.h.
Length OneDimPPMNuclideTest::len_five_ protected
Definition at line 28 of file OneDimPPMNuclideTests.h.
MatDataTablePtr OneDimPPMNuclideTest::mat_table_ protected
Definition at line 17 of file OneDimPPMNuclideTests.h.
NuclideModelPtr OneDimPPMNuclideTest::nuc_model_ptr_ protected
Definition at line 15 of file OneDimPPMNuclideTests.h.
double OneDimPPMNuclideTest::one_dim_ppm_ protected
Definition at line 18 of file OneDimPPMNuclideTests.h.
OneDimPPMNuclidePtr OneDimPPMNuclideTest::one_dim_ppm_ptr_ protected
Definition at line 13 of file OneDimPPMNuclideTests.h.
int OneDimPPMNuclideTest::one_kg_ protected
Definition at line 21 of file OneDimPPMNuclideTests.h.
point_t OneDimPPMNuclideTest::origin_ protected
Definition at line 29 of file OneDimPPMNuclideTests.h.
double OneDimPPMNuclideTest::porosity_ protected
Definition at line 31 of file OneDimPPMNuclideTests.h.
Radius OneDimPPMNuclideTest::r_five_ protected
Definition at line 27 of file OneDimPPMNuclideTests.h.
Radius OneDimPPMNuclideTest::r_four_ protected
Definition at line 27 of file OneDimPPMNuclideTests.h.
double OneDimPPMNuclideTest::rho_ protected
Definition at line 31 of file OneDimPPMNuclideTests.h.
CompMapPtr OneDimPPMNuclideTest::test_comp_ protected
Definition at line 19 of file OneDimPPMNuclideTests.h.
mat_rsrc_ptr OneDimPPMNuclideTest::test_mat_ protected
Definition at line 20 of file OneDimPPMNuclideTests.h.
double OneDimPPMNuclideTest::test_size_ protected
Definition at line 23 of file OneDimPPMNuclideTests.h.
double OneDimPPMNuclideTest::theta_ protected
Definition at line 24 of file OneDimPPMNuclideTests.h.
int OneDimPPMNuclideTest::time_ protected
Definition at line 30 of file OneDimPPMNuclideTests.h.
int OneDimPPMNuclideTest::u235_ protected
Definition at line 22 of file OneDimPPMNuclideTests.h.
double OneDimPPMNuclideTest::v_ protected
Definition at line 25 of file OneDimPPMNuclideTests.h.
The documentation for this class was generated from the following files:
OneDimPPMNuclideTests.h
OneDimPPMNuclideTests.cpp