cyder: LumpedNuclide Class Reference
LumpedNuclide Class Reference
LumpedNuclide is a nuclide transport model that treats the volume as a lumped parameter type nuclide transport model.
#include <LumpedNuclide.h>
Public Member Functions
virtual void absorb (mat_rsrc_ptr matToAdd)
Absorbs the contents of the given Material into this LumpedNuclide model.
const IsoConcMap C_0 () const
Returns the inner boundary condition.
IsoConcMap C_DM (IsoConcMap C_0, int the_time)
DM model concentration calculator.
IsoConcMap C_EXPM (IsoConcMap C_0, int the_time)
EXPM model concentration calculator.
IsoConcMap C_PFM (IsoConcMap C_0, int the_time)
PFM model concentration calculator.
IsoConcMap C_t (IsoConcMap C_0, int the_time)
concentration calculator for this->formulation_ model
virtual IsoFluxMap cauchy_bc (IsoConcMap c_ext, Radius r_ext)
returns the flux at the boundary, the Neumann bc
virtual NuclideModelPtr copy (const NuclideModel &src)
copies a nuclide model and its parameters from another
virtual IsoConcMap dirichlet_bc ()
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
FormulationType enumerateFormulation (std::string formulation)
Returns the FormulationType corresponding to the string.
virtual mat_rsrc_ptr extract (CompMapPtr comp_to_rem, double kg_to_rem)
Extracts the contents of the given Material from this NuclideModel.
mat_rsrc_ptr extractIntegratedMass (NuclideModelPtr daughter, double the_time)
Extracts one timestep's mass from the daughter nuclidemodel.
const FormulationType formulation () const
Returns the formulation of the concentration relationship.
virtual void initModuleMembers (QueryEngine *qe)
initializes the model parameters from an QueryEngine object
virtual std::string name ()
Returns the nuclide model type name.
virtual ConcGradMap neumann_bc (IsoConcMap c_ext, Radius r_ext)
returns the concentration gradient at the boundary, the Neumann bc
const double Pe () const
Returns the peclet number of the component [-].
const double porosity () const
The porosity of the permeable porous mediuam of this component. [%].
virtual void print ()
standard verbose printer includes current temp and concentrations
void set_C_0 (IsoConcMap C_0)
Sets the internal boundary condition.
void set_formulation (std::string formulation)
Sets the formulation of the concentration relationship.
void set_formulation (FormulationType formulation)
Sets the formulation of the concentration relationship.
void set_Pe (double Pe)
Sets the peclet_ variable, the ratio of advective to diffusive transport.
void set_porosity (double porosity)
Sets the porosity_ variable, the percent of the permeable porous medium.
virtual std::pair< IsoVector,
double > source_term_bc ()
returns the available material source term at the outer boundary of the component
const double t_t () const
Returns the transit time through the component [-].
virtual void transportNuclides (int time)
Transports nuclides from the inner to the outer boundary.
virtual NuclideModelType type ()
Returns the nuclide model type.
virtual void update (int the_time)
Updates all the hists.
void update_conc_hist (int the_time)
Updates the available concentration using the wastes_ as mats.
void update_conc_hist (int the_time, std::deque< mat_rsrc_ptr > mats)
Updates the available concentration.
void update_inner_bc (int the_time, std::vector< NuclideModelPtr > daughters)
Determines what IsoVector to remove from the daughter nuclide models.
void update_vec_hist (int the_time)
Updates the contained vector.
virtual void updateNuclideParamsTable ()
Updates the NuclideParams table by adding appropriate rows to describe the parameters initializing this NuclideModel.
const double v () const
The advective velocity through this component.
double V_f ()
Gets the fluid volume, based on porosity.
virtual double V_ff ()
Gets the free fluid volume. Same as V_f (no sorption or solubility)
double V_s ()
Gets the fluid volume, based on porosity.
double V_T ()
Gets the total volume.
virtual ~LumpedNuclide ()
Virtual destructor deletes datamembers that are object pointers.
Public Member Functions inherited from NuclideModel
virtual void addRowToNuclideParamsTable (std::string param_name, boost::any param_val)
adds a row to the NuclideModelParams table.
ConcGrad calc_conc_grad (Concentration c_ext, Concentration c_int, Radius r_ext, Radius r_int)
Returns the concentration gradient based on a simple finite difference between two datapoints.
Flux cauchy_bc (IsoConcMap c_ext, Radius r_ext, Iso tope)
IsoConcMap conc_hist (int the_time)
Returns the map of isotopes to concentrations at the time profided.
Concentration conc_hist (int the_time, Iso tope)
Returns the concetration of a certain isotope at a certain time.
double contained_mass (int the_time)
returns the current contained contaminant mass, in kg, at time
IsoVector contained_vec (int the_time)
The IsoVector representing the summed, normalized material in the component.
virtual Concentration dirichlet_bc (Iso tope)
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
virtual BCType enumerateBCType (std::string type_name)
spits out a number instead of a BCType
const GeometryPtr geom () const
Returns the geom_ data member.
int last_updated ()
returns the time at which the vec_hist and conc_hist were updated
virtual ConcGrad neumann_bc (IsoConcMap c_ext, Radius r_ext, Iso tope)
returns the concentration gradient at the boundary, the Neumann bc
void set_comp_id (int id)
Allows the component id data member to be set.
void set_geom (GeometryPtr geom)
Allows the geometry object to be set.
void set_last_updated (int new_last_updated)
sets the last time that the vec_hist and conc_hist were updated, first verifying whether last_updated is larger than last_updated_
void set_mat_table (MatDataTablePtr mat_table)
sends a pointer to the material table used by this component
virtual double source_term_bc (Iso tope)
returns the prescribed concentration at the boundary, the source term bc in kg
std::pair< IsoVector, double > vec_hist (int the_time)
Returns the IsoVector mass pair for a certain time.
std::deque< mat_rsrc_ptr > wastes ()
Returns wastes_.
virtual ~NuclideModel ()
A virtual destructor.
Static Public Member Functions
static LumpedNuclidePtr create ()
A constructor for the Lumped Nuclide Model that returns a shared pointer.
static LumpedNuclidePtr create (QueryEngine *qe)
A constructor for the Lumped Nuclide Model that returns a shared pointer.
Protected Attributes
IsoConcMap C_0_
the current conc map at the inner boundary
FormulationType formulation_
The name of the lumped parameter model formulation.
double Pe_
The dimensionless mass diffusion Peclet number of the medium [-].
double porosity_
The porosity of the permeable porous medium.
double t_t_
The transit time of a radioactive tracer through the cell.
double v_
The advective velocity through this component [m/s].
Protected Attributes inherited from NuclideModel
int comp_id_
the id of the component that this nuclidemodel is a part of
ConcHist conc_hist_
The map of times to isotopes to concentrations, in kg/m^3.
GeometryPtr geom_
A shared pointer to the geometry of the component.
int last_updated_
the time at which the histories were last updated
MatDataTablePtr mat_table_
A shared pointer to this Component's material data table.
VecHist vec_hist_
The map of times to IsoVectors.
std::deque< mat_rsrc_ptr > wastes_
A vector of the wastes contained by this component wastes(){return component_->wastes();};.
Private Member Functions
LumpedNuclide ()
Default constructor for the lumped parameter nuclide model class.
LumpedNuclide (QueryEngine *qe)
primary constructor reads input from QueryEngine
Detailed Description
LumpedNuclide is a nuclide transport model that treats the volume as a lumped parameter type nuclide transport model.
This method is experimental, and was not proposed in my prelim. This model may be influence by a paper by Zuber and Maloszewski, as well as the inverse problem of that discussed in :
Zuber, A., Maloszewski, P., 2001. Lumped-parameter models. Environmental Isotopes in the Hydrological Cycle. Vol. 6: Modelling, UNESCO, Paris, Tech. Doc. in Hydrology 39, 535.
and :
"Lumped Parameter models as a tool for determining the hydrological parameters of some groundwater systems based on isotope data." Tracers and Modelling in Hydrogeology. (Proceedings of the TraM 2000 Conference in Liege Belgium, May 2000). IAH Publ. no 262, 2000.
This disposal system nuclide model will receive material blindly at both borders. Received material will be incorporated and transferred to the opposite boundary according to lumped conductivity parameters.
The parameters may be dependent on current contaiminant concentration.
The LumpedNuclide model can be used to represent nuclide models of the disposal system such as the Waste Form, Waste Package, Buffer, Near Field, Far Field, and Envrionment.
Definition at line 53 of file LumpedNuclide.h.
Constructor & Destructor Documentation
LumpedNuclide::LumpedNuclide () private
Default constructor for the lumped parameter nuclide model class.
Creates an empty lumped parameter volume with contaminant concentration zero unless an initial contaminant concentration is specified.
Definition at line 20 of file LumpedNuclide.cpp.
References C_0_, NuclideModel::conc_hist_, NuclideModel::last_updated_, Pe_, NuclideModel::set_geom(), and NuclideModel::vec_hist_.
Referenced by create().
LumpedNuclide::LumpedNuclide (QueryEngine * qe) private
primary constructor reads input from QueryEngine
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 37 of file LumpedNuclide.cpp.
References C_0_, NuclideModel::conc_hist_, initModuleMembers(), NuclideModel::last_updated_, NuclideModel::set_geom(), and NuclideModel::vec_hist_.
LumpedNuclide::~LumpedNuclide () virtual
Virtual destructor deletes datamembers that are object pointers.
Definition at line 55 of file LumpedNuclide.cpp.
Member Function Documentation
void LumpedNuclide::absorb (mat_rsrc_ptr matToAdd) virtual
Absorbs the contents of the given Material into this LumpedNuclide model.
Parameters:
matToAdd the LumpedNuclide to be absorbed
Implements NuclideModel.
Definition at line 148 of file LumpedNuclide.cpp.
References NuclideModel::wastes_.
Referenced by update_inner_bc().
const IsoConcMap LumpedNuclide::C_0 () const inline
Returns the inner boundary condition.
Definition at line 189 of file LumpedNuclide.h.
References C_0_.
Referenced by extractIntegratedMass(), set_C_0(), and update_inner_bc().
IsoConcMap LumpedNuclide::C_DM (IsoConcMap C_0, int the_time)
DM model concentration calculator.
Parameters:
C_0 the incoming concentration map
the_time the length of the timestep over which to calculate
Returns:
C_f the final concentration at the end of the timestep
Definition at line 397 of file LumpedNuclide.cpp.
References Pe(), MatTools::scaleConcMap(), and t_t().
Referenced by C_t().
IsoConcMap LumpedNuclide::C_EXPM (IsoConcMap C_0, int the_time)
EXPM model concentration calculator.
Parameters:
C_0 the incoming concentration map
the_time the length of the timestep over which to calculate
Returns:
C_f the final concentration at the end of the timestep
Definition at line 403 of file LumpedNuclide.cpp.
References MatTools::scaleConcMap(), and t_t().
Referenced by C_t().
IsoConcMap LumpedNuclide::C_PFM (IsoConcMap C_0, int the_time)
PFM model concentration calculator.
Parameters:
C_0 the incoming concentration map
the_time the length of the timestep over which to calculate
Returns:
C_f the final concentration at the end of the timestep
Definition at line 408 of file LumpedNuclide.cpp.
References MatTools::scaleConcMap(), and t_t().
Referenced by C_t().
IsoConcMap LumpedNuclide::C_t (IsoConcMap C_0, int the_time)
concentration calculator for this->formulation_ model
Parameters:
C_0 the incoming concentration map
the_time the length of the timestep over which to calculate
Returns:
C_f the final concentration at the end of the timestep
Definition at line 369 of file LumpedNuclide.cpp.
References C_DM(), C_EXPM(), C_PFM(), DM, EXPM, formulation_, and PFM.
Referenced by extractIntegratedMass().
IsoFluxMap LumpedNuclide::cauchy_bc (IsoConcMap c_ext, Radius r_ext) virtual
returns the flux at the boundary, the Neumann bc
Returns:
qC the solute flux at the boundary in kg/m^2/s
Implements NuclideModel.
Definition at line 232 of file LumpedNuclide.cpp.
References NuclideModel::mat_table_, neumann_bc(), and v().
NuclideModelPtr LumpedNuclide::copy (const NuclideModel & src) virtual
copies a nuclide model and its parameters from another
Parameters:
src is the nuclide model being copied
Implements NuclideModel.
Definition at line 102 of file LumpedNuclide.cpp.
References NuclideModel::conc_hist_, formulation(), NuclideModel::geom(), NuclideModel::geom_, Pe(), porosity(), set_C_0(), set_formulation(), NuclideModel::set_geom(), NuclideModel::set_last_updated(), set_Pe(), set_porosity(), t_t(), t_t_, v(), v_, NuclideModel::vec_hist_, and NuclideModel::wastes_.
static LumpedNuclidePtr LumpedNuclide::create () inline static
A constructor for the Lumped Nuclide Model that returns a shared pointer.
Definition at line 74 of file LumpedNuclide.h.
References DM, and LumpedNuclide().
Referenced by LumpedNuclideTest::initNuclideModel(), LumpedNuclideModelConstructor(), NuclideModelFactory::nuclideModel(), LumpedNuclideTest::SetUp(), and TEST_F().
static LumpedNuclidePtr LumpedNuclide::create (QueryEngine * qe) inline static
A constructor for the Lumped Nuclide Model that returns a shared pointer.
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 81 of file LumpedNuclide.h.
References LumpedNuclide().
IsoConcMap LumpedNuclide::dirichlet_bc () virtual
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
Returns:
C the concentration at the boundary in kg/m^3 for each isotope
Implements NuclideModel.
Definition at line 199 of file LumpedNuclide.cpp.
References NuclideModel::conc_hist(), and NuclideModel::last_updated().
FormulationType LumpedNuclide::enumerateFormulation (std::string formulation)
Returns the FormulationType corresponding to the string.
Parameters:
the name of the formulation type (EXPM, PFM, DM, etc.)
Returns:
the formulation type corresponding to the string
Definition at line 249 of file LumpedNuclide.cpp.
References LAST_FORMULATION_TYPE, name(), and type().
Referenced by initModuleMembers(), and set_formulation().
mat_rsrc_ptr LumpedNuclide::extract (CompMapPtr comp_to_rem, double kg_to_rem) virtual
Extracts the contents of the given Material from this NuclideModel.
Use this function for decrementing a NuclideModel's mass balance after transferring through a link.
Parameters:
comp_to_rem the composition to decrement against this LumpedNuclide
comp_to_rem the mass in kg to decrement against this LumpedNuclide
Returns:
the material extracted
Implements NuclideModel.
Definition at line 158 of file LumpedNuclide.cpp.
References MatTools::extract(), NuclideModel::last_updated(), update(), and NuclideModel::wastes_.
mat_rsrc_ptr LumpedNuclide::extractIntegratedMass (NuclideModelPtr daughter, double the_time)
Extracts one timestep's mass from the daughter nuclidemodel.
Parameters:
daughter the nuclide model from which to extract mass
the_time the current time [months].
Returns:
the material that has been extracted from daughter
Definition at line 454 of file LumpedNuclide.cpp.
References MatTools::addConcMaps(), C_0(), C_t(), MatTools::conc_to_comp_map(), NuclideModel::geom(), porosity(), and MatTools::scaleConcMap().
Referenced by update_inner_bc().
const FormulationType LumpedNuclide::formulation () const inline
Returns the formulation of the concentration relationship.
Definition at line 192 of file LumpedNuclide.h.
References formulation_.
Referenced by copy(), and set_formulation().
void LumpedNuclide::initModuleMembers (QueryEngine * qe) virtual
initializes the model parameters from an QueryEngine object
Parameters:
qe is the QueryEngine object containing intialization info
Implements NuclideModel.
Definition at line 59 of file LumpedNuclide.cpp.
References DM, enumerateFormulation(), EXPM, formulation_, Pe_, PFM, porosity_, t_t_, and v_.
Referenced by LumpedNuclide().
virtual std::string LumpedNuclide::name () inline virtual
Returns the nuclide model type name.
Implements NuclideModel.
Definition at line 142 of file LumpedNuclide.h.
Referenced by enumerateFormulation().
ConcGradMap LumpedNuclide::neumann_bc (IsoConcMap c_ext, Radius r_ext) virtual
returns the concentration gradient at the boundary, the Neumann bc
Returns:
dCdx the concentration gradient at the boundary in kg/m^3
Implements NuclideModel.
Definition at line 204 of file LumpedNuclide.cpp.
References NuclideModel::calc_conc_grad(), NuclideModel::conc_hist(), NuclideModel::geom(), and NuclideModel::last_updated().
Referenced by cauchy_bc().
const double LumpedNuclide::Pe () const inline
Returns the peclet number of the component [-].
Definition at line 217 of file LumpedNuclide.h.
References Pe_.
Referenced by C_DM(), copy(), set_Pe(), and updateNuclideParamsTable().
const double LumpedNuclide::porosity () const inline
The porosity of the permeable porous mediuam of this component. [%].
Definition at line 228 of file LumpedNuclide.h.
References porosity_.
Referenced by copy(), extractIntegratedMass(), set_porosity(), updateNuclideParamsTable(), V_f(), and V_s().
void LumpedNuclide::print () virtual
standard verbose printer includes current temp and concentrations
Implements NuclideModel.
Definition at line 143 of file LumpedNuclide.cpp.
void LumpedNuclide::set_C_0 (IsoConcMap C_0) inline
Sets the internal boundary condition.
Definition at line 202 of file LumpedNuclide.h.
References C_0(), and C_0_.
Referenced by copy(), and update_inner_bc().
void LumpedNuclide::set_formulation (std::string formulation) inline
Sets the formulation of the concentration relationship.
Definition at line 205 of file LumpedNuclide.h.
References enumerateFormulation(), and formulation_.
Referenced by copy().
void LumpedNuclide::set_formulation (FormulationType formulation) inline
Sets the formulation of the concentration relationship.
Definition at line 208 of file LumpedNuclide.h.
References formulation(), and formulation_.
void LumpedNuclide::set_Pe (double Pe)
Sets the peclet_ variable, the ratio of advective to diffusive transport.
Definition at line 273 of file LumpedNuclide.cpp.
References Pe(), Pe_, and MatTools::validate_finite_pos().
Referenced by copy().
void LumpedNuclide::set_porosity (double porosity)
Sets the porosity_ variable, the percent of the permeable porous medium.
Definition at line 292 of file LumpedNuclide.cpp.
References porosity(), porosity_, and MatTools::validate_percent().
Referenced by copy().
pair< IsoVector, double > LumpedNuclide::source_term_bc () virtual
returns the available material source term at the outer boundary of the component
Returns:
the IsoVector and mass defining the outer boundary condition
Implements NuclideModel.
Definition at line 184 of file LumpedNuclide.cpp.
References NuclideModel::conc_hist(), NuclideModel::last_updated(), MatTools::scaleConcMap(), and V_f().
const double LumpedNuclide::t_t () const inline
Returns the transit time through the component [-].
Definition at line 220 of file LumpedNuclide.h.
References t_t_.
Referenced by C_DM(), C_EXPM(), C_PFM(), copy(), and updateNuclideParamsTable().
void LumpedNuclide::transportNuclides (int time) virtual
Transports nuclides from the inner to the outer boundary.
Parameters:
time the timestep at which to transport the nuclides
Implements NuclideModel.
Definition at line 172 of file LumpedNuclide.cpp.
References update().
virtual NuclideModelType LumpedNuclide::type () inline virtual
Returns the nuclide model type.
Implements NuclideModel.
Definition at line 137 of file LumpedNuclide.h.
References LUMPED_NUCLIDE.
Referenced by enumerateFormulation().
void LumpedNuclide::update (int the_time) virtual
Updates all the hists.
Parameters:
the_time the time at which to update the history
Implements NuclideModel.
Definition at line 135 of file LumpedNuclide.cpp.
References NuclideModel::last_updated(), NuclideModel::set_last_updated(), update_conc_hist(), and update_vec_hist().
Referenced by extract(), and transportNuclides().
void LumpedNuclide::update_conc_hist (int the_time)
Updates the available concentration using the wastes_ as mats.
Parameters:
the_time the time at which to update the IsoConcMap
Definition at line 392 of file LumpedNuclide.cpp.
References NuclideModel::wastes_.
Referenced by update().
void LumpedNuclide::update_conc_hist (int the_time, std::deque< mat_rsrc_ptr > mats)
Updates the available concentration.
Parameters:
the_time the time at which to update the IsoConcMap
mats the materials that are part of the available concentration
void LumpedNuclide::update_inner_bc (int the_time, std::vector< NuclideModelPtr > daughters) virtual
Determines what IsoVector to remove from the daughter nuclide models.
Parameters:
time the timestep at which the nuclides should be transported
daughter nuclide_model of an internal component. there may be many.
Implements NuclideModel.
Definition at line 419 of file LumpedNuclide.cpp.
References absorb(), C_0(), MatTools::comp_to_conc_map(), extractIntegratedMass(), and set_C_0().
void LumpedNuclide::update_vec_hist (int the_time)
Updates the contained vector.
Parameters:
the_time the time at which to update the vector
Definition at line 414 of file LumpedNuclide.cpp.
References MatTools::sum_mats(), NuclideModel::vec_hist_, and NuclideModel::wastes_.
Referenced by update().
void LumpedNuclide::updateNuclideParamsTable () virtual
Updates the NuclideParams table by adding appropriate rows to describe the parameters initializing this NuclideModel.
Implements NuclideModel.
Definition at line 124 of file LumpedNuclide.cpp.
References NuclideModel::mat_table_, Pe(), porosity(), t_t(), and v().
const double LumpedNuclide::v () const inline
The advective velocity through this component.
[m/s]
Definition at line 225 of file LumpedNuclide.h.
References v_.
Referenced by cauchy_bc(), copy(), and updateNuclideParamsTable().
double LumpedNuclide::V_f ()
Gets the fluid volume, based on porosity.
Definition at line 313 of file LumpedNuclide.cpp.
References porosity(), and V_T().
Referenced by source_term_bc(), and V_ff().
double LumpedNuclide::V_ff () virtual
Gets the free fluid volume. Same as V_f (no sorption or solubility)
Implements NuclideModel.
Definition at line 309 of file LumpedNuclide.cpp.
References V_f().
double LumpedNuclide::V_s ()
Gets the fluid volume, based on porosity.
Definition at line 317 of file LumpedNuclide.cpp.
References porosity(), and V_T().
double LumpedNuclide::V_T () virtual
Gets the total volume.
Implements NuclideModel.
Definition at line 322 of file LumpedNuclide.cpp.
References NuclideModel::geom_.
Referenced by V_f(), and V_s().
Member Data Documentation
IsoConcMap LumpedNuclide::C_0_ protected
the current conc map at the inner boundary
Definition at line 342 of file LumpedNuclide.h.
Referenced by C_0(), LumpedNuclide(), and set_C_0().
FormulationType LumpedNuclide::formulation_ protected
The name of the lumped parameter model formulation.
This can be the Exponential Model (EXPM), Piston Flow Model (PFM), or the Dispersion Model(DM).
Definition at line 330 of file LumpedNuclide.h.
Referenced by C_t(), formulation(), initModuleMembers(), and set_formulation().
double LumpedNuclide::Pe_ protected
The dimensionless mass diffusion Peclet number of the medium [-].
Definition at line 336 of file LumpedNuclide.h.
Referenced by initModuleMembers(), LumpedNuclide(), Pe(), and set_Pe().
double LumpedNuclide::porosity_ protected
The porosity of the permeable porous medium.
Definition at line 339 of file LumpedNuclide.h.
Referenced by initModuleMembers(), porosity(), and set_porosity().
double LumpedNuclide::t_t_ protected
The transit time of a radioactive tracer through the cell.
Definition at line 333 of file LumpedNuclide.h.
Referenced by copy(), initModuleMembers(), and t_t().
double LumpedNuclide::v_ protected
The advective velocity through this component [m/s].
Definition at line 324 of file LumpedNuclide.h.
Referenced by copy(), initModuleMembers(), and v().
The documentation for this class was generated from the following files:
LumpedNuclide.h
LumpedNuclide.cpp