cyder: SolLim Class Reference
SolLim Class Reference
SolLim is a toolkit for manipulating materials under solubility limited conditions.
#include <SolLim.h>
Static Public Member Functions
static double m_aff (double m_ff, double V_ff, double C_sol)
Returns m_aff the available contaminant mass in the free fluid volume [kg].
static double m_ds (double m_T, double K_d, double V_s, double V_f, double d)
Returns m_ds the contaminant mass in the degraded solid [kg].
static double m_f (double m_T, double K_d, double V_s, double V_f)
Returns m_f the contaminant mass in the fluid volume [kg].
static double m_ff (double m_T, double K_d, double V_s, double V_f, double d)
Returns m_ff the contaminant mass in the free fluid volume [kg].
static double m_mf (double m_T, double K_d, double V_s, double V_f, double d)
Returns m_mf the contaminant mass in the matrix pore fluid volume [kg].
static double m_ms (double m_T, double K_d, double V_s, double V_f, double d)
Returns m_ms the mass in the intact matrix solid volume [kg].
static double m_ps (double m_T, double K_d, double V_s, double V_f, double d, double C_sol)
Returns m_ps the contaminant mass that has precipitated into a solid form [kg].
static double m_s (double m_T, double K_d, double V_s, double V_f)
Returns m_s the mass in the solid volume[kg].
Detailed Description
SolLim is a toolkit for manipulating materials under solubility limited conditions.
Definition at line 22 of file SolLim.h.
Member Function Documentation
double SolLim::m_aff (double m_ff, double V_ff, double C_sol) static
Returns m_aff the available contaminant mass in the free fluid volume [kg].
Parameters:
m_ff the contaminant mass int he free fluid volume [kg]
V_ff the free fluid volume [m^3]
C_sol the solubility limit of the element e [kg/m^3]
Returns:
m_aff the available contaminant mass in the free fluid volume [kg]
Definition at line 53 of file SolLim.cpp.
Referenced by MixedCellNuclide::precipitate(), and TEST_F().
double SolLim::m_ds (double m_T, double K_d, double V_s, double V_f, double d) static
Returns m_ds the contaminant mass in the degraded solid [kg].
Parameters:
m_T the total mass of the element e
K_d the distribution coefficient [m^3/kg]
V_s the solid volume [m^3]
V_f the fluid volume [m^3]
d the amount this component has degraded (a fraction)
Returns:
m_ds the contaminant mass in the degraded solid [kg]
Definition at line 37 of file SolLim.cpp.
Referenced by TEST_F().
double SolLim::m_f (double m_T, double K_d, double V_s, double V_f) static
Returns m_f the contaminant mass in the fluid volume [kg].
Parameters:
m_T the total mass of the element e
K_d the distribution coefficient [m^3/kg]
V_s the solid volume [m^3]
V_f the fluid volume [m^3]
Returns:
m_f the contaminant mass in the fluid volume [kg]
Definition at line 18 of file SolLim.cpp.
Referenced by TEST_F().
double SolLim::m_ff (double m_T, double K_d, double V_s, double V_f, double d) static
Returns m_ff the contaminant mass in the free fluid volume [kg].
Parameters:
m_T the total mass of the element e
K_d the distribution coefficient [m^3/kg]
V_s the solid volume [m^3]
V_f the fluid volume [m^3]
d the amount this component has degraded (a fraction)
Returns:
m_ff the contaminant mass in the free fluid volume [kg]
Definition at line 45 of file SolLim.cpp.
Referenced by MixedCellNuclide::sorb(), and TEST_F().
double SolLim::m_mf (double m_T, double K_d, double V_s, double V_f, double d) static
Returns m_mf the contaminant mass in the matrix pore fluid volume [kg].
Parameters:
m_T the total mass of the element e
K_d the distribution coefficient [m^3/kg]
V_s the solid volume [m^3]
V_f the fluid volume [m^3]
d the amount this component has degraded (a fraction)
Returns:
m_mf the contaminant mass in the matrix pore fluid volume [kg]
Definition at line 49 of file SolLim.cpp.
Referenced by TEST_F().
double SolLim::m_ms (double m_T, double K_d, double V_s, double V_f, double d) static
Returns m_ms the mass in the intact matrix solid volume [kg].
Parameters:
m_T the total mass of the element e
K_d the distribution coefficient [m^3/kg]
V_s the solid volume [m^3]
V_f the fluid volume [m^3]
d the amount this component has degraded (a fraction)
Returns:
m_ms the mass in the intact matrix solid volume [kg]
Definition at line 41 of file SolLim.cpp.
Referenced by TEST_F().
double SolLim::m_ps (double m_T, double K_d, double V_s, double V_f, double d, double C_sol) static
Returns m_ps the contaminant mass that has precipitated into a solid form [kg].
Parameters:
m_T the total mass of the element e
K_d the distribution coefficient [m^3/kg]
V_s the solid volume [m^3]
V_f the fluid volume [m^3]
d the amount this component has degraded (a fraction)
C_sol the solubility limit of the element e [kg/m^3]
Returns:
m_ps the contaminant mass that has precipitated into a solid form [kg]
Definition at line 57 of file SolLim.cpp.
Referenced by TEST_F().
double SolLim::m_s (double m_T, double K_d, double V_s, double V_f) static
Returns m_s the mass in the solid volume[kg].
Parameters:
m_T the total mass of the element e
K_d the distribution coefficient [m^3/kg]
V_s the solid volume [m^3]
V_f the fluid volume [m^3]
Returns:
m_s the contaminant mass in the solid volume[kg]
Definition at line 28 of file SolLim.cpp.
Referenced by TEST_F().
The documentation for this class was generated from the following files:
SolLim.h
SolLim.cpp