cyder: StubThermal Class Reference
StubThermal Class Reference
StubThermal is a skeleton component model that does nothing.
#include <StubThermal.h>
Public Member Functions
virtual void copy (const ThermalModel &src)
copies a component and its parameters from another
virtual void initModuleMembers (QueryEngine *qe)
initializes the model parameters from an xmlNodePtr
virtual bool mat_acceptable (mat_rsrc_ptr mat, Radius r_lim, Temp t_lim)
This function says whether or not the material is acceptable to this repository at r_lim for the limit t_lim.
virtual std::string name ()
return the thermal model implementation type
virtual Temp peak_temp ()
gets the peak temperature that this component will experience on the boundary
virtual void print ()
standard verbose printer includes current temp and concentrations
StubThermal ()
Default constructor for the component class.
StubThermal (QueryEngine *qe)
primary constructor reads input from XML node
virtual Temp temp ()
gets the temperature average in the component
virtual void transportHeat (int time)
transports the heat
virtual const ThermalModelType type ()
return the thermal model implementation type
~StubThermal ()
Default destructor does nothing.
Public Member Functions inherited from ThermalModel
GeometryPtr geom ()
void set_geom (GeometryPtr geom)
set the geometry shared pointer
void set_mat_table (MatDataTablePtr mat_table)
set the MatDataTablePtr shared pointer
virtual ~ThermalModel ()
A virtual destructor.
Static Public Member Functions
static StubThermalPtr create ()
A constructor for the Lumped Nuclide Model that returns a shared pointer.
static StubThermalPtr create (QueryEngine *qe)
A constructor for the Lumped Nuclide Model that returns a shared pointer.
Additional Inherited Members
Protected Attributes inherited from ThermalModel
GeometryPtr geom_
A shared pointer to the geometry of this component.
MatDataTablePtr mat_table_
A shared pointer to the MatDataTablePtr representing the material of this component.
TempHist temp_hist_
The temperature history of this component.
Temp temperature_
The temperature of this component, on average.
Detailed Description
StubThermal is a skeleton component model that does nothing.
This disposal system component will do nothing. This Component is intended as a skeleton to guide the implementation of new Components.
The StubThermal model can be used to represent components of the disposal system such as the Waste Form, Waste Package, Buffer, Near Field, Far Field, and Envrionment.
Definition at line 28 of file StubThermal.h.
Constructor & Destructor Documentation
StubThermal::StubThermal () inline
Default constructor for the component class.
Creates an empty component.
Definition at line 34 of file StubThermal.h.
Referenced by create().
StubThermal::StubThermal (QueryEngine * qe) inline
primary constructor reads input from XML node
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 41 of file StubThermal.h.
StubThermal::~StubThermal () inline
Default destructor does nothing.
Definition at line 46 of file StubThermal.h.
Member Function Documentation
void StubThermal::copy (const ThermalModel & src) virtual
copies a component and its parameters from another
Parameters:
src is the component being copied
Implements ThermalModel.
Definition at line 24 of file StubThermal.cpp.
static StubThermalPtr StubThermal::create () inline static
A constructor for the Lumped Nuclide Model that returns a shared pointer.
Definition at line 51 of file StubThermal.h.
References StubThermal().
Referenced by ComponentTest::SetUp(), and ThermalModelFactory::thermalModel().
static StubThermalPtr StubThermal::create (QueryEngine * qe) inline static
A constructor for the Lumped Nuclide Model that returns a shared pointer.
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 58 of file StubThermal.h.
References StubThermal().
void StubThermal::initModuleMembers (QueryEngine * qe) virtual
initializes the model parameters from an xmlNodePtr
Parameters:
qe is the QueryEngine object containing intialization info
Implements ThermalModel.
Definition at line 18 of file StubThermal.cpp.
bool StubThermal::mat_acceptable (mat_rsrc_ptr mat, Radius r_lim, Temp t_lim) virtual
This function says whether or not the material is acceptable to this repository at r_lim for the limit t_lim.
Parameters:
mat the material whose whose contribution to query
r_lim the limiting radius
t_lim the limiting temperature
Returns:
mat_acceptable (true when acceptable, false otherwise)
obviously, put some logic here.
Implements ThermalModel.
Definition at line 47 of file StubThermal.cpp.
virtual std::string StubThermal::name () inline virtual
return the thermal model implementation type
Returns:
impl_name_ the name of the ThermalModel implementation
Implements ThermalModel.
Definition at line 98 of file StubThermal.h.
Temp StubThermal::peak_temp () virtual
gets the peak temperature that this component will experience on the boundary
this is a placeholder!!! deal with it.
Implements ThermalModel.
Definition at line 39 of file StubThermal.cpp.
void StubThermal::print () virtual
standard verbose printer includes current temp and concentrations
Implements ThermalModel.
Definition at line 28 of file StubThermal.cpp.
Temp StubThermal::temp () virtual
gets the temperature average in the component
Implements ThermalModel.
Definition at line 53 of file StubThermal.cpp.
void StubThermal::transportHeat (int time) virtual
transports the heat
Parameters:
time the timestep at which to transport the heat
Implements ThermalModel.
Definition at line 33 of file StubThermal.cpp.
virtual const ThermalModelType StubThermal::type () inline virtual
return the thermal model implementation type
Returns:
impl_name_ the name of the ThermalModel implementation
Implements ThermalModel.
Definition at line 91 of file StubThermal.h.
References STUB_THERMAL.
The documentation for this class was generated from the following files:
StubThermal.h
StubThermal.cpp