cyder: MatDataTable Class Reference
MatDataTable Class Reference
The MatDataTable class provides an interface to the mat_data.sqlite database, providing a robust and correct mass lookup by isotope.
#include <MatDataTable.h>
Public Member Functions
double D (Elem ent)
get the dispersion coefficient [kg/m^2/s] for some element in this material
double data (Elem ent, ChemDataType data)
gets a specific data object for some element in this material.
double K_d (Elem ent)
get the distribution coefficient [kg/kg] for some element in this material
std::string mat ()
returns the string name of the material that this table represents
MatDataTable ()
Default constructor for the MatDataTable class.
MatDataTable (std::string mat, std::vector< element_t > elem_vec, std::map< Elem, int > elem_index, double ref_disp=NULL, double ref_kd=NULL, double ref_sol=NULL)
Detailed constructor for the MatDataTable class Fully initializes the object.
double ref (ChemDataType data)
Returns the reference paramter supplied by the user.
double ref_disp ()
double ref_kd ()
double ref_sol ()
double rel (Elem ent, ChemDataType data)
The reference chemical data parameter for the reference element, Hydrogen.
double S (Elem ent)
get the solubility limit for some element in this material
~MatDataTable ()
Destructor for the NullFacility class.
Protected Member Functions
void check_validity (Elem ent)
checks whether this element has a row entry in the table.
Protected Attributes
std::map< Elem, int > elem_index_
a map for index lookup in the element vector.
int elem_len_
The integer length (number of rows) of the tables.
std::vector< element_t > elem_vec_
The vector of element structs that holds the data in the mass table.
bool initialized_
This is true if the MatDataTable has been initialized with real data.
std::string mat_
The material that this table represents, specifically, the name of the table in the DB.
double ref_disp_
The reference dispersion coefficient.
double ref_kd_
The reference K_d coefficient.
double ref_sol_
The reference solubility limit.
Detailed Description
The MatDataTable class provides an interface to the mat_data.sqlite database, providing a robust and correct mass lookup by isotope.
Definition at line 38 of file MatDataTable.h.
Constructor & Destructor Documentation
MatDataTable::MatDataTable ()
Default constructor for the MatDataTable class.
Default values are zeros and null strings
Definition at line 16 of file MatDataTable.cpp.
MatDataTable::MatDataTable (std::string mat, std::vector< element_t > elem_vec, std::map< Elem, int > elem_index, double ref_disp = NULL, double ref_kd = NULL, double ref_sol = NULL)
Detailed constructor for the MatDataTable class Fully initializes the object.
Parameters:
mat the mat_ data member, a string
elem_vec the elem_vec_ data member, a vector of element structs, the data
elem_index the elem_index_ data member, mapping the element IDs to indices
ref_disp is the reference dispersion coefficient
ref_kd is the reference kd coefficient
ref_sol is the reference solubility limit
MatDataTable::~MatDataTable ()
Destructor for the NullFacility class.
Makes certain to delete all appropriate data on the stack.
Definition at line 38 of file MatDataTable.cpp.
Member Function Documentation
void MatDataTable::check_validity (Elem ent) protected
checks whether this element has a row entry in the table.
ideally all of them will...
Exceptions:
CycException when theres some drama
Definition at line 60 of file MatDataTable.cpp.
References elem_index_.
Referenced by D(), K_d(), and S().
double MatDataTable::D (Elem ent)
get the dispersion coefficient [kg/m^2/s] for some element in this material
Parameters:
ent an identifier of type Elem, which is an int
Returns:
D a double, the dispersion coefficient [kg/m^2/s] for the element ent in the material mat.
Definition at line 54 of file MatDataTable.cpp.
References check_validity(), data(), and DISP.
double MatDataTable::data (Elem ent, ChemDataType data)
gets a specific data object for some element in this material.
Parameters:
ent an identifier of type Elem, which is an int
data is a ChemDataType enum (DISP, KD, SOL, ...)
Returns:
the data of type data for element elt in this material.
Definition at line 71 of file MatDataTable.cpp.
References DISP, KD, ref(), rel(), and SOL.
Referenced by D(), K_d(), and S().
double MatDataTable::K_d (Elem ent)
get the distribution coefficient [kg/kg] for some element in this material
Parameters:
ent an identifier of type Elem, which is an int
Returns:
K_d a double, the distribution coefficient [kg/kg] for the element ent in the material mat.
Definition at line 42 of file MatDataTable.cpp.
References check_validity(), data(), and KD.
std::string MatDataTable::mat () inline
returns the string name of the material that this table represents
Returns:
mat_
Definition at line 116 of file MatDataTable.h.
References mat_.
double MatDataTable::ref (ChemDataType data)
Returns the reference paramter supplied by the user.
That is, in the case of data=DISP, the reference dispersion coefficient that the user has supplied for the reference element, Hydrogen is returned.
Parameters:
data is a ChemDataType enum (DISP, KD, SOL, ...)
Definition at line 112 of file MatDataTable.cpp.
References DISP, elem_index_, elem_vec_, initialized_, KD, ref_disp_, ref_kd_, ref_sol_, and SOL.
Referenced by data().
double MatDataTable::ref_disp () inline
Definition at line 117 of file MatDataTable.h.
References initialized_, and ref_disp_.
double MatDataTable::ref_kd () inline
Definition at line 118 of file MatDataTable.h.
References initialized_, and ref_kd_.
double MatDataTable::ref_sol () inline
Definition at line 119 of file MatDataTable.h.
References initialized_, and ref_sol_.
double MatDataTable::rel (Elem ent, ChemDataType data)
The reference chemical data parameter for the reference element, Hydrogen.
In the case of data=DISP, this is the dispersion coefficient for the reference element, Hydrogen. The amount by which D(element) differs from D(hydrogen) is its relative diffusivity. That is returned with this function.
Parameters:
ent an identifier of type Elem, the element for which to return the rel_D
data is a ChemDataType enum (DISP, KD, SOL, ...)
Definition at line 90 of file MatDataTable.cpp.
References DISP, elem_index_, elem_vec_, KD, and SOL.
Referenced by data().
double MatDataTable::S (Elem ent)
get the solubility limit for some element in this material
Parameters:
ent an identifier of type Elem, which is an int
Returns:
S a double, the solubility limit [kg/m^3] for the element ent in the material mat.
Definition at line 48 of file MatDataTable.cpp.
References check_validity(), data(), and SOL.
Member Data Documentation
std::map<Elem, int> MatDataTable::elem_index_ protected
a map for index lookup in the element vector.
Definition at line 170 of file MatDataTable.h.
Referenced by check_validity(), ref(), and rel().
int MatDataTable::elem_len_ protected
The integer length (number of rows) of the tables.
Definition at line 160 of file MatDataTable.h.
std::vector<element_t> MatDataTable::elem_vec_ protected
The vector of element structs that holds the data in the mass table.
Definition at line 165 of file MatDataTable.h.
Referenced by ref(), and rel().
bool MatDataTable::initialized_ protected
This is true if the MatDataTable has been initialized with real data.
Definition at line 182 of file MatDataTable.h.
Referenced by ref(), ref_disp(), ref_kd(), and ref_sol().
std::string MatDataTable::mat_ protected
The material that this table represents, specifically, the name of the table in the DB.
Definition at line 155 of file MatDataTable.h.
Referenced by mat().
double MatDataTable::ref_disp_ protected
The reference dispersion coefficient.
Definition at line 173 of file MatDataTable.h.
Referenced by ref(), and ref_disp().
double MatDataTable::ref_kd_ protected
The reference K_d coefficient.
Definition at line 176 of file MatDataTable.h.
Referenced by ref(), and ref_kd().
double MatDataTable::ref_sol_ protected
The reference solubility limit.
Definition at line 179 of file MatDataTable.h.
Referenced by ref(), and ref_sol().
The documentation for this class was generated from the following files:
MatDataTable.h
MatDataTable.cpp