cyder: STCDB Class Reference
STCDB Class Reference
The STCDB class provides an interface to the stc_data.sqlite database, providing a robust and correct mass lookup by isotope.
#include <STCDB.h>
Public Member Functions
std::vector< double > alpha_th_range (SqliteDb *db)
Returns a vector of distinct values of alpha_th in the db.
bool initialized (std::string mat)
checks whether a table associated with a particular mat has been created
STCDataTablePtr initializeFromSQL (th_params_t th_params)
a function to initialize a large array of element_t structs via the SQLite/C++ API
const std::map< Iso, int > iso_index (SqliteDb *db, std::string table_name) const
This returns the iso_index_ for a particular db and mat struct.
std::vector< double > k_th_range (SqliteDb *db)
Returns a vector of distinct values of k_th in the db.
const std::string mat_name (th_params_t th_params) const
Converts the th_params struct into a coded name.
std::vector< double > r_calc_range (SqliteDb *db)
Returns a vector of distinct values of r_calc in the db.
std::vector< double > spacing_range (SqliteDb *db)
Returns a vector of distinct values of spacing in the db.
double stc (th_params_t th_params, Iso tope, int the_time)
Returns the stc for the material and isotope requested.
boost::multi_array< double, 2 > stc_array (SqliteDb *db, th_params_t th_params)
This returns the stc_array_ for a particular db and mat struct.
STCDB ()
Default constructor for the STCDB class.
STCDataTablePtr table (th_params_t th_params)
returns the table matching the mat string.
std::string table_id (SqliteDb *db, th_params_t th_params)
Finds the name of the table in the database for the mat struct .
const std::map< int, int > time_index (SqliteDb *db, std::string table_name) const
This returns the time_index for a particular db and mat struct.
std::string whereClause (th_params_t th_params)
this helper function provides the WHERE clause that selects the mat from the db.
~STCDB ()
Destructor for the NullFacility class.
Static Public Member Functions
static STCDB * Instance ()
Provides a singleton instance for the STCDB.
Protected Member Functions
const std::map< int, int > getIndex (std::vector< StrList >) const
Returns a map from values to indices of the query result.
std::vector< double > getRange (std::vector< StrList > vals)
Returns a vector of distinct values of the query result.
Protected Attributes
std::vector< double > alpha_th_range_
Returns a vector of distinct values of alpha_th in the db.
std::vector< double > k_th_range_
Returns a vector of distinct values of k_th in the db.
std::vector< double > r_calc_range_
Returns a vector of distinct values of r_calc in the db.
std::vector< double > spacing_range_
Returns a vector of distinct values of spcacing in the db.
std::map< std::string,
STCDataTablePtr > tables_
a mat from the names of the tables to the table pointers
Private Attributes
std::string file_path_
this database's file path
Static Private Attributes
static STCDB * instance_ = 0
A pointer to this STCDB once it has been initialized.
Detailed Description
The STCDB class provides an interface to the stc_data.sqlite database, providing a robust and correct mass lookup by isotope.
Definition at line 18 of file STCDB.h.
Constructor & Destructor Documentation
STCDB::STCDB ()
Default constructor for the STCDB class.
Initializes the data from the provided mat_data.sqlite file.
Definition at line 28 of file STCDB.cpp.
STCDB::~STCDB ()
Destructor for the NullFacility class.
Makes certain to delete all appropriate data on the stack.
Definition at line 33 of file STCDB.cpp.
References instance_.
Member Function Documentation
vector< double > STCDB::alpha_th_range (SqliteDb * db)
Returns a vector of distinct values of alpha_th in the db.
Parameters:
db the database to look into
Returns:
alpha_th_range_
Definition at line 190 of file STCDB.cpp.
References alpha_th_range_, and getRange().
const map< int, int > STCDB::getIndex (std::vector< StrList >) const protected
Returns a map from values to indices of the query result.
Definition at line 108 of file STCDB.cpp.
Referenced by iso_index(), and time_index().
vector< double > STCDB::getRange (std::vector< StrList > vals) protected
Returns a vector of distinct values of the query result.
Definition at line 121 of file STCDB.cpp.
Referenced by alpha_th_range(), k_th_range(), r_calc_range(), and spacing_range().
bool STCDB::initialized (std::string mat)
checks whether a table associated with a particular mat has been created
Parameters:
mat the string name of the table to check the existence of
Definition at line 56 of file STCDB.cpp.
References tables_.
Referenced by table().
STCDataTablePtr STCDB::initializeFromSQL (th_params_t th_params)
a function to initialize a large array of element_t structs via the SQLite/C++ API
Parameters:
mat the string indicatin the material this table should represent
Definition at line 73 of file STCDB.cpp.
References file_path_, iso_index(), mat_name(), stc_array(), table_id(), and time_index().
Referenced by table().
STCDB * STCDB::Instance () static
Provides a singleton instance for the STCDB.
Like the Highlander, there should be only one.
Returns:
a pointer to the STCDB
Definition at line 18 of file STCDB.cpp.
const map< Iso, int > STCDB::iso_index (SqliteDb * db, std::string table_name) const
This returns the iso_index_ for a particular db and mat struct.
iso_index_ is a map from isotope IDs to indexes in the stc_vec_
Parameters:
db the database to query
table_name the name of the table to query
Definition at line 95 of file STCDB.cpp.
References getIndex().
Referenced by initializeFromSQL(), and stc_array().
vector< double > STCDB::k_th_range (SqliteDb * db)
Returns a vector of distinct values of k_th in the db.
Parameters:
db the database to look into
Returns:
k_th_range_
Definition at line 182 of file STCDB.cpp.
References getRange(), and k_th_range_.
const string STCDB::mat_name (th_params_t th_params) const
Converts the th_params struct into a coded name.
Parameters:
mat the struct describing a material
Definition at line 63 of file STCDB.cpp.
References th_params_t::alpha_th, th_params_t::k_th, th_params_t::r_calc, and th_params_t::spacing.
Referenced by initializeFromSQL(), and table().
vector< double > STCDB::r_calc_range (SqliteDb * db)
Returns a vector of distinct values of r_calc in the db.
Parameters:
db the database to look into
Returns:
r_calc_range_
Definition at line 206 of file STCDB.cpp.
References getRange(), and r_calc_range_.
vector< double > STCDB::spacing_range (SqliteDb * db)
Returns a vector of distinct values of spacing in the db.
Parameters:
db the database to look into
Returns:
spacing_range_
Definition at line 198 of file STCDB.cpp.
References getRange(), and spacing_range_.
double STCDB::stc (th_params_t th_params, Iso tope, int the_time)
Returns the stc for the material and isotope requested.
If the table has not been created, this will create it.
Parameters:
mat a struct descriptor of the table
iso an isotope identifier of the isotope whose stc you're interested in
the_time the time at which to query the stc
Definition at line 38 of file STCDB.cpp.
References table().
boost::multi_array< double, 2 > STCDB::stc_array (SqliteDb * db, th_params_t th_params)
This returns the stc_array_ for a particular db and mat struct.
The stc_array holds stc values for specific isotope and time pairs. This is the main data in the table and has dimensions n_isos x n_timesteps.
Parameters:
db the database to query
mat the struct describing the material
Returns:
stc_array an array of stc values for specific isotope and time pairs.
Definition at line 153 of file STCDB.cpp.
References iso_index(), table_id(), and time_index().
Referenced by initializeFromSQL().
STCDataTablePtr STCDB::table (th_params_t th_params)
returns the table matching the mat string.
Parameters:
mat a struct indicating the variables in the table
Returns:
a STCDataTablePtr holding the data associated with the mat
Definition at line 43 of file STCDB.cpp.
References initialized(), initializeFromSQL(), mat_name(), and tables_.
Referenced by stc().
string STCDB::table_id (SqliteDb * db, th_params_t th_params)
Finds the name of the table in the database for the mat struct .
Parameters:
db the database to query
mat the struct describing a material
Definition at line 134 of file STCDB.cpp.
References th_params_t::alpha_th, th_params_t::k_th, th_params_t::r_calc, th_params_t::spacing, and whereClause().
Referenced by initializeFromSQL(), and stc_array().
const map< int, int > STCDB::time_index (SqliteDb * db, std::string table_name) const
This returns the time_index for a particular db and mat struct.
time_index is a map from timestep values to indexes in the stc_array
Parameters:
db the database to query
table_name the name of the table to query
Definition at line 102 of file STCDB.cpp.
References getIndex().
Referenced by initializeFromSQL(), and stc_array().
string STCDB::whereClause (th_params_t th_params)
this helper function provides the WHERE clause that selects the mat from the db.
Parameters:
mat the material properties to specify when querying the table.
Definition at line 85 of file STCDB.cpp.
References th_params_t::alpha_th, th_params_t::k_th, th_params_t::r_calc, and th_params_t::spacing.
Referenced by table_id().
Member Data Documentation
std::vector<double> STCDB::alpha_th_range_ protected
Returns a vector of distinct values of alpha_th in the db.
Definition at line 187 of file STCDB.h.
Referenced by alpha_th_range().
std::string STCDB::file_path_ private
this database's file path
Definition at line 28 of file STCDB.h.
Referenced by initializeFromSQL().
STCDB * STCDB::instance_ = 0 static private
A pointer to this STCDB once it has been initialized.
Definition at line 23 of file STCDB.h.
Referenced by ~STCDB().
std::vector<double> STCDB::k_th_range_ protected
Returns a vector of distinct values of k_th in the db.
Definition at line 184 of file STCDB.h.
Referenced by k_th_range().
std::vector<double> STCDB::r_calc_range_ protected
Returns a vector of distinct values of r_calc in the db.
Definition at line 193 of file STCDB.h.
Referenced by r_calc_range().
std::vector<double> STCDB::spacing_range_ protected
Returns a vector of distinct values of spcacing in the db.
Definition at line 190 of file STCDB.h.
Referenced by spacing_range().
std::map<std::string, STCDataTablePtr> STCDB::tables_ protected
a mat from the names of the tables to the table pointers
Definition at line 181 of file STCDB.h.
Referenced by initialized(), and table().
The documentation for this class was generated from the following files:
STCDB.h
STCDB.cpp