cyder: MixedCellNuclideTest Class Reference
MixedCellNuclideTest Class Reference
#include <MixedCellNuclideTests.h>
Protected Member Functions
MixedCellNuclidePtr initNuclideModel ()
virtual void SetUp ()
virtual void TearDown ()
Protected Attributes
double adv_vel_
int am241_
double D_
MixedCellNuclidePtr default_mixed_cell_ptr_
NuclideModelPtr default_nuc_model_ptr_
double deg_rate_
std::string false_str_
GeometryPtr geom_
bool kd_limited_
Length len_five_
MatDataTablePtr mat_table_
double mixed_cell_
MixedCellNuclidePtr mixed_cell_ptr_
NuclideModelPtr nuc_model_ptr_
int one_mol_
point_t origin_
double porosity_
Radius r_five_
Radius r_four_
bool sol_limited_
CompMapPtr test_comp_
mat_rsrc_ptr test_mat_
double test_size_
double theta_
int time_
int u235_
Elem u_
Detailed Description
Definition at line 10 of file MixedCellNuclideTests.h.
Member Function Documentation
MixedCellNuclidePtr MixedCellNuclideTest::initNuclideModel () protected
Definition at line 68 of file MixedCellNuclideTests.cpp.
References MixedCellNuclide::create().
void MixedCellNuclideTest::SetUp () protected virtual
Definition at line 16 of file MixedCellNuclideTests.cpp.
References MixedCellNuclide::create(), MDB, and NuclideModel::set_mat_table().
void MixedCellNuclideTest::TearDown () protected virtual
Definition at line 60 of file MixedCellNuclideTests.cpp.
Member Data Documentation
double MixedCellNuclideTest::adv_vel_ protected
Definition at line 26 of file MixedCellNuclideTests.h.
int MixedCellNuclideTest::am241_ protected
Definition at line 22 of file MixedCellNuclideTests.h.
double MixedCellNuclideTest::D_ protected
Definition at line 32 of file MixedCellNuclideTests.h.
MixedCellNuclidePtr MixedCellNuclideTest::default_mixed_cell_ptr_ protected
Definition at line 14 of file MixedCellNuclideTests.h.
NuclideModelPtr MixedCellNuclideTest::default_nuc_model_ptr_ protected
Definition at line 17 of file MixedCellNuclideTests.h.
double MixedCellNuclideTest::deg_rate_ protected
Definition at line 33 of file MixedCellNuclideTests.h.
std::string MixedCellNuclideTest::false_str_ protected
Definition at line 36 of file MixedCellNuclideTests.h.
GeometryPtr MixedCellNuclideTest::geom_ protected
Definition at line 27 of file MixedCellNuclideTests.h.
bool MixedCellNuclideTest::kd_limited_ protected
Definition at line 35 of file MixedCellNuclideTests.h.
Length MixedCellNuclideTest::len_five_ protected
Definition at line 29 of file MixedCellNuclideTests.h.
MatDataTablePtr MixedCellNuclideTest::mat_table_ protected
Definition at line 15 of file MixedCellNuclideTests.h.
double MixedCellNuclideTest::mixed_cell_ protected
Definition at line 18 of file MixedCellNuclideTests.h.
MixedCellNuclidePtr MixedCellNuclideTest::mixed_cell_ptr_ protected
Definition at line 13 of file MixedCellNuclideTests.h.
NuclideModelPtr MixedCellNuclideTest::nuc_model_ptr_ protected
Definition at line 16 of file MixedCellNuclideTests.h.
int MixedCellNuclideTest::one_mol_ protected
Definition at line 21 of file MixedCellNuclideTests.h.
point_t MixedCellNuclideTest::origin_ protected
Definition at line 30 of file MixedCellNuclideTests.h.
double MixedCellNuclideTest::porosity_ protected
Definition at line 32 of file MixedCellNuclideTests.h.
Radius MixedCellNuclideTest::r_five_ protected
Definition at line 28 of file MixedCellNuclideTests.h.
Radius MixedCellNuclideTest::r_four_ protected
Definition at line 28 of file MixedCellNuclideTests.h.
bool MixedCellNuclideTest::sol_limited_ protected
Definition at line 34 of file MixedCellNuclideTests.h.
CompMapPtr MixedCellNuclideTest::test_comp_ protected
Definition at line 19 of file MixedCellNuclideTests.h.
mat_rsrc_ptr MixedCellNuclideTest::test_mat_ protected
Definition at line 20 of file MixedCellNuclideTests.h.
double MixedCellNuclideTest::test_size_ protected
Definition at line 24 of file MixedCellNuclideTests.h.
double MixedCellNuclideTest::theta_ protected
Definition at line 25 of file MixedCellNuclideTests.h.
int MixedCellNuclideTest::time_ protected
Definition at line 31 of file MixedCellNuclideTests.h.
int MixedCellNuclideTest::u235_ protected
Definition at line 22 of file MixedCellNuclideTests.h.
Elem MixedCellNuclideTest::u_ protected
Definition at line 23 of file MixedCellNuclideTests.h.
The documentation for this class was generated from the following files:
MixedCellNuclideTests.h
MixedCellNuclideTests.cpp