cyder: ThermalModel Class Reference
ThermalModel Class Reference
Abstract interface for heat transport models to be used in the Cyder.
#include <ThermalModel.h>
Public Member Functions
virtual void copy (const ThermalModel &src)=0
copies a component and its parameters from another
GeometryPtr geom ()
virtual void initModuleMembers (QueryEngine *qe)=0
initializes the model parameters from an xmlNodePtr
virtual bool mat_acceptable (mat_rsrc_ptr mat, Radius r_lim, Temp t_lim)=0
This function says whether or not the material is acceptable to this repository at r_lim for the limit t_lim.
virtual std::string name ()=0
get the name of the thermal model implementation type
virtual Temp peak_temp ()=0
get the peak Temperature this object will experience during the simulation
virtual void print ()=0
standard verbose printer should include current temp and concentrations
void set_geom (GeometryPtr geom)
set the geometry shared pointer
void set_mat_table (MatDataTablePtr mat_table)
set the MatDataTablePtr shared pointer
virtual Temp temp ()=0
get the Temperature
virtual void transportHeat (int time)=0
transports the heat
virtual const ThermalModelType type ()=0
get the thermal model implementation type
virtual ~ThermalModel ()
A virtual destructor.
Protected Attributes
GeometryPtr geom_
A shared pointer to the geometry of this component.
MatDataTablePtr mat_table_
A shared pointer to the MatDataTablePtr representing the material of this component.
TempHist temp_hist_
The temperature history of this component.
Temp temperature_
The temperature of this component, on average.
Detailed Description
Abstract interface for heat transport models to be used in the Cyder.
ThermalModels such as Lumped, Stub etc, will share this virtual interface so that they can be interchanged within the Cyder.
Definition at line 49 of file ThermalModel.h.
Constructor & Destructor Documentation
virtual ThermalModel::~ThermalModel () inline virtual
A virtual destructor.
Definition at line 56 of file ThermalModel.h.
Member Function Documentation
virtual void ThermalModel::copy (const ThermalModel & src) pure virtual
copies a component and its parameters from another
Parameters:
src is the component being copied
Implemented in LumpedThermal, STCThermal, and StubThermal.
GeometryPtr ThermalModel::geom () inline
Definition at line 125 of file ThermalModel.h.
References geom_.
virtual void ThermalModel::initModuleMembers (QueryEngine * qe) pure virtual
initializes the model parameters from an xmlNodePtr
Parameters:
qe is the QueryEngine object containing intialization info
Implemented in LumpedThermal, STCThermal, and StubThermal.
virtual bool ThermalModel::mat_acceptable (mat_rsrc_ptr mat, Radius r_lim, Temp t_lim) pure virtual
This function says whether or not the material is acceptable to this repository at r_lim for the limit t_lim.
Parameters:
mat the material whose whose contribution to query
r_lim the limiting radius
t_lim the limiting temperature
Returns:
mat_acceptable (true when acceptable, false otherwise)
Implemented in STCThermal, LumpedThermal, and StubThermal.
virtual std::string ThermalModel::name () pure virtual
get the name of the thermal model implementation type
Implemented in STCThermal, LumpedThermal, and StubThermal.
virtual Temp ThermalModel::peak_temp () pure virtual
get the peak Temperature this object will experience during the simulation
Implemented in STCThermal, LumpedThermal, and StubThermal.
virtual void ThermalModel::print () pure virtual
standard verbose printer should include current temp and concentrations
Implemented in LumpedThermal, STCThermal, and StubThermal.
void ThermalModel::set_geom (GeometryPtr geom) inline
set the geometry shared pointer
Parameters:
geom the geometry of the component, a shared pointer
Definition at line 123 of file ThermalModel.h.
References geom_.
Referenced by STCThermal::copy(), and STCThermal::STCThermal().
void ThermalModel::set_mat_table (MatDataTablePtr mat_table) inline
set the MatDataTablePtr shared pointer
Parameters:
mat_table the matdatatableptr of of the component, a shared pointer
Definition at line 132 of file ThermalModel.h.
Referenced by STCThermalTest::SetUp().
virtual Temp ThermalModel::temp () pure virtual
get the Temperature
Returns:
temperature_
Implemented in STCThermal, LumpedThermal, and StubThermal.
virtual void ThermalModel::transportHeat (int time) pure virtual
transports the heat
Parameters:
time the timestep at which to transport the heat
Implemented in LumpedThermal, STCThermal, and StubThermal.
virtual const ThermalModelType ThermalModel::type () pure virtual
get the thermal model implementation type
Implemented in STCThermal, LumpedThermal, and StubThermal.
Member Data Documentation
GeometryPtr ThermalModel::geom_ protected
A shared pointer to the geometry of this component.
Definition at line 142 of file ThermalModel.h.
Referenced by geom(), and set_geom().
MatDataTablePtr ThermalModel::mat_table_ protected
A shared pointer to the MatDataTablePtr representing the material of this component.
Definition at line 145 of file ThermalModel.h.
TempHist ThermalModel::temp_hist_ protected
The temperature history of this component.
Definition at line 132 of file ThermalModel.h.
Referenced by STCThermal::peak_temp().
Temp ThermalModel::temperature_ protected
The temperature of this component, on average.
Definition at line 139 of file ThermalModel.h.
Referenced by STCThermal::temp().
The documentation for this class was generated from the following file:
ThermalModel.h