cyder: MatTools Class Reference
MatTools Class Reference
MatTools is a toolkit for manipulating materials.
#include <MatTools.h>
Static Public Member Functions
static CompMapPtr addCompMaps (CompMapPtr orig, CompMapPtr to_add)
add comments
static IsoConcMap addConcMaps (IsoConcMap orig, IsoConcMap to_add)
This is a helper function that returns the sum of two IsoConcMaps.
static IsoConcMap comp_to_conc_map (const CompMapPtr comp, double mass, double vol)
Converts a CompMap and associated total mass to an IsoConcMap for a Volume.
static std::pair< CompMapPtr,
double > conc_to_comp_map (const IsoConcMap conc, double vol)
Converts an IsoConcMap and Volume to CompMap and associated total mass.
static mat_rsrc_ptr extract (const CompMapPtr comp_to_rem, double kg_to_rem, std::deque< mat_rsrc_ptr > &mat_list)
removes the specified amount of the specified composition from a deque of materials provided to the function by reference.
static int isoToElem (int iso)
Converts a standard isoid into an element.
static std::vector< double > linspace (double a, double b, int n)
add comments
static IsoConcMap scaleConcMap (IsoConcMap C_0, double scalar)
This is a helper function that scales an IsoConcMap with a scalar.
static std::pair< CompMapPtr,
double > subtractCompMaps (std::pair< CompMapPtr, double > orig, std::pair< CompMapPtr, double > to_subtract)
add comments
static std::pair< IsoVector,
double > sum_mats (std::deque< mat_rsrc_ptr > mats)
sums the materials in the vector, filling the vec and kg with the cumulative IsoVector and total mass, in kg.
static double V_ds (double V_T, double theta, double d)
Returns the degraded solid volume [m^3] based on the total volume and the porosity.
static double V_f (double V_T, double theta)
Returns the fluid volume [m^3] based on the total volume and the porosity.
static double V_ff (double V_T, double theta, double d)
Returns the free fluid volume [m^3] based on the total volume, porosity, and total degradation.
static double V_mf (double V_T, double theta, double d)
Returns the fluid volume in the intact matrix [m^3] based on the total volume, porosity, and total degradation.
static double V_ms (double V_T, double theta, double d)
Returns the matrix solid volume [m^3] based on the total volume and the porosity.
static double V_s (double V_T, double theta)
Returns the solid volume [m^3] based on the total volume and the porosity.
static void validate_finite_pos (double pos)
Confirms whether or not the provided value is finite and positive(0<=pos<=infty)
static void validate_nonzero (double nonzero)
Confirms whether or not the provided value is zero.
static void validate_percent (double per)
Confirms whether or not the provided value is a percent (0<=per<=1)
static void validate_pos (double pos)
Confirms whether or not the provided value is positive(0<=pos)
static IsoConcMap zeroConcMap ()
Returns an empty IsoConcMap.
Detailed Description
MatTools is a toolkit for manipulating materials.
Definition at line 63 of file MatTools.h.
Member Function Documentation
static CompMapPtr MatTools::addCompMaps (CompMapPtr orig, CompMapPtr to_add) static
add comments
IsoConcMap MatTools::addConcMaps (IsoConcMap orig, IsoConcMap to_add) static
This is a helper function that returns the sum of two IsoConcMaps.
Parameters:
orig the original IsoConcMap (not modified in this function)
to_add IsoConcMap to add (not modified in this function)
Returns:
to_ret the sum of orig and to_add
Definition at line 208 of file MatTools.cpp.
Referenced by LumpedNuclide::extractIntegratedMass(), and OneDimPPMNuclide::trap_rule().
IsoConcMap MatTools::comp_to_conc_map (const CompMapPtr comp, double mass, double vol) static
Converts a CompMap and associated total mass to an IsoConcMap for a Volume.
Parameters:
comp the composition to convert, a CompMapPtr
mass the total mass of the composition [kg]
vol the total volume in which the concentration exists [m^3]
Returns:
an IsoConcMap whose elements are comp[iso]*mass/volume
Definition at line 72 of file MatTools.cpp.
References validate_finite_pos().
Referenced by OneDimPPMNuclide::Ci(), DegRateNuclide::dirichlet_bc(), MixedCellNuclide::dirichlet_bc(), MixedCellNuclide::neumann_bc(), LumpedNuclideTest::SetUp(), TEST_F(), and LumpedNuclide::update_inner_bc().
pair< CompMapPtr, double > MatTools::conc_to_comp_map (const IsoConcMap conc, double vol) static
Converts an IsoConcMap and Volume to CompMap and associated total mass.
Parameters:
conc the IsoConcMap to convert
vol the total volume in which the concentration exists [m^3]
Returns:
a CompMapPtr and associated mass
Definition at line 102 of file MatTools.cpp.
References validate_finite_pos().
Referenced by LumpedNuclide::extractIntegratedMass(), DegRateNuclide::inner_dirichlet(), MixedCellNuclide::inner_dirichlet(), DegRateNuclide::inner_neumann(), MixedCellNuclide::inner_neumann(), TEST_F(), and OneDimPPMNuclide::update_inner_bc().
mat_rsrc_ptr MatTools::extract (const CompMapPtr comp_to_rem, double kg_to_rem, std::deque< mat_rsrc_ptr > & mat_list) static
removes the specified amount of the specified composition from a deque of materials provided to the function by reference.
Parameters:
comp_to_rem a CompMapPtr representing what to remove
kg_to_rem a mass to remove of the CompMapPtr [kg]
mat_list the list of materials to remove that comp from
Returns:
the material extracted
Definition at line 56 of file MatTools.cpp.
Referenced by StubNuclide::extract(), DegRateNuclide::extract(), MixedCellNuclide::extract(), LumpedNuclide::extract(), and OneDimPPMNuclide::extract().
int MatTools::isoToElem (int iso) static
Converts a standard isoid into an element.
Parameters:
iso the isotope id (i.e. 92235) to convert
Returns:
elem the element id (i.e. 92) that corresponds to iso
Definition at line 260 of file MatTools.cpp.
Referenced by MixedCellNuclide::precipitate(), MixedCellNuclide::sorb(), and TEST_F().
vector< double > MatTools::linspace (double a, double b, int n) static
add comments
Definition at line 267 of file MatTools.cpp.
Referenced by OneDimPPMNuclide::update_inner_bc().
IsoConcMap MatTools::scaleConcMap (IsoConcMap C_0, double scalar) static
This is a helper function that scales an IsoConcMap with a scalar.
Parameters:
C_0 the original IsoConcMap, to be scaled.
scalar the scalar by which to multiply each element of C_0 [-]
Definition at line 196 of file MatTools.cpp.
References validate_finite_pos().
Referenced by LumpedNuclide::C_DM(), LumpedNuclide::C_EXPM(), LumpedNuclide::C_PFM(), LumpedNuclide::extractIntegratedMass(), DegRateNuclide::inner_dirichlet(), MixedCellNuclide::inner_dirichlet(), DegRateNuclide::inner_neumann(), MixedCellNuclide::inner_neumann(), LumpedNuclide::source_term_bc(), TEST_F(), and OneDimPPMNuclide::trap_rule().
pair< CompMapPtr, double > MatTools::subtractCompMaps (std::pair< CompMapPtr, double > orig, std::pair< CompMapPtr, double > to_subtract) static
add comments
Definition at line 229 of file MatTools.cpp.
pair< IsoVector, double > MatTools::sum_mats (std::deque< mat_rsrc_ptr > mats) static
sums the materials in the vector, filling the vec and kg with the cumulative IsoVector and total mass, in kg.
should put this in a toolkit or something. Doesn't belong here.
Parameters:
mats the vector of materials to be summed (not mixed)
Definition at line 22 of file MatTools.cpp.
Referenced by OneDimPPMNuclide::Ci(), DegRateNuclide::source_term_bc(), MixedCellNuclide::source_term_bc(), OneDimPPMNuclide::source_term_bc(), TEST_F(), OneDimPPMNuclide::update_inner_bc(), OneDimPPMNuclide::update_vec_hist(), DegRateNuclide::update_vec_hist(), MixedCellNuclide::update_vec_hist(), and LumpedNuclide::update_vec_hist().
double MatTools::V_ds (double V_T, double theta, double d) static
Returns the degraded solid volume [m^3] based on the total volume and the porosity.
Parameters:
V_T the total volume [m^3]
theta the porosity (a fraction)
Returns:
V_ds the degraded solid volume [m^3]
Definition at line 149 of file MatTools.cpp.
Referenced by TEST_F().
double MatTools::V_f (double V_T, double theta) static
Returns the fluid volume [m^3] based on the total volume and the porosity.
Parameters:
V_T the total volume [m^3]
theta the porosity (a fraction)
Returns:
V_f the fluid volume [m^3]
Definition at line 126 of file MatTools.cpp.
Referenced by TEST_F().
double MatTools::V_ff (double V_T, double theta, double d) static
Returns the free fluid volume [m^3] based on the total volume, porosity, and total degradation.
Parameters:
V_T the total volume [m^3]
theta the porosity (a fraction)
d the total degradation (a fraction)
Returns:
V_ff the free fluid volume [m^3]
Definition at line 133 of file MatTools.cpp.
Referenced by TEST_F().
double MatTools::V_mf (double V_T, double theta, double d) static
Returns the fluid volume in the intact matrix [m^3] based on the total volume, porosity, and total degradation.
Parameters:
V_T the total volume [m^3]
theta the porosity (a fraction)
d the total degradation (a fraction)
Returns:
V_mf the fluid volume in the intact matrix [m^3]
Definition at line 139 of file MatTools.cpp.
Referenced by TEST_F().
double MatTools::V_ms (double V_T, double theta, double d) static
Returns the matrix solid volume [m^3] based on the total volume and the porosity.
Parameters:
V_T the total volume [m^3]
theta the porosity (a fraction)
Returns:
V_ms the matrix solid volume [m^3]
Definition at line 155 of file MatTools.cpp.
Referenced by TEST_F().
double MatTools::V_s (double V_T, double theta) static
Returns the solid volume [m^3] based on the total volume and the porosity.
Parameters:
V_T the total volume [m^3]
theta the porosity (a fraction)
Returns:
V_s the solid volume [m^3]
Definition at line 144 of file MatTools.cpp.
Referenced by TEST_F().
void MatTools::validate_finite_pos (double pos) static
Confirms whether or not the provided value is finite and positive(0<=pos<=infty)
Parameters:
pos the value to test
Exceptions:
CycRangeException
Definition at line 171 of file MatTools.cpp.
Referenced by OneDimPPMNuclide::Azt(), OneDimPPMNuclide::Bzt(), OneDimPPMNuclide::calculate_conc_diff(), comp_to_conc_map(), conc_to_comp_map(), scaleConcMap(), STCThermal::set_alpha_th(), STCThermal::set_k_th(), LumpedNuclide::set_Pe(), STCThermal::set_r_calc(), Geometry::set_radius(), OneDimPPMNuclide::set_rho(), STCThermal::set_spacing(), TEST_F(), OneDimPPMNuclide::update_inner_bc(), and Geometry::volume().
void MatTools::validate_nonzero (double nonzero) static
Confirms whether or not the provided value is zero.
Parameters:
nonzero the value to test
Exceptions:
CycRangeException
Definition at line 190 of file MatTools.cpp.
void MatTools::validate_percent (double per) static
Confirms whether or not the provided value is a percent (0<=per<=1)
Parameters:
per the value to test
Exceptions:
CycRangeException
Definition at line 160 of file MatTools.cpp.
Referenced by LumpedNuclide::set_porosity(), and OneDimPPMNuclide::set_porosity().
void MatTools::validate_pos (double pos) static
Confirms whether or not the provided value is positive(0<=pos)
Parameters:
pos the value to test
Exceptions:
CycRangeException if pos<0
Definition at line 179 of file MatTools.cpp.
Referenced by Cyder::set_r_lim(), and Cyder::set_t_lim().
IsoConcMap MatTools::zeroConcMap () static
Returns an empty IsoConcMap.
Definition at line 96 of file MatTools.cpp.
The documentation for this class was generated from the following files:
MatTools.h
MatTools.cpp