cyder: OneDimPPMNuclide Class Reference
OneDimPPMNuclide Class Reference
OneDimPPMNuclide is a nuclide transport model that treats the volume as a one dimensional system with unidirectional flow and a semi-infinite boundary condition in the positive flow direction.
#include <OneDimPPMNuclide.h>
Public Member Functions
virtual void absorb (mat_rsrc_ptr matToAdd)
Absorbs the contents of the given Material into this OneDimPPMNuclide.
double Azt (double R, double z, double v, double t, double D)
give doc
double Bzt (double R, double z, double v, double t, double D, double C_i)
give doc
double calculate_conc_diff (IsoConcMap C_0, IsoConcMap C_i, double r_calc, int iso, int t0, int t)
Calculates the concentration of a single isotope due to C_0 after dt at radius r_calc.
IsoConcMap calculate_conc_diff (IsoConcMap C_0, IsoConcMap C_i, double r_calc, int t0, int t)
Calculates the concentration of an isoconcmap due to C_0 after dt at radius r_calc.
virtual IsoFluxMap cauchy_bc (IsoConcMap c_ext, Radius r_ext)
returns the flux at the boundary, the Neumann bc
IsoConcMap Ci ()
return initial concentration in the cell for this timestep
IsoConcMap Co (const NuclideModelPtr &daughter)
return Co, the source concentration at the inner boundary
IsoConcMap conc_profile (IsoConcMap C_0, double r_calc, int dt)
Calculates the concentration of each isotope a certain time and radius.
virtual NuclideModelPtr copy (const NuclideModel &src)
copies a nuclide model and its parameters from another
virtual IsoConcMap dirichlet_bc ()
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
virtual mat_rsrc_ptr extract (CompMapPtr comp_to_rem, double kg_to_rem)
Extracts the contents of the given Material from this NuclideModel.
virtual void initModuleMembers (QueryEngine *qe)
initializes the model parameters from an xmlNodePtr
virtual std::string name ()
Returns the nuclide model type name.
virtual ConcGradMap neumann_bc (IsoConcMap c_ext, Radius r_ext)
returns the concentration gradient at the boundary, the Neumann bc
const double porosity () const
return porosity
virtual void print ()
standard verbose printer includes current temp and concentrations
const double rho () const
return bulk density
void set_Ci (IsoConcMap Ci)
sets the Ci_ variable, the initial concentration.
void set_porosity (double porosity)
sets the porosity_ variable, the percent void of the medium
void set_rho (double rho)
sets the rho_ variable, the dry bulk density of the medium [kg/m^3]
void set_v (double v)
sets the v_ variable, the advective velocity through this component.
virtual std::pair< IsoVector,
double > source_term_bc ()
returns the available material source term at the outer boundary of the component
virtual void transportNuclides (int time)
Transports nuclides from the inner to the outer boundary.
IsoConcMap trap_rule (double a, double b, int n, std::map< double, IsoConcMap > fmap)
describe
virtual NuclideModelType type ()
Returns the nuclide model type.
virtual void update (int the_time)
Updates all the hists.
void update_conc_hist (int the_time)
Updates the available concentration using the wastes_ as mats.
void update_conc_hist (int the_time, std::deque< mat_rsrc_ptr > mats)
Updates the available concentration.
void update_inner_bc (int the_time, std::vector< NuclideModelPtr > daughters)
Determines what IsoVector to remove from the daughter nuclide models.
void update_vec_hist (int the_time)
update the istopic contaminant vector history, vec_hist_ based on wastes_
virtual void updateNuclideParamsTable ()
Updates the NuclideParams table by adding appropriate rows to describe the parameters initializing this NuclideModel.
const double v () const
The advective velocity through this component.
double V_f ()
Gets the fluid volume, based on porosity.
virtual double V_ff ()
Gets the fluid volume, based on porosity.
double V_T ()
Gets the total fluid volume.
virtual ~OneDimPPMNuclide ()
Virtual destructor deletes datamembers that are object pointers.
Public Member Functions inherited from NuclideModel
virtual void addRowToNuclideParamsTable (std::string param_name, boost::any param_val)
adds a row to the NuclideModelParams table.
ConcGrad calc_conc_grad (Concentration c_ext, Concentration c_int, Radius r_ext, Radius r_int)
Returns the concentration gradient based on a simple finite difference between two datapoints.
Flux cauchy_bc (IsoConcMap c_ext, Radius r_ext, Iso tope)
IsoConcMap conc_hist (int the_time)
Returns the map of isotopes to concentrations at the time profided.
Concentration conc_hist (int the_time, Iso tope)
Returns the concetration of a certain isotope at a certain time.
double contained_mass (int the_time)
returns the current contained contaminant mass, in kg, at time
IsoVector contained_vec (int the_time)
The IsoVector representing the summed, normalized material in the component.
virtual Concentration dirichlet_bc (Iso tope)
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
virtual BCType enumerateBCType (std::string type_name)
spits out a number instead of a BCType
const GeometryPtr geom () const
Returns the geom_ data member.
int last_updated ()
returns the time at which the vec_hist and conc_hist were updated
virtual ConcGrad neumann_bc (IsoConcMap c_ext, Radius r_ext, Iso tope)
returns the concentration gradient at the boundary, the Neumann bc
void set_comp_id (int id)
Allows the component id data member to be set.
void set_geom (GeometryPtr geom)
Allows the geometry object to be set.
void set_last_updated (int new_last_updated)
sets the last time that the vec_hist and conc_hist were updated, first verifying whether last_updated is larger than last_updated_
void set_mat_table (MatDataTablePtr mat_table)
sends a pointer to the material table used by this component
virtual double source_term_bc (Iso tope)
returns the prescribed concentration at the boundary, the source term bc in kg
std::pair< IsoVector, double > vec_hist (int the_time)
Returns the IsoVector mass pair for a certain time.
std::deque< mat_rsrc_ptr > wastes ()
Returns wastes_.
virtual ~NuclideModel ()
A virtual destructor.
Static Public Member Functions
static OneDimPPMNuclidePtr create ()
A constructor for the OneDimPPM Nuclide Model that returns a shared pointer.
static OneDimPPMNuclidePtr create (QueryEngine *qe)
A constructor for the OneDimPPM Nuclide Model that returns a shared pointer.
Protected Attributes
IsoConcMap Ci_
The initial contaminant concentration, C(x,0), in g/cm^3.
IsoConcMap Co_
The contaminant concentration constantly at the source until t_0, in g/cm^3.
double porosity_
Porosity of the component matrix, a fraction between 0 and 1, inclusive.
double rho_
The bulk (dry) density of the component matrix, in g/cm^3.
double v_
The advective velocity through the waste packages in units of m/s.
Protected Attributes inherited from NuclideModel
int comp_id_
the id of the component that this nuclidemodel is a part of
ConcHist conc_hist_
The map of times to isotopes to concentrations, in kg/m^3.
GeometryPtr geom_
A shared pointer to the geometry of the component.
int last_updated_
the time at which the histories were last updated
MatDataTablePtr mat_table_
A shared pointer to this Component's material data table.
VecHist vec_hist_
The map of times to IsoVectors.
std::deque< mat_rsrc_ptr > wastes_
A vector of the wastes contained by this component wastes(){return component_->wastes();};.
Private Member Functions
OneDimPPMNuclide ()
Default constructor for the mixed cell nuclide model class.
OneDimPPMNuclide (QueryEngine *qe)
primary constructor reads input from QueryEngine
Detailed Description
OneDimPPMNuclide is a nuclide transport model that treats the volume as a one dimensional system with unidirectional flow and a semi-infinite boundary condition in the positive flow direction.
The solution is given in : F. J. Leij, T. H. Skaggs, and M. T. Van Genuchten, ``Analytical solutions for solute transport in three-dimensional semi-infinite porous media,'' Water resources research, vol. 27, no. 10, p. 27192733, 1991.
This disposal system nuclide model will receive material both diffusively and advectively. That is, at the internal boundary a Cauchy type boundary condition is applied.
For the boundary and initial conditions,
the solution is given as
If the concentration from an adjacent cell is higher than the concentration within the mixed cell, this cell will accept the appropriate diffusive flux accross that boundary. So too if the concentration is lower in the adjacent cell, a corresponding contaminant flux will leave this cell across that boundary. Similarly, the advective velocity (unidirectional) at the internal boundary of this cell will cause material to enter the cell advectively.
When accepting a flux of Material, this cell incorporates it into the list of wastes that it contains.. The volume will then make the corresponding boundary conditions available at all boundaries.
The OneDimPPMNuclide model can be used to represent nuclide models of the disposal system such as the Waste Form, Waste Package, Buffer, Near Field, Far Field, and Envrionment. However, is is best used to represent either the Buffer or the Environment components, due to its long running time and lack of degradation.
Definition at line 74 of file OneDimPPMNuclide.h.
Constructor & Destructor Documentation
OneDimPPMNuclide::OneDimPPMNuclide () private
Default constructor for the mixed cell nuclide model class.
Creates an empty mixed cell with contaminant concentration zero unless an initial contaminant concentration is specified.
Definition at line 23 of file OneDimPPMNuclide.cpp.
References Ci_, Co_, NuclideModel::conc_hist_, NuclideModel::last_updated_, NuclideModel::set_geom(), NuclideModel::vec_hist_, and NuclideModel::wastes_.
Referenced by create().
OneDimPPMNuclide::OneDimPPMNuclide (QueryEngine * qe) private
primary constructor reads input from QueryEngine
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 39 of file OneDimPPMNuclide.cpp.
References Ci_, Co_, NuclideModel::conc_hist_, initModuleMembers(), NuclideModel::last_updated_, NuclideModel::set_geom(), NuclideModel::vec_hist_, and NuclideModel::wastes_.
OneDimPPMNuclide::~OneDimPPMNuclide () virtual
Virtual destructor deletes datamembers that are object pointers.
Definition at line 55 of file OneDimPPMNuclide.cpp.
Member Function Documentation
void OneDimPPMNuclide::absorb (mat_rsrc_ptr matToAdd) virtual
Absorbs the contents of the given Material into this OneDimPPMNuclide.
Parameters:
matToAdd the OneDimPPMNuclide to be absorbed
Implements NuclideModel.
Definition at line 105 of file OneDimPPMNuclide.cpp.
References NuclideModel::wastes_.
Referenced by update_inner_bc().
double OneDimPPMNuclide::Azt (double R, double z, double v, double t, double D)
give doc
Definition at line 247 of file OneDimPPMNuclide.cpp.
References MatTools::validate_finite_pos().
Referenced by calculate_conc_diff().
double OneDimPPMNuclide::Bzt (double R, double z, double v, double t, double D, double C_i)
give doc
Definition at line 257 of file OneDimPPMNuclide.cpp.
References MatTools::validate_finite_pos().
Referenced by calculate_conc_diff().
double OneDimPPMNuclide::calculate_conc_diff (IsoConcMap C_0, IsoConcMap C_i, double r_calc, int iso, int t0, int t)
Calculates the concentration of a single isotope due to C_0 after dt at radius r_calc.
/ describe van genuchten et. al eqn. here...
 @param C_0 the initial concentration at that radius?
 @param r_calc the radius at which to calculate the IsoConcMap [m]
 @param iso the isotope whose concentration is being queried [-]
 @param dt the change in time since C_0 was calculated [timestep]
Definition at line 269 of file OneDimPPMNuclide.cpp.
References Azt(), Bzt(), NuclideModel::mat_table_, SECSPERMONTH, v(), and MatTools::validate_finite_pos().
Referenced by calculate_conc_diff(), and update_inner_bc().
IsoConcMap OneDimPPMNuclide::calculate_conc_diff (IsoConcMap C_0, IsoConcMap C_i, double r_calc, int t0, int t)
Calculates the concentration of an isoconcmap due to C_0 after dt at radius r_calc.
/ describe van genuchten et. al eqn. here...
 @param C_0 the initial concentration at that radius?
 @param r_calc the radius at which to calculate the IsoConcMap [m]
 @param dt the change in time since C_0 was calculated [timestep]
Definition at line 234 of file OneDimPPMNuclide.cpp.
References calculate_conc_diff(), and MatTools::validate_finite_pos().
IsoFluxMap OneDimPPMNuclide::cauchy_bc (IsoConcMap c_ext, Radius r_ext) virtual
returns the flux at the boundary, the Neumann bc
Returns:
qC the solute flux at the boundary in kg/m^2/s
Implements NuclideModel.
Definition at line 196 of file OneDimPPMNuclide.cpp.
References NuclideModel::mat_table_, neumann_bc(), and v().
IsoConcMap OneDimPPMNuclide::Ci ()
return initial concentration in the cell for this timestep
Definition at line 417 of file OneDimPPMNuclide.cpp.
References MatTools::comp_to_conc_map(), MatTools::sum_mats(), V_ff(), and NuclideModel::wastes_.
Referenced by set_Ci(), and update_inner_bc().
IsoConcMap OneDimPPMNuclide::Co (const NuclideModelPtr & daughter)
return Co, the source concentration at the inner boundary
Definition at line 405 of file OneDimPPMNuclide.cpp.
References dirichlet_bc(), NuclideModel::geom(), and v().
Referenced by update_inner_bc().
IsoConcMap OneDimPPMNuclide::conc_profile (IsoConcMap C_0, double r_calc, int dt)
Calculates the concentration of each isotope a certain time and radius.
Parameters:
C_0 the initial concentration at that radius?
r_calc the radius at which to calculate the IsoConcMap [m]
dt the change in time since C_0 was calculated [timestep]
NuclideModelPtr OneDimPPMNuclide::copy (const NuclideModel & src) virtual
copies a nuclide model and its parameters from another
Parameters:
src is the nuclide model being copied
Implements NuclideModel.
Definition at line 69 of file OneDimPPMNuclide.cpp.
References NuclideModel::conc_hist_, NuclideModel::geom(), NuclideModel::geom_, porosity(), rho(), NuclideModel::set_geom(), NuclideModel::set_last_updated(), set_porosity(), set_rho(), set_v(), update_vec_hist(), v(), NuclideModel::vec_hist_, and NuclideModel::wastes_.
static OneDimPPMNuclidePtr OneDimPPMNuclide::create () inline static
A constructor for the OneDimPPM Nuclide Model that returns a shared pointer.
Definition at line 96 of file OneDimPPMNuclide.h.
References OneDimPPMNuclide().
Referenced by OneDimPPMNuclideTest::initNuclideModel(), NuclideModelFactory::nuclideModel(), OneDimPPMNuclideModelConstructor(), OneDimPPMNuclideTest::SetUp(), and TEST_F().
static OneDimPPMNuclidePtr OneDimPPMNuclide::create (QueryEngine * qe) inline static
A constructor for the OneDimPPM Nuclide Model that returns a shared pointer.
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 103 of file OneDimPPMNuclide.h.
References OneDimPPMNuclide().
IsoConcMap OneDimPPMNuclide::dirichlet_bc () virtual
returns the prescribed concentration at the boundary, the dirichlet bc in kg/m^3
Returns:
C the concentration at the boundary in kg/m^3 for each isotope
Implements NuclideModel.
Definition at line 152 of file OneDimPPMNuclide.cpp.
References source_term_bc(), and V_ff().
Referenced by Co(), and neumann_bc().
mat_rsrc_ptr OneDimPPMNuclide::extract (CompMapPtr comp_to_rem, double kg_to_rem) virtual
Extracts the contents of the given Material from this NuclideModel.
Use this function for decrementing a NuclideModel's mass balance after transferring through a link.
Parameters:
comp_to_rem the composition to decrement against this OneDimPPMNuclide
comp_to_rem the mass in kg to decrement against this OneDimPPMNuclide
Returns:
the material extracted
Implements NuclideModel.
Definition at line 116 of file OneDimPPMNuclide.cpp.
References MatTools::extract(), NuclideModel::last_updated(), update(), and NuclideModel::wastes_.
void OneDimPPMNuclide::initModuleMembers (QueryEngine * qe) virtual
initializes the model parameters from an xmlNodePtr
Parameters:
qe is the QueryEngine object containing intialization info
Implements NuclideModel.
Definition at line 58 of file OneDimPPMNuclide.cpp.
References porosity_, rho_, and v_.
Referenced by OneDimPPMNuclide().
virtual std::string OneDimPPMNuclide::name () inline virtual
Returns the nuclide model type name.
Implements NuclideModel.
Definition at line 178 of file OneDimPPMNuclide.h.
ConcGradMap OneDimPPMNuclide::neumann_bc (IsoConcMap c_ext, Radius r_ext) virtual
returns the concentration gradient at the boundary, the Neumann bc
Returns:
dCdx the concentration gradient at the boundary in kg/m^3
Implements NuclideModel.
Definition at line 168 of file OneDimPPMNuclide.cpp.
References NuclideModel::calc_conc_grad(), dirichlet_bc(), and NuclideModel::geom().
Referenced by cauchy_bc().
const double OneDimPPMNuclide::porosity () const inline
return porosity
Definition at line 227 of file OneDimPPMNuclide.h.
References porosity_.
Referenced by copy(), set_porosity(), updateNuclideParamsTable(), and V_f().
void OneDimPPMNuclide::print () virtual
standard verbose printer includes current temp and concentrations
Implements NuclideModel.
Definition at line 100 of file OneDimPPMNuclide.cpp.
const double OneDimPPMNuclide::rho () const inline
return bulk density
Definition at line 303 of file OneDimPPMNuclide.h.
References rho_.
Referenced by copy(), set_rho(), and updateNuclideParamsTable().
void OneDimPPMNuclide::set_Ci (IsoConcMap Ci)
sets the Ci_ variable, the initial concentration.
Definition at line 422 of file OneDimPPMNuclide.cpp.
References Ci(), and Ci_.
void OneDimPPMNuclide::set_porosity (double porosity)
sets the porosity_ variable, the percent void of the medium
Definition at line 373 of file OneDimPPMNuclide.cpp.
References porosity(), porosity_, and MatTools::validate_percent().
Referenced by copy().
void OneDimPPMNuclide::set_rho (double rho)
sets the rho_ variable, the dry bulk density of the medium [kg/m^3]
Definition at line 389 of file OneDimPPMNuclide.cpp.
References rho(), rho_, and MatTools::validate_finite_pos().
Referenced by copy().
void OneDimPPMNuclide::set_v (double v)
sets the v_ variable, the advective velocity through this component.
Definition at line 427 of file OneDimPPMNuclide.cpp.
References v(), and v_.
Referenced by copy().
pair< IsoVector, double > OneDimPPMNuclide::source_term_bc () virtual
returns the available material source term at the outer boundary of the component
Returns:
the IsoVector and mass defining the outer boundary condition
Implements NuclideModel.
Definition at line 147 of file OneDimPPMNuclide.cpp.
References MatTools::sum_mats(), and NuclideModel::wastes_.
Referenced by dirichlet_bc().
void OneDimPPMNuclide::transportNuclides (int time) virtual
Transports nuclides from the inner to the outer boundary.
Parameters:
time the timestep at which to transport the nuclides
Implements NuclideModel.
Definition at line 129 of file OneDimPPMNuclide.cpp.
References update().
IsoConcMap OneDimPPMNuclide::trap_rule (double a, double b, int n, std::map< double, IsoConcMap > fmap)
describe
Definition at line 338 of file OneDimPPMNuclide.cpp.
References MatTools::addConcMaps(), and MatTools::scaleConcMap().
Referenced by update_inner_bc().
virtual NuclideModelType OneDimPPMNuclide::type () inline virtual
Returns the nuclide model type.
Implements NuclideModel.
Definition at line 173 of file OneDimPPMNuclide.h.
References ONEDIMPPM_NUCLIDE.
void OneDimPPMNuclide::update (int the_time) virtual
Updates all the hists.
Parameters:
the_time the time at which to update the history
Implements NuclideModel.
Definition at line 140 of file OneDimPPMNuclide.cpp.
References NuclideModel::set_last_updated(), update_conc_hist(), update_vec_hist(), and NuclideModel::wastes_.
Referenced by extract(), and transportNuclides().
void OneDimPPMNuclide::update_conc_hist (int the_time)
Updates the available concentration using the wastes_ as mats.
Parameters:
the_time the time at which to update the IsoConcMap
Definition at line 218 of file OneDimPPMNuclide.cpp.
References NuclideModel::wastes_.
Referenced by update().
void OneDimPPMNuclide::update_conc_hist (int the_time, std::deque< mat_rsrc_ptr > mats)
Updates the available concentration.
Parameters:
the_time the time at which to update the IsoConcMap
mats the materials that are part of the available concentration
void OneDimPPMNuclide::update_inner_bc (int the_time, std::vector< NuclideModelPtr > daughters) virtual
Determines what IsoVector to remove from the daughter nuclide models.
Parameters:
time the timestep at which the nuclides should be transported
daughter nuclide_model of an internal component. there may be many.
Implements NuclideModel.
Definition at line 299 of file OneDimPPMNuclide.cpp.
References absorb(), calculate_conc_diff(), Ci(), Co(), MatTools::conc_to_comp_map(), NuclideModel::geom(), MatTools::linspace(), MatTools::sum_mats(), trap_rule(), MatTools::validate_finite_pos(), and NuclideModel::wastes_.
void OneDimPPMNuclide::update_vec_hist (int the_time)
update the istopic contaminant vector history, vec_hist_ based on wastes_
Parameters:
the_time the time at which to update the vec_hist_ [timestep]
Definition at line 213 of file OneDimPPMNuclide.cpp.
References MatTools::sum_mats(), NuclideModel::vec_hist_, and NuclideModel::wastes_.
Referenced by copy(), and update().
void OneDimPPMNuclide::updateNuclideParamsTable () virtual
Updates the NuclideParams table by adding appropriate rows to describe the parameters initializing this NuclideModel.
Implements NuclideModel.
Definition at line 90 of file OneDimPPMNuclide.cpp.
References NuclideModel::mat_table_, porosity(), rho(), and v().
const double OneDimPPMNuclide::v () const inline
The advective velocity through this component.
[m/s]
Definition at line 311 of file OneDimPPMNuclide.h.
References v_.
Referenced by calculate_conc_diff(), cauchy_bc(), Co(), copy(), set_v(), and updateNuclideParamsTable().
double OneDimPPMNuclide::V_f ()
Gets the fluid volume, based on porosity.
Definition at line 437 of file OneDimPPMNuclide.cpp.
References porosity(), and V_T().
Referenced by V_ff().
virtual double OneDimPPMNuclide::V_ff () inline virtual
Gets the fluid volume, based on porosity.
Implements NuclideModel.
Definition at line 323 of file OneDimPPMNuclide.h.
References V_f().
Referenced by Ci(), and dirichlet_bc().
double OneDimPPMNuclide::V_T () virtual
Gets the total fluid volume.
Implements NuclideModel.
Definition at line 432 of file OneDimPPMNuclide.cpp.
References NuclideModel::geom_.
Referenced by V_f().
Member Data Documentation
IsoConcMap OneDimPPMNuclide::Ci_ protected
The initial contaminant concentration, C(x,0), in g/cm^3.
Definition at line 339 of file OneDimPPMNuclide.h.
Referenced by OneDimPPMNuclide(), and set_Ci().
IsoConcMap OneDimPPMNuclide::Co_ protected
The contaminant concentration constantly at the source until t_0, in g/cm^3.
Definition at line 342 of file OneDimPPMNuclide.h.
Referenced by OneDimPPMNuclide().
double OneDimPPMNuclide::porosity_ protected
Porosity of the component matrix, a fraction between 0 and 1, inclusive.
Definition at line 345 of file OneDimPPMNuclide.h.
Referenced by initModuleMembers(), porosity(), and set_porosity().
double OneDimPPMNuclide::rho_ protected
The bulk (dry) density of the component matrix, in g/cm^3.
Definition at line 348 of file OneDimPPMNuclide.h.
Referenced by initModuleMembers(), rho(), and set_rho().
double OneDimPPMNuclide::v_ protected
The advective velocity through the waste packages in units of m/s.
Definition at line 336 of file OneDimPPMNuclide.h.
Referenced by initModuleMembers(), set_v(), and v().
The documentation for this class was generated from the following files:
OneDimPPMNuclide.h
OneDimPPMNuclide.cpp