cyder: Component Class Reference
Component Class Reference
Defines interface for subcomponents of the Cyder generic repository.
#include <Component.h>
Public Member Functions
void absorb (mat_rsrc_ptr mat_to_add)
Absorbs the contents of the given Material into this Component.
void addComponentToTable (ComponentPtr comp)
Adds a component to the components table.
const point_t centroid ()
get the centroid position vector of the object
Component (Model *creator)
Creates an empty component.
ComponentType componentEnum (std::string type)
Enumerates a string if it is one of the named ComponentTypes.
void copy (const ComponentPtr &src)
copies a component and its parameters from another
NuclideModelPtr copyNuclideModel (NuclideModelPtr src)
Returns atd::s new nuclide model that is a copy of the src model.
ThermalModelPtr copyThermalModel (ThermalModelPtr src)
Returns a new thermal model that is a copy of the src model.
const std::vector< ComponentPtr > daughters ()
get the list of daughter components
void extract (CompMapPtr comp_to_rem, double kg_to_rem)
Extracts the contents of the given composition from this Component.
const GeometryPtr geom ()
get the pointer to the geometry object
const int ID ()
get the ID
void init (std::string name, ComponentType type, std::string mat, double ref_disp, double ref_kd, double ref_sol, Radius inner_radius, Radius outer_radius, ThermalModelPtr thermal_model, NuclideModelPtr nuclide_model)
initializes the model parameters from an QueryEngine object
void initModuleMembers (QueryEngine *qe)
initializes the model parameters from an QueryEngine object and calls the explicit init(ID, name, ...) function.
const Radius inner_radius ()
get the inner radius of the object
bool isFull ()
Reports true if the component is full of whatever goes inside it.
ComponentPtr load (ComponentType type, ComponentPtr to_load)
Loads this component with another component.
const MatDataTablePtr mat_table ()
get the material table that this component is made of (clay, salt, glass, etc.)
const std::string name ()
get the Name
const std::vector
< NuclideModelPtr > nuclide_daughters ()
Returns the nuclide models of each daughter component.
NuclideModelPtr nuclide_model (QueryEngine *qe)
Returns a new nuclide model of the string type and QueryEngine object.
NuclideModelPtr nuclide_model ()
gets the pointer to the nuclide model being used in this component
const Radius outer_radius ()
get the inner radius of the object
ComponentPtr parent ()
get the parent component
const Temp peak_temp (BoundaryType type)
get the peak Temperature this object will experience during the simulation
void print ()
standard verbose printer includes current temp and concentrations
void set_geom (GeometryPtr geom)
set the pointer to the geometry object
void set_mat_table (std::string mat, double ref_disp, double ref_kd, double ref_sol)
set the material type that this component is made of (clay, salt, glass, etc.) and retrieves the appropriate MatDataTablePtr
void set_mat_table (MatDataTablePtr mat_table)
set the material type that this component is made of (clay, salt, glass, etc.) and retrieves the appropriate MatDataTablePtr
void set_name (std::string name)
set the Name
void set_nuclide_model (const NuclideModelPtr &src)
sets the nuclide model to the src nuclide model
void set_parent (ComponentPtr parent)
set the parent component
void set_thermal_model (const ThermalModelPtr &src)
sets the thermal model to the src thermal model
void set_type (ComponentType type)
set the ComponentType
void setPlacement (point_t centroid, double length)
set the placement of the object
const Temp temp ()
get the Temperature
const Temp temp_lim ()
get the maximum Temperature this object allows at its boundaries
ThermalModelPtr thermal_model (QueryEngine *qe)
Returns a new thermal model of the string type QueryEngine object.
ThermalModelPtr thermal_model ()
gets the pointer to the thermal model being used in this component
void transportHeat (int time)
Transports heat from the inner boundary to the outer boundary in this component.
void transportNuclides (int time)
Transports nuclides from the inner boundary to the outer boundary in this component.
ComponentType type ()
Returns the ComponentType of this component (WF, WP, etc.)
void updateContaminantTable (int the_time)
Updates the gen_repo_contaminant_table_ for this component.
const std::deque< mat_rsrc_ptr > wastes ()
get the list of waste objects
const double x ()
get the x component of the centroid position vector of the object
const double y ()
get the y component of the centroid position vector of the object
const double z ()
get the z component of the centroid position vector of the object
~Component ()
Default destructor does nothing.
Protected Attributes
CompHistory comp_hist_
The composition history of this Component, in the form of a map whose keys are integers representing the time at which this Component had a particular composition and whose values are the corresponding compositions.
ConcMap concentrations_
The concentrations of contaminant isotopes in the component.
Model * creator_
the genrepo that created/owns this component
std::vector< ComponentPtr > daughters_
The immediate daughter components of this component.
GeometryPtr geom_
The geometry of the cylindrical component, a shared pointer.
int ID_
The serial number for this Component.
MassHistory mass_hist_
The mass history of this Component, in the form of a map whose keys are integers representing the time at which this Component had a particular composition and whose values are the corresponding mass compositions.
std::string mat_
The type of thermal model implemented by this component.
MatDataTablePtr mat_table_
A pointer to the MatDataTable representing this Component's material.
std::string name_
The name of this component, a string.
NuclideModelPtr nuclide_model_
The type of nuclide model implemented by this component.
ComponentPtr parent_
The immediate parent component of this component.
Temp peak_inner_temp_
The peak temp achieved at the inner boundary.
Temp peak_outer_temp_
The peak temp achieved at the outer boundary.
Temp temp_
The temp taken to be the homogeneous temp of the whole component.
Temp temp_lim_
The temp limit of this component.
ThermalModelPtr thermal_model_
The type of thermal model implemented by this component.
ComponentType type_
The type of component that this component represents (ff, buffer, wp, etc.)
Static Protected Attributes
static int nextID_ = 0
Stores the next available component ID.
Detailed Description
Defines interface for subcomponents of the Cyder generic repository.
Components such as the Waste Form, Waste Package, Buffer, Near Field, Far Field, and Envrionment will share a universal interface so that information passing concerning fluxes and other boundary conditions can be passed in and out of them.
Definition at line 60 of file Component.h.
Constructor & Destructor Documentation
Component::Component (Model * creator)
Creates an empty component.
Definition at line 32 of file Component.cpp.
References comp_hist_, creator_, mass_hist_, and set_geom().
Component::~Component ()
Default destructor does nothing.
Definition at line 52 of file Component.cpp.
Member Function Documentation
void Component::absorb (mat_rsrc_ptr mat_to_add)
Absorbs the contents of the given Material into this Component.
Parameters:
mat_to_add the Material to be absorbed
Definition at line 182 of file Component.cpp.
References nuclide_model().
void Component::addComponentToTable (ComponentPtr comp)
Adds a component to the components table.
Definition at line 298 of file Component.cpp.
const point_t Component::centroid ()
get the centroid position vector of the object
Definition at line 362 of file Component.cpp.
References geom_.
ComponentType Component::componentEnum (std::string type)
Enumerates a string if it is one of the named ComponentTypes.
Parameters:
type the name of the ComponentType (i.e. FF)
Returns:
the ComponentType enum associated with this string by the component_type_names_ list
Definition at line 246 of file Component.cpp.
References LAST_EBS, name(), and type().
Referenced by initModuleMembers().
void Component::copy (const ComponentPtr & src)
copies a component and its parameters from another
Parameters:
src is the component being copied
Definition at line 112 of file Component.cpp.
References comp_hist_, copyNuclideModel(), copyThermalModel(), ID_, mass_hist_, name_, nextID_, set_geom(), set_mat_table(), set_name(), set_nuclide_model(), set_thermal_model(), set_type(), temp_, and temp_lim_.
NuclideModelPtr Component::copyNuclideModel (NuclideModelPtr src)
Returns atd::s new nuclide model that is a copy of the src model.
Definition at line 283 of file Component.cpp.
References geom(), ID(), mat_table(), and NuclideModelFactory::nuclideModel().
Referenced by copy(), and init().
ThermalModelPtr Component::copyThermalModel (ThermalModelPtr src)
Returns a new thermal model that is a copy of the src model.
Parameters:
src a pointer to the thermal model to copy
Returns:
a pointer to the ThermalModel that was created
Definition at line 278 of file Component.cpp.
References geom(), mat_table(), and ThermalModelFactory::thermalModel().
Referenced by copy(), and init().
const std::vector< ComponentPtr > Component::daughters ()
get the list of daughter components
Returns:
components
Definition at line 337 of file Component.cpp.
References daughters_.
void Component::extract (CompMapPtr comp_to_rem, double kg_to_rem)
Extracts the contents of the given composition from this Component.
Use this function for decrementing a Component's mass balance after transferring through a link.
Parameters:
comp_to_rem the composition to decrement against this Component
kg_to_rem the mass in kg to decrement against this Component
Definition at line 190 of file Component.cpp.
References nuclide_model().
const GeometryPtr Component::geom () inline
get the pointer to the geometry object
Definition at line 346 of file Component.h.
References geom_.
Referenced by copyNuclideModel(), copyThermalModel(), init(), isFull(), set_geom(), and setPlacement().
const int Component::ID ()
get the ID
Returns:
ID_
Definition at line 317 of file Component.cpp.
References ID_.
Referenced by copyNuclideModel(), and updateContaminantTable().
void Component::init (std::string name, ComponentType type, std::string mat, double ref_disp, double ref_kd, double ref_sol, Radius inner_radius, Radius outer_radius, ThermalModelPtr thermal_model, NuclideModelPtr nuclide_model)
initializes the model parameters from an QueryEngine object
Parameters:
name the name_ data member, a string
type the type_ data member, a ComponentType enum value
mat the name to initialize the mat_table_ data member, a string
ref_disp a reference (hydrogen) dispersion coefficient
ref_kd a reference (hydrogen) K_d coefficient
ref_sol a reference (hydrogen) Solubility coefficient
inner_radius the inner_radius_ data member, in meters
outer_radius the outer_radius_ data member, in meters
thermal_model the thermal_model_ data member, a pointer
nuclide_model the nuclide_model_ data member, a pointer
Definition at line 87 of file Component.cpp.
References comp_hist_, copyNuclideModel(), copyThermalModel(), geom(), ID_, INNER, mass_hist_, name(), name_, nextID_, OUTER, set_mat_table(), set_nuclide_model(), set_thermal_model(), type(), and type_.
void Component::initModuleMembers (QueryEngine * qe)
initializes the model parameters from an QueryEngine object and calls the explicit init(ID, name, ...) function.
Parameters:
qe is the QueryEngine object containing intialization info
Definition at line 56 of file Component.cpp.
References componentEnum(), inner_radius(), name(), nuclide_model(), outer_radius(), thermal_model(), and type().
const Radius Component::inner_radius ()
get the inner radius of the object
Returns:
inner_radius_ in [meters]
Definition at line 356 of file Component.cpp.
References geom_.
Referenced by initModuleMembers().
bool Component::isFull ()
Reports true if the component is full of whatever goes inside it.
Returns:
TRUE if the component is full and FALSE if there is no more room
Definition at line 222 of file Component.cpp.
References BUFFER, daughters_, geom(), and type().
ComponentPtr Component::load (ComponentType type, ComponentPtr to_load)
Loads this component with another component.
Parameters:
type the ComponentType of this component
to_load the Component to load into this component
Definition at line 215 of file Component.cpp.
References daughters_.
const MatDataTablePtr Component::mat_table ()
get the material table that this component is made of (clay, salt, glass, etc.)
Returns:
mat_table
Definition at line 334 of file Component.cpp.
References mat_table_.
Referenced by copyNuclideModel(), and copyThermalModel().
const std::string Component::name ()
get the Name
Returns:
name_
Definition at line 320 of file Component.cpp.
References name_.
Referenced by componentEnum(), init(), initModuleMembers(), and set_name().
const std::vector< NuclideModelPtr > Component::nuclide_daughters ()
Returns the nuclide models of each daughter component.
Definition at line 288 of file Component.cpp.
References daughters_.
Referenced by transportNuclides().
NuclideModelPtr Component::nuclide_model (QueryEngine * qe)
Returns a new nuclide model of the string type and QueryEngine object.
Parameters:
qe is the QueryEngine object containing intialization info
Returns:
nuclide_model_ a pointer to the NuclideModel that was created
Definition at line 273 of file Component.cpp.
References NuclideModelFactory::nuclideModel().
NuclideModelPtr Component::nuclide_model ()
gets the pointer to the nuclide model being used in this component
Returns:
nuclide_model_
Definition at line 374 of file Component.cpp.
References nuclide_model_.
Referenced by absorb(), extract(), initModuleMembers(), transportNuclides(), updateContaminantTable(), and wastes().
const Radius Component::outer_radius ()
get the inner radius of the object
Returns:
outer_radius_ in [meters]
Definition at line 359 of file Component.cpp.
References geom_.
Referenced by initModuleMembers().
ComponentPtr Component::parent ()
get the parent component
Returns:
component
Definition at line 340 of file Component.cpp.
References parent_.
Referenced by set_parent().
const Temp Component::peak_temp (BoundaryType type)
get the peak Temperature this object will experience during the simulation
Parameters:
type indicates whether to return the inner or outer peak temp
Returns:
peak_temp_
Definition at line 349 of file Component.cpp.
References INNER, peak_inner_temp_, and peak_outer_temp_.
void Component::print ()
standard verbose printer includes current temp and concentrations
Definition at line 152 of file Component.cpp.
References wastes().
void Component::set_geom (GeometryPtr geom) inline
set the pointer to the geometry object
Definition at line 343 of file Component.h.
References geom(), and geom_.
Referenced by Component(), and copy().
void Component::set_mat_table (std::string mat, double ref_disp, double ref_kd, double ref_sol)
set the material type that this component is made of (clay, salt, glass, etc.) and retrieves the appropriate MatDataTablePtr
Parameters:
mat the name of the material type (clay, salt, glass, etc.)
ref_disp a reference (related to hydrogen) dispersion parameter
ref_kd a reference (related to hydrogen) K_d value
ref_sol a reference (related to hydrogen) S value
Definition at line 323 of file Component.cpp.
References mat_table_, and MDB.
Referenced by copy(), and init().
void Component::set_mat_table (MatDataTablePtr mat_table)
set the material type that this component is made of (clay, salt, glass, etc.) and retrieves the appropriate MatDataTablePtr
Parameters:
mat_table the MatDataTablePtr for the material type (clay, salt, glass, etc.)
Definition at line 329 of file Component.cpp.
References mat_table_.
void Component::set_name (std::string name) inline
set the Name
Parameters:
the new name
Definition at line 237 of file Component.h.
References name(), and name_.
Referenced by copy().
void Component::set_nuclide_model (const NuclideModelPtr & src) inline
sets the nuclide model to the src nuclide model
Definition at line 358 of file Component.h.
References nuclide_model_.
Referenced by copy(), and init().
void Component::set_parent (ComponentPtr parent) inline
set the parent component
Parameters:
parent is the component that should be set as the parent
Definition at line 377 of file Component.h.
References parent(), and parent_.
void Component::set_thermal_model (const ThermalModelPtr & src) inline
sets the thermal model to the src thermal model
Definition at line 370 of file Component.h.
References thermal_model_.
Referenced by copy(), and init().
void Component::set_type (ComponentType type) inline
set the ComponentType
Definition at line 175 of file Component.h.
References type(), and type_.
Referenced by copy().
void Component::setPlacement (point_t centroid, double length)
set the placement of the object
Parameters:
centroid is the centroid position vector
length is the length of the object
Definition at line 380 of file Component.cpp.
References geom(), and nuclide_model_.
const Temp Component::temp ()
get the Temperature
Returns:
temp_
Definition at line 353 of file Component.cpp.
References temp_.
const Temp Component::temp_lim ()
get the maximum Temperature this object allows at its boundaries
Returns:
temp_lim_
Definition at line 346 of file Component.cpp.
References temp_lim_.
ThermalModelPtr Component::thermal_model (QueryEngine * qe)
Returns a new thermal model of the string type QueryEngine object.
Parameters:
qe is the QueryEngine object containing intialization info
Returns:
thermal_model_ a pointer to the ThermalModel that was created
Definition at line 269 of file Component.cpp.
References ThermalModelFactory::thermalModel().
ThermalModelPtr Component::thermal_model ()
gets the pointer to the thermal model being used in this component
Returns:
thermal_model_
Definition at line 377 of file Component.cpp.
References thermal_model_.
Referenced by initModuleMembers().
void Component::transportHeat (int time)
Transports heat from the inner boundary to the outer boundary in this component.
Parameters:
time the timestep at which to transport the heat
Definition at line 198 of file Component.cpp.
References thermal_model_.
void Component::transportNuclides (int time)
Transports nuclides from the inner boundary to the outer boundary in this component.
Parameters:
time the timestep at which to transport the nuclides
Definition at line 206 of file Component.cpp.
References nuclide_daughters(), and nuclide_model().
ComponentType Component::type ()
Returns the ComponentType of this component (WF, WP, etc.)
Returns:
type_ the ComponentType of this component
Definition at line 243 of file Component.cpp.
References type_.
Referenced by componentEnum(), init(), initModuleMembers(), isFull(), and set_type().
void Component::updateContaminantTable (int the_time)
Updates the gen_repo_contaminant_table_ for this component.
Definition at line 162 of file Component.cpp.
References ID(), and nuclide_model().
const deque< mat_rsrc_ptr > Component::wastes ()
get the list of waste objects
Returns:
wastes
Definition at line 343 of file Component.cpp.
References nuclide_model().
Referenced by print().
const double Component::x ()
get the x component of the centroid position vector of the object
Definition at line 365 of file Component.cpp.
References geom_.
const double Component::y ()
get the y component of the centroid position vector of the object
Definition at line 368 of file Component.cpp.
References geom_.
const double Component::z ()
get the z component of the centroid position vector of the object
Definition at line 371 of file Component.cpp.
References geom_.
Member Data Documentation
CompHistory Component::comp_hist_ protected
The composition history of this Component, in the form of a map whose keys are integers representing the time at which this Component had a particular composition and whose values are the corresponding compositions.
A composition is a map of isotopes and their corresponding number of atoms.
Definition at line 405 of file Component.h.
Referenced by Component(), copy(), and init().
ConcMap Component::concentrations_ protected
The concentrations of contaminant isotopes in the component.
Definition at line 485 of file Component.h.
Model* Component::creator_ protected
the genrepo that created/owns this component
Definition at line 488 of file Component.h.
Referenced by Component().
std::vector<ComponentPtr> Component::daughters_ protected
The immediate daughter components of this component.
Definition at line 439 of file Component.h.
Referenced by daughters(), isFull(), load(), and nuclide_daughters().
GeometryPtr Component::geom_ protected
The geometry of the cylindrical component, a shared pointer.
Definition at line 454 of file Component.h.
Referenced by centroid(), geom(), inner_radius(), outer_radius(), set_geom(), x(), y(), and z().
int Component::ID_ protected
The serial number for this Component.
Definition at line 391 of file Component.h.
Referenced by copy(), ID(), and init().
MassHistory Component::mass_hist_ protected
The mass history of this Component, in the form of a map whose keys are integers representing the time at which this Component had a particular composition and whose values are the corresponding mass compositions.
A composition is a map of isotopes and the corresponding masses.
Definition at line 414 of file Component.h.
Referenced by Component(), copy(), and init().
std::string Component::mat_ protected
The type of thermal model implemented by this component.
Definition at line 419 of file Component.h.
MatDataTablePtr Component::mat_table_ protected
A pointer to the MatDataTable representing this Component's material.
Definition at line 449 of file Component.h.
Referenced by mat_table(), and set_mat_table().
std::string Component::name_ protected
The name of this component, a string.
Definition at line 444 of file Component.h.
Referenced by copy(), init(), name(), and set_name().
int Component::nextID_ = 0 static protected
Stores the next available component ID.
Definition at line 396 of file Component.h.
Referenced by copy(), and init().
NuclideModelPtr Component::nuclide_model_ protected
The type of nuclide model implemented by this component.
Definition at line 429 of file Component.h.
Referenced by nuclide_model(), set_nuclide_model(), and setPlacement().
ComponentPtr Component::parent_ protected
The immediate parent component of this component.
Definition at line 434 of file Component.h.
Referenced by parent(), and set_parent().
Temp Component::peak_inner_temp_ protected
The peak temp achieved at the inner boundary.
Definition at line 474 of file Component.h.
Referenced by peak_temp().
Temp Component::peak_outer_temp_ protected
The peak temp achieved at the outer boundary.
Definition at line 469 of file Component.h.
Referenced by peak_temp().
Temp Component::temp_ protected
The temp taken to be the homogeneous temp of the whole component.
Definition at line 480 of file Component.h.
Referenced by copy(), and temp().
Temp Component::temp_lim_ protected
The temp limit of this component.
Definition at line 464 of file Component.h.
Referenced by copy(), and temp_lim().
ThermalModelPtr Component::thermal_model_ protected
The type of thermal model implemented by this component.
Definition at line 424 of file Component.h.
Referenced by set_thermal_model(), thermal_model(), and transportHeat().
ComponentType Component::type_ protected
The type of component that this component represents (ff, buffer, wp, etc.)
Definition at line 459 of file Component.h.
Referenced by init(), set_type(), and type().
The documentation for this class was generated from the following files:
Component.h
Component.cpp