cyder: MatToolsTests.cpp File Reference
MatToolsTests.cpp File Reference
#include <deque>
#include <map>
#include <gtest/gtest.h>
#include "CycLimits.h"
#include "CycException.h"
#include "Material.h"
#include "MatTools.h"
#include "NuclideModel.h"
Classes
class MatToolsTest
Functions
TEST_F (MatToolsTest, sum_mats_empty)
TEST_F (MatToolsTest, sum_mats_one)
TEST_F (MatToolsTest, sum_mats_small_entry)
TEST_F (MatToolsTest, extract)
TEST_F (MatToolsTest, convert_comp_to_conc)
TEST_F (MatToolsTest, scale_conc_map)
TEST_F (MatToolsTest, scale_zero_conc_map)
TEST_F (MatToolsTest, validate_finite_pos)
TEST_F (MatToolsTest, V_f)
TEST_F (MatToolsTest, V_ff)
TEST_F (MatToolsTest, V_mf)
TEST_F (MatToolsTest, V_s)
TEST_F (MatToolsTest, V_ds)
TEST_F (MatToolsTest, V_ms)
TEST_F (MatToolsTest, conc_to_conc_map)
TEST_F (MatToolsTest, isoToElem)
Function Documentation
TEST_F (MatToolsTest , sum_mats_empty)
Definition at line 48 of file MatToolsTests.cpp.
References MatTools::sum_mats().
TEST_F (MatToolsTest , sum_mats_one)
Definition at line 58 of file MatToolsTests.cpp.
References MatTools::sum_mats().
TEST_F (MatToolsTest , sum_mats_small_entry)
Definition at line 74 of file MatToolsTests.cpp.
References MatTools::sum_mats().
TEST_F (MatToolsTest , extract)
Definition at line 100 of file MatToolsTests.cpp.
TEST_F (MatToolsTest , convert_comp_to_conc)
Definition at line 105 of file MatToolsTests.cpp.
References MatTools::comp_to_conc_map().
TEST_F (MatToolsTest , scale_conc_map)
Definition at line 132 of file MatToolsTests.cpp.
References MatTools::scaleConcMap().
TEST_F (MatToolsTest , scale_zero_conc_map)
Definition at line 150 of file MatToolsTests.cpp.
References MatTools::scaleConcMap().
TEST_F (MatToolsTest , validate_finite_pos)
Definition at line 169 of file MatToolsTests.cpp.
References MatTools::validate_finite_pos().
TEST_F (MatToolsTest , V_f)
Definition at line 177 of file MatToolsTests.cpp.
References MatTools::V_f().
TEST_F (MatToolsTest , V_ff)
Definition at line 191 of file MatToolsTests.cpp.
References MatTools::V_ff().
TEST_F (MatToolsTest , V_mf)
Definition at line 213 of file MatToolsTests.cpp.
References MatTools::V_mf().
TEST_F (MatToolsTest , V_s)
Definition at line 235 of file MatToolsTests.cpp.
References MatTools::V_s().
TEST_F (MatToolsTest , V_ds)
Definition at line 249 of file MatToolsTests.cpp.
References MatTools::V_ds().
TEST_F (MatToolsTest , V_ms)
Definition at line 271 of file MatToolsTests.cpp.
References MatTools::V_ms().
TEST_F (MatToolsTest , conc_to_conc_map)
Definition at line 294 of file MatToolsTests.cpp.
References MatTools::conc_to_comp_map().
TEST_F (MatToolsTest , isoToElem)
Definition at line 299 of file MatToolsTests.cpp.
References MatTools::isoToElem().