cyder: th_params_t Struct Reference
th_params_t Struct Reference
Defines the structure of data associated with this row location in the database.
#include <STCDataTable.h>
Public Member Functions
th_params_t & a (double a_in)
th_params_t & k (double k_in)
th_params_t & r (double r_in)
th_params_t & s (double s_in)
Public Attributes
double alpha_th
a double indicating the thermal diffusivity of the material [] >
double k_th
a double indicating the thermal conductivity of the material [] >
double r_calc
a double indicating the radius where the STC is calculated >
double spacing
a double indicating the uniform spacing between packages [m] >
Detailed Description
Defines the structure of data associated with this row location in the database.
Definition at line 19 of file STCDataTable.h.
Member Function Documentation
th_params_t& th_params_t::a (double a_in) inline
Definition at line 27 of file STCDataTable.h.
References alpha_th.
Referenced by STCThermal::initializeSTCTable(), and STCDBTest::SetUp().
th_params_t& th_params_t::k (double k_in) inline
Definition at line 28 of file STCDataTable.h.
References k_th.
Referenced by STCThermal::initializeSTCTable(), and STCDBTest::SetUp().
th_params_t& th_params_t::r (double r_in) inline
Definition at line 30 of file STCDataTable.h.
References r_calc.
Referenced by STCThermal::initializeSTCTable(), and STCDBTest::SetUp().
th_params_t& th_params_t::s (double s_in) inline
Definition at line 29 of file STCDataTable.h.
References spacing.
Referenced by STCThermal::initializeSTCTable(), and STCDBTest::SetUp().
Member Data Documentation
double th_params_t::alpha_th
a double indicating the thermal diffusivity of the material [] >
Definition at line 22 of file STCDataTable.h.
Referenced by a(), STCDB::mat_name(), STCDB::table_id(), and STCDB::whereClause().
double th_params_t::k_th
a double indicating the thermal conductivity of the material [] >
Definition at line 23 of file STCDataTable.h.
Referenced by k(), STCDB::mat_name(), STCDB::table_id(), and STCDB::whereClause().
double th_params_t::r_calc
a double indicating the radius where the STC is calculated >
Definition at line 25 of file STCDataTable.h.
Referenced by STCDB::mat_name(), r(), STCDB::table_id(), and STCDB::whereClause().
double th_params_t::spacing
a double indicating the uniform spacing between packages [m] >
Definition at line 24 of file STCDataTable.h.
Referenced by STCDB::mat_name(), s(), STCDB::table_id(), and STCDB::whereClause().
The documentation for this struct was generated from the following file:
STCDataTable.h